### ISSUE TITLE
dva build error

### ISSUE THREAD

**Issue by lbbc1117** [AKSHAYUBHAT/DeepVideoAnalytics#10]
When I run 
`docker-compose up`
I got 
> Building dva
Step 1/42 : FROM tensorflow/tensorflow:1.0.0
ERROR: Service 'dva' failed to build: Get https://registry-1.docker.io/v2/: EOF

What I've done wrong?

**Comment by AKSHAYUBHAT** [comment]
This looks mostly like an error due to you not being able to connect to docker registry, may due to proxy? 

try if 
`docker pull tensorflow/tensorflow:1.0.0` 
works
