### ISSUE TITLE
Error executing 'detect_text.ipynb'

### ISSUE THREAD

**Issue by JoshuaMolina** [AKSHAYUBHAT/DeepVideoAnalytics#100]
Hello,

I have a problem when executing the script 'detect_text.ipynb'. I follow the steps described in the readme.md, and when I execute the following command:
**_docker run -p 8888: 8888 -it akshayubhat / dva-auto: latest_**

The result is this:

**_C:\Users\jmolinat>docker run -p 8888:8888 -it akshayubhat/dva-auto:latest
Unable to find image 'akshayubhat/dva-auto:latest' locally
latest: Pulling from akshayubhat/dva-auto
01a4f8387457: Pull complete
...
78b2841c8959: Pull complete
Digest: sha256:99c8fcc4a9935c21d9535bd76ba675bb0722dbf4aa1be657334fc4753ba8d4f6
Status: Downloaded newer image for akshayubhat/dva-auto:latest
root@b0d7ba8b7630:~/DVA# dir
LICENSE   buildpack-run.sh  configs  dva     dvalib  fabfile.py  manage.py  readme.md   repos             runtime.txt  templates  tutorial
Procfile  client            deploy   dvaapp  dvaui   logs        notebooks  readme.pdf  requirements.txt  scripts      tests
root@b0d7ba8b7630:~/DVA#_**

I don't know where the url of the Jupyter Notebook is, as discussed in the readme.md, in order to execute the script. And jupyter is not installed in the docker.

On the other hand, I have tried to do otherwise cloning the github repository on my computer, through my environment and running the command Jupyter notebook, run the script detect_text.ipynb. But I get this error and I can not find a way to fix it:

**_text_detector = detector.TextBoxDetector(model_path='../../repos/tf_ctpn_cpu/checkpoints/')
text_detector.load()
box_count = 0
for im_name in glob("images/*.jpg"):
    display(Image(im_name,width=300))
    regions = text_detector.detect(im_name)
    im=cv2.imread(im_name)
    for k in regions:
        crop_img = im[int(k['x']):int(k['x'] + k['w']),int(k['y']):int(k['y'] + k['h'])]
        print k['score']
        cv2.imwrite('boxes/box_{}.jpg'.format(box_count),crop_img)
        display(Image('boxes/box_{}.jpg'.format(box_count)))
        box_count += 1

NameError                                 Traceback (most recent call last)
<ipython-input-2-c7d60dec0e76> in <module>()
      1 text_detector = detector.TextBoxDetector(model_path='../../repos/tf_ctpn_cpu/checkpoints/')
----> 2 text_detector.load()
      3 box_count = 0
      4 for im_name in glob("images/*.jpg"):
      5     display(Image(im_name,width=300))

/imatge/jmolina/DeepVideoAnalytics-master/dvalib/detector.pyc in load(self)
    248     def load(self):
    249         logging.info('Creating networks and loading parameters')
--> 250         cfg_from_file(os.path.join(os.path.dirname(__file__),'ctpn/text.yml'))
    251         gpu_options = tf.GPUOptions(per_process_gpu_memory_fraction=self.gpu_fraction)
    252         config = tf.ConfigProto(allow_soft_placement=True,gpu_options=gpu_options)

NameError: global name 'cfg_from_file' is not defined_**

Let's see if someone can help me solve this problem.

Regards and thank you very much.

**Comment by ericjenott** [comment]
I am also having the same problem.  Seems the "lib" directory doesn't exist inside the "dvalib" directory.  I tried copying it from repos/tf_ctpn_cpu/lib into dvalib and had some success after changing some imports and paths in the code, but eventually got stuck.

**Comment by AKSHAYUBHAT** [comment]
Hey let me take a look. I think it appears that the weights are not available in the checkpoint folder inside repos/tf_ctpn/

**Comment by AKSHAYUBHAT** [comment]
Okay I have fixed it, make sure that you follow steps in readme.md at 

https://github.com/AKSHAYUBHAT/DeepVideoAnalytics/tree/master/notebooks/OCR

to start docker container, install and start jupyter inside the container. 

The detection notebook has also been updated with shell commands to download model checkpoint.

https://github.com/AKSHAYUBHAT/DeepVideoAnalytics/blob/master/notebooks/OCR/detect_text.ipynb

**Comment by JoshuaMolina** [comment]
Hello again,

first of all, thanks for answering so fast in the previous post. I have followed the steps that have been updated and the following happens:

I tried the docker solution and I get this error:

**_ImportError Traceback (most recent call last)
<ipython-input-1-c44efc1161b3> in <module>()
      2 sys.path.append('/opt/ctpn/CTPN/tools/')
      3 sys.path.append('/opt/ctpn/CTPN/src/')
----> 4 from cfg import Config as cfg
      5 from other import draw_boxes, resize_im, CaffeModel
      6 import cv2, os, caffe, sys

ImportError: No module named cfg
The problem seems to be that the /opt folder in docker is empty:

root@7962411c9077:~/DVA/notebooks/OCR# ls -alF /opt
total 8
drwxr-xr-x 2 root root 4096 Nov 17 15:32 ./
drwxr-xr-x 1 root root 4096 Dec 15 16:56 ../
root@7962411c9077:~/DVA/notebooks/OCR#_** 

I'm a bit confused because the detect_text.ipynb in the docker is different from the detect_text.ipynb downloaded from DeepVideoAnalytics github.
I also tried to run this one (without docker). I had to manually create directory 'repos/tf_ctpn_cpu/checkpoints' because it did not exist. Once I did this, several files are downloaded but then I obtain again error:

**_NameError Traceback (most recent call last)
<ipython-input-2-e3618d152545> in <module>()
      1 text_detector = detector.TextBoxDetector(model_path='../../repos/tf_ctpn_cpu/checkpoints/')
----> 2 text_detector.load()
      3 box_count = 0
      4 for im_name in glob("images/*.jpg"):
      5     display(Image(im_name,width=300))

/imatge/morros/workspace/text/DeepVideoAnalytics/dvalib/detector.pyc in load(self)
    248     def load(self):
    249         logging.info('Creating networks and loading parameters')
--> 250         cfg_from_file(os.path.join(os.path.dirname(__file__),'ctpn/text.yml'))
    251         gpu_options = tf.GPUOptions(per_process_gpu_memory_fraction=self.gpu_fraction)
    252         config = tf.ConfigProto(allow_soft_placement=True,gpu_options=gpu_options)

NameError: global name 'cfg_from_file' is not defined_**

Let's see if someone can help me solve this new problem.

Regards and thank you very much.
