### ISSUE TITLE
Error executing 'detect_text.ipynb' update

### ISSUE THREAD

**Issue by JoshuaMolina** [AKSHAYUBHAT/DeepVideoAnalytics#101]
Hello again,

first of all, thanks for answering so fast in the previous post. I have followed the steps that have been updated and the following happens:

I tried the docker solution and I get this error:

**_ImportError Traceback (most recent call last)
in ()
2 sys.path.append('/opt/ctpn/CTPN/tools/')
3 sys.path.append('/opt/ctpn/CTPN/src/')
----> 4 from cfg import Config as cfg
5 from other import draw_boxes, resize_im, CaffeModel
6 import cv2, os, caffe, sys

ImportError: No module named cfg
The problem seems to be that the /opt folder in docker is empty:

root@7962411c9077:/DVA/notebooks/OCR# ls -alF /opt
total 8
drwxr-xr-x 2 root root 4096 Nov 17 15:32 ./
drwxr-xr-x 1 root root 4096 Dec 15 16:56 ../
root@7962411c9077:/DVA/notebooks/OCR#_**

I'm a bit confused because the detect_text.ipynb in the docker is different from the detect_text.ipynb downloaded from DeepVideoAnalytics github.
I also tried to run this one (without docker). I had to manually create directory 'repos/tf_ctpn_cpu/checkpoints' because it did not exist. Once I did this, several files are downloaded but then I obtain again error:

**_NameError Traceback (most recent call last)
in ()
1 text_detector = detector.TextBoxDetector(model_path='../../repos/tf_ctpn_cpu/checkpoints/')
----> 2 text_detector.load()
3 box_count = 0
4 for im_name in glob("images/*.jpg"):
5 display(Image(im_name,width=300))

/imatge/morros/workspace/text/DeepVideoAnalytics/dvalib/detector.pyc in load(self)
248 def load(self):
249 logging.info('Creating networks and loading parameters')
--> 250 cfg_from_file(os.path.join(os.path.dirname(file),'ctpn/text.yml'))
251 gpu_options = tf.GPUOptions(per_process_gpu_memory_fraction=self.gpu_fraction)
252 config = tf.ConfigProto(allow_soft_placement=True,gpu_options=gpu_options)

NameError: global name 'cfg_from_file' is not defined_**

Let's see if someone can help me solve this new problem.

Regards and thank you very much.

**Comment by AKSHAYUBHAT** [comment]
Your docker image is old, update to latest docker image by running the following command.
`docker rmi akshayubhat/dva-auto:gpu && docker pull akshayubhat/dva-auto:gpu`
