### ISSUE TITLE
Continuation error executing detect_text.py with docker

### ISSUE THREAD

**Issue by JoshuaMolina** [AKSHAYUBHAT/DeepVideoAnalytics#103]
Hello,

following the last command you told me:
**_docker rmi akshayubhat / dva-auto: latest && docker pull akshayubhat / dva-auto: latest_**

Continue giving the same error as before:

import sys
sys.path.append('/opt/ctpn/CTPN/tools/')
sys.path.append('/opt/ctpn/CTPN/src/')
from cfg import Config as cfg
from other import draw_boxes, resize_im, CaffeModel
import cv2, os, caffe, sys
from detectors import TextProposalDetector, TextDetector
import os.path as osp
from utils.timer import Timer
from IPython.core.display import Image, display

DEMO_IMAGE_DIR="demo_images/"
NET_DEF_FILE="/opt/ctpn/CTPN/models/deploy.prototxt"
MODEL_FILE="/opt/ctpn/CTPN/models/ctpn_trained_model.caffemodel"

if True: # Set this to true for CPU only mode
    caffe.set_mode_cpu()
else:
    caffe.set_mode_gpu()
    caffe.set_device(cfg.TEST_GPU_ID)

text_proposals_detector=TextProposalDetector(CaffeModel(NET_DEF_FILE, MODEL_FILE))
text_detector=TextDetector(text_proposals_detector)
-------------------------------------------------------------------------------------------------------------------
ImportError Traceback (most recent call last)
<ipython-input-1-c44efc1161b3> in <module>()
      2 sys.path.append('/opt/ctpn/CTPN/tools/')
      3 sys.path.append('/opt/ctpn/CTPN/src/')
----> 4 from cfg import Config as cfg
      5 from other import draw_boxes, resize_im, CaffeModel
      6 import cv2, os, caffe, sys

ImportError: No module named cfg

It seems that the / opt directory is still empty, and for python commands it should contain CTPN.

Regards, and thank you very much.

Joshua Molina

**Comment by AKSHAYUBHAT** [comment]
It seems your docker containers have not been updated.
Try checking `docker image ls`.

**Comment by JoshuaMolina** [comment]
This is what the **_docker image ls_** command returns:

REPOSITORY                   TAG                IMAGE ID               CREATED              SIZE
akshayubhat/dva-auto   latest              29fbcef9bb73        3 weeks ago         2.96GB

**Comment by AKSHAYUBHAT** [comment]
It seems you are confusing between executing code inside the container vs on host OS. The github repo you cloned contains old code, the container which you pulled has the latest code.
