### ISSUE TITLE
about the delf

### ISSUE THREAD

**Issue by Usernamezhx** [AKSHAYUBHAT/DeepVideoAnalytics#109]
hi 
    I'm sorry to bother you. what confuse me is that if you use your own data to train the delf model ? I think the original model is good at landscape retrieving. thanks for advance.

**Comment by AKSHAYUBHAT** [comment]
Hey sorry I have not had time to integrate DELF yet, currently following indexing models are supported. 

- Inception pool3 for similar image retrieval
- VGG convolutional filters for instance retrieval (You need to install it via VDN)
- Facenet for face indexing / recognition

I was focused on incorporating vector space approximations LOPQ/PCA for efficient retrieval. 
With that almost done, I plan on incorporating DELF (for indexing) as well as LocationNet (for placing/predicting lat/long directly).

**Comment by Usernamezhx** [comment]
thanks your reply. you said the VGG convolution that means the Compression of Deep Neural Networks for Image Instance Retrieval ?can you provide more detail  : P .I search your project and find the vgg model in the slim/net. but that only provide the processing .
