### ISSUE TITLE
OSX 10.11, 'dva' build error

### ISSUE THREAD

**Issue by lbbc1117** [AKSHAYUBHAT/DeepVideoAnalytics#11]
> Building dva
Step 1/42 : FROM tensorflow/tensorflow:1.0.0
 ---> ea40dcc45724
Step 2/42 : MAINTAINER Akshay Bhat <akshayubhat@gmail.com>
 ---> Using cache
 ---> 389a74280567
Step 3/42 : RUN apt-get update && apt-get install -y wget
 ---> Running in cde6ff5740aa
Ign http://archive.ubuntu.com trusty InRelease
Get:1 http://archive.ubuntu.com trusty-updates InRelease [65.9 kB]
Get:2 http://archive.ubuntu.com trusty-security InRelease [65.9 kB]
Get:3 http://archive.ubuntu.com trusty Release.gpg [933 B]
Get:4 http://archive.ubuntu.com trusty-updates/main Sources [486 kB]
Get:5 http://archive.ubuntu.com trusty-updates/restricted Sources [5957 B]
Get:6 http://archive.ubuntu.com trusty-updates/universe Sources [221 kB]
Get:7 http://archive.ubuntu.com trusty-updates/main amd64 Packages [641 kB]
Get:8 http://archive.ubuntu.com trusty-updates/restricted amd64 Packages [1131 kB]
Get:9 http://archive.ubuntu.com trusty-updates/universe amd64 Packages [519 kB]
Get:10 http://archive.ubuntu.com trusty-security/main Sources [162 kB]
Get:11 http://archive.ubuntu.com trusty-security/restricted Sources [4667 B]
Get:12 http://archive.ubuntu.com trusty-security/universe Sources [59.4 kB]
Get:13 http://archive.ubuntu.com trusty-security/main amd64 Packages [736 kB]
Get:14 http://archive.ubuntu.com trusty-security/restricted amd64 Packages [17.0 kB]
Get:15 http://archive.ubuntu.com trusty-security/universe amd64 Packages [200 kB]
Get:16 http://archive.ubuntu.com trusty Release [58.5 kB]
Get:17 http://archive.ubuntu.com trusty/main Sources [1335 kB]
Get:18 http://archive.ubuntu.com trusty/restricted Sources [5335 B]
Get:19 http://archive.ubuntu.com trusty/universe Sources [7926 kB]
Get:20 http://archive.ubuntu.com trusty/main amd64 Packages [1743 kB]
Get:21 http://archive.ubuntu.com trusty/restricted amd64 Packages [1640 kB]
Get:22 http://archive.ubuntu.com trusty/universe amd64 Packages [7589 kB]
Fetched 24.6 MB in 5min 0s (81.9 kB/s)
W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/trusty-updates/main/binary-amd64/Packages  Hash Sum mismatch
W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/trusty-updates/restricted/binary-amd64/Packages  Hash Sum mismatch
W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/trusty/restricted/binary-amd64/Packages  Hash Sum mismatch
E: Some index files failed to download. They have been ignored, or old ones used instead.
ERROR: Service 'dva' failed to build: The command '/bin/sh -c apt-get update && apt-get install -y wget' returned a non-zero code: 100

Is this due to proxy?

**Comment by AKSHAYUBHAT** [comment]
Hash sum mismatch means the downloaded version has errors and that's why the computed hash does not matches the expected one. 

Rather than building the image, you can just pull all layers from the Docker hub by running.

`docker pull akshayubhat/deepvideoanalytics:cpu`

**Comment by AKSHAYUBHAT** [comment]
Assuming this worked out.

**Comment by lbbc1117** [comment]
Thanks,  it works
