### ISSUE TITLE
Could I use it for video retrieval using video clips? 

### ISSUE THREAD

**Issue by huangxiaosa** [AKSHAYUBHAT/DeepVideoAnalytics#110]
# Checklist for submitting an issue 

- Have you verified that docker is installed correctly and e.g. GFW is not preventing downloads?

- Which docker-compose.yml file are you using?

- Please post output of `docker ps -a` or confirm that all containers are running?

- If a specific container is not running or "exited" please post output of `docker logs <name of the container>`

- Is your question about OCR blog post in notebooks/OCR/ ?

**Comment by AKSHAYUBHAT** [comment]
You can technically feed individual frames as separate queries. In future the query processing pipeline will be extended to use short video clips.
