### ISSUE TITLE
dvaapp.models.MultipleObjectsReturned: get() returned more than one TrainedModel -- it returned 2!

### ISSUE THREAD

**Issue by ericjenott** [AKSHAYUBHAT/DeepVideoAnalytics#112]
Hello Mr. Bhat,

I'm having a problem with the multiple GPU version.  With the exceptions of gpu_global-model_1, dva-pg, and dva-rmq, all of the docker containers exit with errors.  gpu_crnn_1, gpu_textbox_1, gpu_inception_1, gpu_facenet_1, gpu_webserver_1, gpu_non-gpu-workers_1 all get the error "dvaapp.models.MultipleObjectsReturned: get() returned more than one TrainedModel -- it returned 2!", and exit.  Most of the rest exit with various SQL errors.  I'll post the whole log below.  I've tried doing a fresh git clone, deleting all my docker containers, images, and volumes, and starting over from a clean start, but I still get these messages.  Please let me know if you can see anything that I'm doing wrong.  Thanks!

webserver_1        | WARNING:root:Could not import indexer / clustering assuming running in front-end mode
webserver_1        | System check identified some issues:
webserver_1        | 
webserver_1        | WARNINGS:
webserver_1        | ?: (rest_framework.W001) You have specified a default PAGE_SIZE pagination rest_framework setting,without specifying also a DEFAULT_PAGINATION_CLASS.
webserver_1        | 	HINT: The default for DEFAULT_PAGINATION_CLASS is None. In previous versions this was PageNumberPagination. If you wish to define PAGE_SIZE globally whilst defining pagination_class on a per-view basis you may silence this check.
webserver_1        | No changes detected
webserver_1        | WARNING:root:Could not import indexer / clustering assuming running in front-end mode
webserver_1        | System check identified some issues:
webserver_1        | 
webserver_1        | WARNINGS:
webserver_1        | ?: (rest_framework.W001) You have specified a default PAGE_SIZE pagination rest_framework setting,without specifying also a DEFAULT_PAGINATION_CLASS.
webserver_1        | 	HINT: The default for DEFAULT_PAGINATION_CLASS is None. In previous versions this was PageNumberPagination. If you wish to define PAGE_SIZE globally whilst defining pagination_class on a per-view basis you may silence this check.
webserver_1        | Operations to perform:
webserver_1        |   Apply all migrations: admin, auth, authtoken, contenttypes, django_celery_beat, django_celery_results, dvaapp, dvaui, sessions
webserver_1        | Running migrations:
webserver_1        |   Applying contenttypes.0001_initial... OK
webserver_1        |   Applying auth.0001_initial... OK
webserver_1        |   Applying admin.0001_initial... OK
webserver_1        |   Applying admin.0002_logentry_remove_auto_add... OK
webserver_1        |   Applying contenttypes.0002_remove_content_type_name... OK
webserver_1        |   Applying auth.0002_alter_permission_name_max_length... OK
webserver_1        |   Applying auth.0003_alter_user_email_max_length... OK
webserver_1        |   Applying auth.0004_alter_user_username_opts... OK
webserver_1        |   Applying auth.0005_alter_user_last_login_null... OK
webserver_1        |   Applying auth.0006_require_contenttypes_0002... OK
webserver_1        |   Applying auth.0007_alter_validators_add_error_messages... OK
webserver_1        |   Applying auth.0008_alter_user_username_max_length... OK
webserver_1        |   Applying authtoken.0001_initial... OK
webserver_1        |   Applying authtoken.0002_auto_20160226_1747... OK
webserver_1        |   Applying django_celery_beat.0001_initial... OK
webserver_1        |   Applying django_celery_beat.0002_auto_20161118_0346... OK
webserver_1        |   Applying django_celery_beat.0003_auto_20161209_0049... OK
webserver_1        |   Applying django_celery_beat.0004_auto_20170221_0000... OK
webserver_1        |   Applying django_celery_results.0001_initial... OK
webserver_1        |   Applying dvaapp.0001_initial... OK
webserver_1        |   Applying dvaapp.custom_migration... OK
webserver_1        |   Applying dvaapp.0001_auto_20170825_1749... OK
webserver_1        |   Applying dvaapp.0002_detector_queue... OK
webserver_1        |   Applying dvaapp.0003_auto_20170826_0041... OK
dva-pg             | ERROR:  duplicate key value violates unique constraint "auth_user_username_key"
dva-pg             | DETAIL:  Key (username)=(akshay) already exists.
dva-pg             | STATEMENT:  INSERT INTO "auth_user" ("password", "last_login", "is_superuser", "username", "first_name", "last_name", "email", "is_staff", "is_active", "date_joined") VALUES ('pbkdf2_sha256$36000$RIFRUug7V9fx$5kpuJ+eKLH/k9AZ+5DvEV0YRRH9DAzECqS9xXv8LjTI=', NULL, true, 'akshay', '', '', 'akshay@deepvideoanalytics.com', true, true, '2018-01-02T13:58:17.021504+00:00'::timestamptz) RETURNING "auth_user"."id"
coco_1             | Traceback (most recent call last):
coco_1             |   File "./init_fs.py", line 21, in <module>
coco_1             |     email=os.environ['SUPEREMAIL'])
coco_1             |   File "/usr/local/lib/python2.7/dist-packages/django/contrib/auth/models.py", line 170, in create_superuser
coco_1             |     return self._create_user(username, email, password, **extra_fields)
coco_1             |   File "/usr/local/lib/python2.7/dist-packages/django/contrib/auth/models.py", line 153, in _create_user
coco_1             |     user.save(using=self._db)
coco_1             |   File "/usr/local/lib/python2.7/dist-packages/django/contrib/auth/base_user.py", line 80, in save
coco_1             |     super(AbstractBaseUser, self).save(*args, **kwargs)
coco_1             |   File "/usr/local/lib/python2.7/dist-packages/django/db/models/base.py", line 807, in save
coco_1             |     force_update=force_update, update_fields=update_fields)
coco_1             |   File "/usr/local/lib/python2.7/dist-packages/django/db/models/base.py", line 837, in save_base
coco_1             |     updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
coco_1             |   File "/usr/local/lib/python2.7/dist-packages/django/db/models/base.py", line 923, in _save_table
coco_1             |     result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
coco_1             |   File "/usr/local/lib/python2.7/dist-packages/django/db/models/base.py", line 962, in _do_insert
coco_1             |     using=using, raw=raw)
coco_1             |   File "/usr/local/lib/python2.7/dist-packages/django/db/models/manager.py", line 85, in manager_method
coco_1             |     return getattr(self.get_queryset(), name)(*args, **kwargs)
coco_1             |   File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 1076, in _insert
coco_1             |     return query.get_compiler(using=using).execute_sql(return_id)
coco_1             |   File "/usr/local/lib/python2.7/dist-packages/django/db/models/sql/compiler.py", line 1099, in execute_sql
dva-pg             | ERROR:  relation "dvaui_externalserver" does not exist at character 35
dva-pg             | STATEMENT:  SELECT COUNT(*) AS "__count" FROM "dvaui_externalserver"
coco_1             |     cursor.execute(sql, params)
coco_1             |   File "/usr/local/lib/python2.7/dist-packages/django/db/backends/utils.py", line 65, in execute
face_1             | Traceback (most recent call last):
face_1             |   File "./init_fs.py", line 28, in <module>
face_1             |     if ExternalServer.objects.count() == 0:
face_1             |   File "/usr/local/lib/python2.7/dist-packages/django/db/models/manager.py", line 85, in manager_method
face_1             |     return getattr(self.get_queryset(), name)(*args, **kwargs)
face_1             |   File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 364, in count
face_1             |     return self.query.get_count(using=self.db)
face_1             |   File "/usr/local/lib/python2.7/dist-packages/django/db/models/sql/query.py", line 499, in get_count
face_1             |     number = obj.get_aggregation(using, ['__count'])['__count']
face_1             |   File "/usr/local/lib/python2.7/dist-packages/django/db/models/sql/query.py", line 480, in get_aggregation
face_1             |     result = compiler.execute_sql(SINGLE)
face_1             |   File "/usr/local/lib/python2.7/dist-packages/django/db/models/sql/compiler.py", line 886, in execute_sql
face_1             |     raise original_exception
face_1             | django.db.utils.ProgrammingError: relation "dvaui_externalserver" does not exist
face_1             | LINE 1: SELECT COUNT(*) AS "__count" FROM "dvaui_externalserver"
face_1             |                                           ^
face_1             | 
coco_1             |     return self.cursor.execute(sql, params)
coco_1             |   File "/usr/local/lib/python2.7/dist-packages/django/db/utils.py", line 94, in __exit__
coco_1             |     six.reraise(dj_exc_type, dj_exc_value, traceback)
coco_1             |   File "/usr/local/lib/python2.7/dist-packages/django/db/backends/utils.py", line 65, in execute
coco_1             |     return self.cursor.execute(sql, params)
coco_1             | django.db.utils.IntegrityError: duplicate key value violates unique constraint "auth_user_username_key"
coco_1             | DETAIL:  Key (username)=(akshay) already exists.
coco_1             | 
face_1             | Traceback (most recent call last):
face_1             |   File "./start_container.py", line 15, in <module>
face_1             |     subprocess.check_call(['./init_fs.py',])
face_1             |   File "/usr/lib/python2.7/subprocess.py", line 541, in check_call
face_1             |     raise CalledProcessError(retcode, cmd)
face_1             | subprocess.CalledProcessError: Command '['./init_fs.py']' returned non-zero exit status 1
coco_1             | Traceback (most recent call last):
coco_1             |   File "./start_container.py", line 15, in <module>
coco_1             |     subprocess.check_call(['./init_fs.py',])
coco_1             |   File "/usr/lib/python2.7/subprocess.py", line 541, in check_call
coco_1             |     raise CalledProcessError(retcode, cmd)
coco_1             | subprocess.CalledProcessError: Command '['./init_fs.py']' returned non-zero exit status 1
gpu_coco_1 exited with code 1
webserver_1        |   Applying dvaapp.0004_auto_20170826_0641... OK
gpu_face_1 exited with code 1
webserver_1        |   Applying dvaapp.0005_auto_20170826_1539... OK
webserver_1        |   Applying dvaapp.0006_auto_20170826_1617... OK
webserver_1        |   Applying dvaapp.0007_auto_20170826_1644... OK
webserver_1        |   Applying dvaapp.0008_auto_20170826_1644... OK
webserver_1        |   Applying dvaapp.0009_auto_20170826_1918... OK
webserver_1        |   Applying dvaapp.0010_auto_20170827_1626... OK
webserver_1        |   Applying dvaapp.0011_auto_20170828_2143... OK
webserver_1        |   Applying dvaapp.0012_auto_20170829_0528... OK
webserver_1        |   Applying dvaapp.0013_indexentries_indexer_shasum... OK
webserver_1        |   Applying dvaapp.0014_auto_20170829_0635... OK
webserver_1        |   Applying dvaapp.0015_retriever_name... OK
webserver_1        |   Applying dvaapp.0016_auto_20170829_0959... OK
webserver_1        |   Applying dvaapp.0017_auto_20170829_1016... OK
webserver_1        |   Applying dvaapp.0018_auto_20170831_2141... OK
webserver_1        |   Applying dvaapp.0019_auto_20170831_2238... OK
webserver_1        |   Applying dvaapp.0020_retriever_last_built... OK
webserver_1        |   Applying dvaapp.0021_remove_video_query... OK
webserver_1        |   Applying dvaapp.0022_auto_20170901_2329... OK
webserver_1        |   Applying dvaapp.0023_auto_20170902_0516... OK
webserver_1        |   Applying dvaapp.0024_systemstate... OK
webserver_1        |   Applying dvaapp.0025_auto_20170903_0141... OK
webserver_1        |   Applying dvaapp.0026_worker... OK
webserver_1        |   Applying dvaapp.0027_worker_queue_name... OK
webserver_1        |   Applying dvaapp.0028_auto_20170905_1842... OK
webserver_1        |   Applying dvaapp.0029_queryregion... OK
webserver_1        |   Applying dvaapp.0030_queryregionindexvector... OK
webserver_1        |   Applying dvaapp.0031_auto_20170913_1927... OK
webserver_1        |   Applying dvaapp.0032_queryregionresults... OK
webserver_1        |   Applying dvaapp.0033_auto_20170920_0340... OK
webserver_1        |   Applying dvaapp.0034_auto_20171004_0351... OK
webserver_1        |   Applying dvaapp.0035_auto_20171004_0403... OK
webserver_1        |   Applying dvaapp.0036_deepmodel_parent... OK
tagger_1           | Traceback (most recent call last):
tagger_1           |   File "./init_fs.py", line 28, in <module>
tagger_1           |     if ExternalServer.objects.count() == 0:
tagger_1           |   File "/usr/local/lib/python2.7/dist-packages/django/db/models/manager.py", line 85, in manager_method
tagger_1           |     return getattr(self.get_queryset(), name)(*args, **kwargs)
tagger_1           |   File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 364, in count
tagger_1           |     return self.query.get_count(using=self.db)
tagger_1           |   File "/usr/local/lib/python2.7/dist-packages/django/db/models/sql/query.py", line 499, in get_count
tagger_1           |     number = obj.get_aggregation(using, ['__count'])['__count']
tagger_1           |   File "/usr/local/lib/python2.7/dist-packages/django/db/models/sql/query.py", line 480, in get_aggregation
tagger_1           |     result = compiler.execute_sql(SINGLE)
tagger_1           |   File "/usr/local/lib/python2.7/dist-packages/django/db/models/sql/compiler.py", line 886, in execute_sql
tagger_1           |     raise original_exception
tagger_1           | django.db.utils.ProgrammingError: relation "dvaui_externalserver" does not exist
tagger_1           | LINE 1: SELECT COUNT(*) AS "__count" FROM "dvaui_externalserver"
tagger_1           |                                           ^
tagger_1           | 
dva-pg             | ERROR:  relation "dvaui_externalserver" does not exist at character 35
dva-pg             | STATEMENT:  SELECT COUNT(*) AS "__count" FROM "dvaui_externalserver"
webserver_1        |   Applying dvaapp.0037_auto_20171022_0619... OK
tagger_1           | Traceback (most recent call last):
tagger_1           |   File "./start_container.py", line 15, in <module>
tagger_1           |     subprocess.check_call(['./init_fs.py',])
tagger_1           |   File "/usr/lib/python2.7/subprocess.py", line 541, in check_call
tagger_1           |     raise CalledProcessError(retcode, cmd)
tagger_1           | subprocess.CalledProcessError: Command '['./init_fs.py']' returned non-zero exit status 1
webserver_1        |   Applying dvaapp.0038_auto_20171022_0642... OK
webserver_1        |   Applying dvaapp.0039_worker_alive... OK
webserver_1        |   Applying dvaapp.0040_tevent_worker... OK
webserver_1        |   Applying dvaapp.0041_managementaction_ping_index... OK
webserver_1        |   Applying dvaapp.0042_delete_vdnserver... OK
webserver_1        |   Applying dvaapp.0043_auto_20171215_1206... OK
gpu_tagger_1 exited with code 1
webserver_1        |   Applying dvaapp.0044_auto_20171222_0539... OK
webserver_1        |   Applying dvaapp.0045_auto_20171222_0650... OK
webserver_1        |   Applying dvaapp.0046_trainingset... OK
webserver_1        |   Applying dvaapp.0047_workerrequest... OK
webserver_1        |   Applying dvaapp.0048_auto_20171224_2250... OK
webserver_1        |   Applying dvaapp.0049_trainingset_built... OK
webserver_1        |   Applying dvaapp.0050_delete_workerrequest... OK
webserver_1        |   Applying dvaapp.0051_auto_20171229_1000... OK
webserver_1        |   Applying dvaapp.0052_auto_20171230_0152... OK
webserver_1        |   Applying dvaapp.0053_retriever_approximator_shashum... OK
webserver_1        |   Applying dvaapp.0054_auto_20171230_0407... OK
webserver_1        |   Applying dvaapp.0055_auto_20171230_0534... OK
webserver_1        |   Applying dvaapp.0056_auto_20171230_1206... OK
webserver_1        |   Applying dvaapp.0057_tevent_task_group_id... OK
webserver_1        |   Applying dvaapp.0058_auto_20171231_2311... OK
webserver_1        |   Applying dvaapp.0059_auto_20180101_1037... OK
webserver_1        |   Applying dvaapp.0060_auto_20180101_2228... OK
webserver_1        |   Applying dvaapp.0061_auto_20180101_2245... OK
webserver_1        |   Applying dvaui.0001_initial... OK
webserver_1        |   Applying dvaui.0002_auto_20171216_0733... OK
webserver_1        |   Applying dvaui.0003_storeddvapql_server... OK
webserver_1        |   Applying sessions.0001_initial... OK
dva-pg             | ERROR:  duplicate key value violates unique constraint "dvaapp_deepmodel_shasum_key"
dva-pg             | DETAIL:  Key (shasum)=(9f99caccbc75dcee8cb0a55a0551d7c5cb8a6836) already exists.
dva-pg             | STATEMENT:  INSERT INTO "dvaapp_trainedmodel" ("detector_type", "mode", "model_type", "name", "algorithm", "shasum", "model_filename", "created", "arguments", "source_id", "trained", "url", "files", "produces_labels", "produces_json", "produces_text", "parent_id") VALUES (NULL, 'T', 'I', 'facenet', '', '9f99caccbc75dcee8cb0a55a0551d7c5cb8a6836', '', '2018-01-02T13:58:44.911095+00:00'::timestamptz, '{}', NULL, false, '', '[{"url": "https://www.dropbox.com/s/jytpgw8et09ede9/facenet.pb", "filename": "facenet.pb"}]', false, false, false, NULL) RETURNING "dvaapp_trainedmodel"."id"
dva-pg             | ERROR:  duplicate key value violates unique constraint "dvaapp_deepmodel_shasum_key"
dva-pg             | DETAIL:  Key (shasum)=(9f99caccbc75dcee8cb0a55a0551d7c5cb8a6836) already exists.
dva-pg             | STATEMENT:  INSERT INTO "dvaapp_trainedmodel" ("detector_type", "mode", "model_type", "name", "algorithm", "shasum", "model_filename", "created", "arguments", "source_id", "trained", "url", "files", "produces_labels", "produces_json", "produces_text", "parent_id") VALUES (NULL, 'T', 'I', 'facenet', '', '9f99caccbc75dcee8cb0a55a0551d7c5cb8a6836', '', '2018-01-02T13:58:44.911728+00:00'::timestamptz, '{}', NULL, false, '', '[{"url": "https://www.dropbox.com/s/jytpgw8et09ede9/facenet.pb", "filename": "facenet.pb"}]', false, false, false, NULL) RETURNING "dvaapp_trainedmodel"."id"
non-gpu-workers_1  | Traceback (most recent call last):
non-gpu-workers_1  |   File "./init_fs.py", line 50, in <module>
non-gpu-workers_1  |     model_type=m['model_type'])
non-gpu-workers_1  |   File "/usr/local/lib/python2.7/dist-packages/django/db/models/manager.py", line 85, in manager_method
non-gpu-workers_1  |     return getattr(self.get_queryset(), name)(*args, **kwargs)
non-gpu-workers_1  |   File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 464, in get_or_create
non-gpu-workers_1  |     return self.get(**lookup), False
non-gpu-workers_1  |   File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 384, in get
non-gpu-workers_1  |     (self.model._meta.object_name, num)
non-gpu-workers_1  | dvaapp.models.MultipleObjectsReturned: get() returned more than one TrainedModel -- it returned 2!
non-gpu-workers_1  | Traceback (most recent call last):
non-gpu-workers_1  |   File "./start_container.py", line 15, in <module>
non-gpu-workers_1  |     subprocess.check_call(['./init_fs.py',])
non-gpu-workers_1  |   File "/usr/lib/python2.7/subprocess.py", line 541, in check_call
non-gpu-workers_1  |     raise CalledProcessError(retcode, cmd)
non-gpu-workers_1  | subprocess.CalledProcessError: Command '['./init_fs.py']' returned non-zero exit status 1
gpu_non-gpu-workers_1 exited with code 1
webserver_1        | Traceback (most recent call last):
webserver_1        |   File "./init_fs.py", line 50, in <module>
webserver_1        |     model_type=m['model_type'])
webserver_1        |   File "/usr/local/lib/python2.7/dist-packages/django/db/models/manager.py", line 85, in manager_method
webserver_1        |     return getattr(self.get_queryset(), name)(*args, **kwargs)
webserver_1        |   File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 464, in get_or_create
webserver_1        |     return self.get(**lookup), False
webserver_1        |   File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 384, in get
webserver_1        |     (self.model._meta.object_name, num)
webserver_1        | dvaapp.models.MultipleObjectsReturned: get() returned more than one TrainedModel -- it returned 2!
webserver_1        | Traceback (most recent call last):
webserver_1        |   File "./start_container.py", line 15, in <module>
webserver_1        |     subprocess.check_call(['./init_fs.py',])
webserver_1        |   File "/usr/lib/python2.7/subprocess.py", line 541, in check_call
webserver_1        |     raise CalledProcessError(retcode, cmd)
webserver_1        | subprocess.CalledProcessError: Command '['./init_fs.py']' returned non-zero exit status 1
gpu_webserver_1 exited with code 1
facenet_1          | Traceback (most recent call last):
facenet_1          |   File "./init_fs.py", line 50, in <module>
facenet_1          |     model_type=m['model_type'])
facenet_1          |   File "/usr/local/lib/python2.7/dist-packages/django/db/models/manager.py", line 85, in manager_method
facenet_1          |     return getattr(self.get_queryset(), name)(*args, **kwargs)
facenet_1          |   File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 464, in get_or_create
facenet_1          |     return self.get(**lookup), False
facenet_1          |   File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 384, in get
facenet_1          |     (self.model._meta.object_name, num)
facenet_1          | dvaapp.models.MultipleObjectsReturned: get() returned more than one TrainedModel -- it returned 2!
facenet_1          | Traceback (most recent call last):
facenet_1          |   File "./start_container.py", line 15, in <module>
facenet_1          |     subprocess.check_call(['./init_fs.py',])
facenet_1          |   File "/usr/lib/python2.7/subprocess.py", line 541, in check_call
facenet_1          |     raise CalledProcessError(retcode, cmd)
facenet_1          | subprocess.CalledProcessError: Command '['./init_fs.py']' returned non-zero exit status 1
gpu_facenet_1 exited with code 1
inception_1        | Traceback (most recent call last):
inception_1        |   File "./init_fs.py", line 50, in <module>
inception_1        |     model_type=m['model_type'])
inception_1        |   File "/usr/local/lib/python2.7/dist-packages/django/db/models/manager.py", line 85, in manager_method
inception_1        |     return getattr(self.get_queryset(), name)(*args, **kwargs)
inception_1        |   File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 464, in get_or_create
inception_1        |     return self.get(**lookup), False
inception_1        |   File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 384, in get
inception_1        |     (self.model._meta.object_name, num)
inception_1        | dvaapp.models.MultipleObjectsReturned: get() returned more than one TrainedModel -- it returned 2!
inception_1        | Traceback (most recent call last):
inception_1        |   File "./start_container.py", line 15, in <module>
inception_1        |     subprocess.check_call(['./init_fs.py',])
inception_1        |   File "/usr/lib/python2.7/subprocess.py", line 541, in check_call
inception_1        |     raise CalledProcessError(retcode, cmd)
inception_1        | subprocess.CalledProcessError: Command '['./init_fs.py']' returned non-zero exit status 1
gpu_inception_1 exited with code 1
textbox_1          | Traceback (most recent call last):
textbox_1          |   File "./init_fs.py", line 50, in <module>
textbox_1          |     model_type=m['model_type'])
textbox_1          |   File "/usr/local/lib/python2.7/dist-packages/django/db/models/manager.py", line 85, in manager_method
textbox_1          |     return getattr(self.get_queryset(), name)(*args, **kwargs)
textbox_1          |   File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 464, in get_or_create
textbox_1          |     return self.get(**lookup), False
textbox_1          |   File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 384, in get
textbox_1          |     (self.model._meta.object_name, num)
textbox_1          | dvaapp.models.MultipleObjectsReturned: get() returned more than one TrainedModel -- it returned 2!
textbox_1          | Traceback (most recent call last):
textbox_1          |   File "./start_container.py", line 15, in <module>
textbox_1          |     subprocess.check_call(['./init_fs.py',])
textbox_1          |   File "/usr/lib/python2.7/subprocess.py", line 541, in check_call
textbox_1          |     raise CalledProcessError(retcode, cmd)
textbox_1          | subprocess.CalledProcessError: Command '['./init_fs.py']' returned non-zero exit status 1
gpu_textbox_1 exited with code 1
global-model_1     | WARNING:root:Could not import indexer / clustering assuming running in front-end mode
global-model_1     | WARNING:root:Could not import indexer / clustering assuming running in front-end mode
global-model_1     | Using TensorFlow backend.
global-model_1     | Using TensorFlow backend.
global-model_1     | /usr/local/lib/python2.7/dist-packages/celery/platforms.py:793: RuntimeWarning: You're running the worker with superuser privileges: this is
global-model_1     | absolutely not recommended!
global-model_1     | 
global-model_1     | Please specify a different user using the -u option.
global-model_1     | 
global-model_1     | User information: uid=0 euid=0 gid=0 egid=0
global-model_1     | 
global-model_1     |   uid=uid, euid=euid, gid=gid, egid=egid,
global-model_1     | /usr/local/lib/python2.7/dist-packages/celery/platforms.py:793: RuntimeWarning: You're running the worker with superuser privileges: this is
global-model_1     | absolutely not recommended!
global-model_1     | 
global-model_1     | Please specify a different user using the -u option.
global-model_1     | 
global-model_1     | User information: uid=0 euid=0 gid=0 egid=0
global-model_1     | 
global-model_1     |   uid=uid, euid=euid, gid=gid, egid=egid,
dva-rmq            | 2018-01-02 14:10:39.454 [info] <0.488.0> accepting AMQP connection <0.488.0> (172.20.0.11:48930 -> 172.20.0.2:5672)
dva-rmq            | 2018-01-02 14:10:39.484 [info] <0.488.0> connection <0.488.0> (172.20.0.11:48930 -> 172.20.0.2:5672): user 'dvauser' authenticated and granted access to vhost '/'
dva-rmq            | 2018-01-02 14:10:39.491 [info] <0.498.0> accepting AMQP connection <0.498.0> (172.20.0.11:48932 -> 172.20.0.2:5672)
dva-rmq            | 2018-01-02 14:10:39.492 [info] <0.498.0> connection <0.498.0> (172.20.0.11:48932 -> 172.20.0.2:5672): user 'dvauser' authenticated and granted access to vhost '/'
dva-rmq            | 2018-01-02 14:10:39.502 [info] <0.514.0> accepting AMQP connection <0.514.0> (172.20.0.11:48934 -> 172.20.0.2:5672)
dva-rmq            | 2018-01-02 14:10:39.503 [info] <0.514.0> connection <0.514.0> (172.20.0.11:48934 -> 172.20.0.2:5672): user 'dvauser' authenticated and granted access to vhost '/'
dva-rmq            | 2018-01-02 14:10:39.536 [info] <0.526.0> accepting AMQP connection <0.526.0> (172.20.0.11:48936 -> 172.20.0.2:5672)
dva-rmq            | 2018-01-02 14:10:39.537 [info] <0.526.0> connection <0.526.0> (172.20.0.11:48936 -> 172.20.0.2:5672): user 'dvauser' authenticated and granted access to vhost '/'
dva-rmq            | 2018-01-02 14:10:39.543 [info] <0.534.0> accepting AMQP connection <0.534.0> (172.20.0.11:48938 -> 172.20.0.2:5672)
dva-rmq            | 2018-01-02 14:10:39.544 [info] <0.534.0> connection <0.534.0> (172.20.0.11:48938 -> 172.20.0.2:5672): user 'dvauser' authenticated and granted access to vhost '/'
dva-rmq            | 2018-01-02 14:10:39.552 [info] <0.549.0> accepting AMQP connection <0.549.0> (172.20.0.11:48940 -> 172.20.0.2:5672)
dva-rmq            | 2018-01-02 14:10:39.553 [info] <0.549.0> connection <0.549.0> (172.20.0.11:48940 -> 172.20.0.2:5672): user 'dvauser' authenticated and granted access to vhost '/'
crnn_1             | Traceback (most recent call last):
crnn_1             |   File "./launch_from_env.py", line 27, in <module>
crnn_1             |     dm = TrainedModel.objects.get(name=model_name, model_type=TrainedModel.ANALYZER)
crnn_1             |   File "/usr/local/lib/python2.7/dist-packages/django/db/models/manager.py", line 85, in manager_method
crnn_1             |     return getattr(self.get_queryset(), name)(*args, **kwargs)
crnn_1             |   File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 384, in get
crnn_1             |     (self.model._meta.object_name, num)
crnn_1             | dvaapp.models.MultipleObjectsReturned: get() returned more than one TrainedModel -- it returned 2!
crnn_1             | Traceback (most recent call last):
crnn_1             |   File "./start_container.py", line 25, in <module>
crnn_1             |     subprocess.check_call(['./launch_from_env.py','1'])
crnn_1             |   File "/usr/lib/python2.7/subprocess.py", line 541, in check_call
crnn_1             |     raise CalledProcessError(retcode, cmd)
crnn_1             | subprocess.CalledProcessError: Command '['./launch_from_env.py', '1']' returned non-zero exit status 1
gpu_crnn_1 exited with code 1

**Comment by ericjenott** [comment]
Also, if I run docker-compose-gpu.yml, the "webserver" container exits with the same error message: "dvaapp.models.MultipleObjectsReturned: get() returned more than one TrainedModel -- it returned 2!"

**Comment by AKSHAYUBHAT** [comment]
These errors appear to be happening due to:

1.  Other processes trying to use the database before web server container executes migrations 
2.  Multiple processes, trying to create models/superuser at the same time.
3.  Multiple models with same name being created.

Regarding 1, the only solution I have right now is to make other containers wait for few seconds by adding `sleep 45 &&` before start container. My latest commit fixes these three issues.
