### ISSUE TITLE
lack of file

### ISSUE THREAD

**Issue by doudoubean** [AKSHAYUBHAT/DeepVideoAnalytics#113]
this url "https://github.com/AKSHAYUBHAT/DeepVideoAnalytics/tree/master/configs/custom_defaults" lacks of defaults.py file.

**Comment by AKSHAYUBHAT** [comment]
Instead of using a single defaults.py the configuration are now split into different json file to avoid repetition between Mac (dev) and Linux version. I have updated readme.md with new instructions. 

https://github.com/AKSHAYUBHAT/DeepVideoAnalytics/tree/master/configs/custom_defaults
