### ISSUE TITLE
ImportError: No module named redis

### ISSUE THREAD

**Issue by doudoubean** [AKSHAYUBHAT/DeepVideoAnalytics#116]
hi, When I run the latest dva project, it appears an error. The details are listed below:
*******************************************************************************************************

root@ai100:/home/yangzhanku/deeplearning/DeepVideoAnalytics/deploy/gpu# nvidia-docker-compose -f docker-compose-gpu.yml up
Starting dva-redis ... 
Starting dva-rmq ... 
Starting dva-redis
Starting dva-pg ... 
Starting dva-rmq
Starting dva-rmq ... done
Starting webserver ... 
Starting webserver ... done
Attaching to dva-redis, dva-pg, dva-rmq, webserver
dva-pg    | LOG:  database system was shut down at 2018-01-09 01:35:59 UTC
dva-pg    | LOG:  MultiXact member wraparound protections are now enabled
dva-pg    | LOG:  autovacuum launcher started
dva-pg    | LOG:  database system is ready to accept connections
dva-redis | 
dva-redis | Welcome to the Bitnami redis container
dva-redis | Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-redis
dva-redis | Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-redis/issues
dva-redis | Send us your feedback at containers@bitnami.com
dva-redis | 
dva-redis | INFO  ==> Starting redis... 
dva-redis | 21:C 09 Jan 01:37:07.029 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
dva-redis | 21:C 09 Jan 01:37:07.029 # Redis version=4.0.6, bits=64, commit=00000000, modified=0, pid=21, just started
dva-redis | 21:C 09 Jan 01:37:07.029 # Configuration loaded
dva-redis |                 _._                                                  
dva-redis |            _.-``__ ''-._                                             
dva-redis |       _.-``    `.  `_.  ''-._           Redis 4.0.6 (00000000/0) 64 bit
dva-redis |   .-`` .-```.  ```\/    _.,_ ''-._                                   
dva-redis |  (    '      ,       .-`  | `,    )     Running in standalone mode
dva-redis |  |`-._`-...-` __...-.``-._|'` _.-'|     Port: 6379
dva-redis |  |    `-._   `._    /     _.-'    |     PID: 21
dva-redis |   `-._    `-._  `-./  _.-'    _.-'                                   
dva-redis |  |`-._`-._    `-.__.-'    _.-'_.-'|                                  
dva-redis |  |    `-._`-._        _.-'_.-'    |           http://redis.io        
dva-redis |   `-._    `-._`-.__.-'_.-'    _.-'                                   
dva-redis |  |`-._`-._    `-.__.-'    _.-'_.-'|                                  
dva-redis |  |    `-._`-._        _.-'_.-'    |                                  
dva-redis |   `-._    `-._`-.__.-'_.-'    _.-'                                   
dva-redis |       `-._    `-.__.-'    _.-'                                       
dva-redis |           `-._        _.-'                                           
dva-redis |               `-.__.-'                                               
dva-redis | 
dva-redis | 21:M 09 Jan 01:37:07.031 # WARNING: The TCP backlog setting of 511 cannot be enforced because /proc/sys/net/core/somaxconn is set to the lower value of 128.
dva-redis | 21:M 09 Jan 01:37:07.031 # Server initialized
dva-redis | 21:M 09 Jan 01:37:07.031 # WARNING overcommit_memory is set to 0! Background save may fail under low memory condition. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.
dva-redis | 21:M 09 Jan 01:37:07.031 # WARNING you have Transparent Huge Pages (THP) support enabled in your kernel. This will create latency and memory usage issues with Redis. To fix this issue run the command 'echo never > /sys/kernel/mm/transparent_hugepage/enabled' as root, and add it to your /etc/rc.local in order to retain the setting after a reboot. Redis must be restarted after THP is disabled.
dva-redis | 21:M 09 Jan 01:37:07.031 * Ready to accept connections
dva-rmq   | 
dva-rmq   | =INFO REPORT==== 9-Jan-2018::01:37:08 ===
dva-rmq   | Starting RabbitMQ 3.6.10 on Erlang 19.2.1
dva-rmq   | Copyright (C) 2007-2017 Pivotal Software, Inc.
dva-rmq   | Licensed under the MPL.  See http://www.rabbitmq.com/
dva-rmq   | 
dva-rmq   |               RabbitMQ 3.6.10. Copyright (C) 2007-2017 Pivotal Software, Inc.
dva-rmq   |   ##  ##      Licensed under the MPL.  See http://www.rabbitmq.com/
dva-rmq   |   ##  ##
dva-rmq   |   ##########  Logs: tty
dva-rmq   |   ######  ##        tty
dva-rmq   |   ##########
dva-rmq   |               Starting broker...
dva-rmq   | 
dva-rmq   | =INFO REPORT==== 9-Jan-2018::01:37:08 ===
dva-rmq   | node           : rabbit@4e6df6b35217
dva-rmq   | home dir       : /var/lib/rabbitmq
dva-rmq   | config file(s) : /etc/rabbitmq/rabbitmq.config
dva-rmq   | cookie hash    : Uz7pYo/Ni1uLDJ+hWLe/4A==
dva-rmq   | log            : tty
dva-rmq   | sasl log       : tty
dva-rmq   | database dir   : /var/lib/rabbitmq/mnesia/rabbit@4e6df6b35217
dva-rmq   | 
dva-rmq   | =INFO REPORT==== 9-Jan-2018::01:37:09 ===
dva-rmq   | Memory limit set to 25737MB of 64343MB total.
dva-rmq   | 
dva-rmq   | =INFO REPORT==== 9-Jan-2018::01:37:09 ===
dva-rmq   | Enabling free disk space monitoring
dva-rmq   | 
dva-rmq   | =INFO REPORT==== 9-Jan-2018::01:37:09 ===
dva-rmq   | Disk free limit set to 50MB
dva-rmq   | 
dva-rmq   | =INFO REPORT==== 9-Jan-2018::01:37:09 ===
dva-rmq   | Limiting to approx 524188 file handles (471767 sockets)
dva-rmq   | 
dva-rmq   | =INFO REPORT==== 9-Jan-2018::01:37:09 ===
dva-rmq   | FHC read buffering:  OFF
dva-rmq   | FHC write buffering: ON
dva-rmq   | 
dva-rmq   | =INFO REPORT==== 9-Jan-2018::01:37:09 ===
dva-rmq   | Waiting for Mnesia tables for 30000 ms, 9 retries left
webserver | Already up-to-date.
dva-rmq   | 
dva-rmq   | =INFO REPORT==== 9-Jan-2018::01:37:09 ===
dva-rmq   | Waiting for Mnesia tables for 30000 ms, 9 retries left
dva-rmq   | 
dva-rmq   | =INFO REPORT==== 9-Jan-2018::01:37:09 ===
dva-rmq   | Priority queues enabled, real BQ is rabbit_variable_queue
dva-rmq   | 
dva-rmq   | =INFO REPORT==== 9-Jan-2018::01:37:09 ===
dva-rmq   | Starting rabbit_node_monitor
dva-rmq   | 
dva-rmq   | =INFO REPORT==== 9-Jan-2018::01:37:09 ===
dva-rmq   | msg_store_transient: using rabbit_msg_store_ets_index to provide index
dva-rmq   | 
dva-rmq   | =INFO REPORT==== 9-Jan-2018::01:37:09 ===
dva-rmq   | msg_store_persistent: using rabbit_msg_store_ets_index to provide index
dva-rmq   | 
dva-rmq   | =INFO REPORT==== 9-Jan-2018::01:37:09 ===
dva-rmq   | started TCP Listener on [::]:5672
dva-rmq   |  completed with 0 plugins.
dva-rmq   | 
dva-rmq   | =INFO REPORT==== 9-Jan-2018::01:37:09 ===
dva-rmq   | Server startup complete; 0 plugins started.
webserver | Traceback (most recent call last):
webserver |   File "manage.py", line 22, in <module>
webserver |     execute_from_command_line(sys.argv)
webserver |   File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 363, in execute_from_command_line
webserver |     utility.execute()
webserver |   File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 337, in execute
webserver |     django.setup()
webserver |   File "/usr/local/lib/python2.7/dist-packages/django/__init__.py", line 27, in setup
webserver |     apps.populate(settings.INSTALLED_APPS)
webserver |   File "/usr/local/lib/python2.7/dist-packages/django/apps/registry.py", line 108, in populate
webserver |     app_config.import_models()
webserver |   File "/usr/local/lib/python2.7/dist-packages/django/apps/config.py", line 202, in import_models
webserver |     self.models_module = import_module(models_module_name)
webserver |   File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
webserver |     __import__(name)
webserver |   File "/root/DVA/server/dvaapp/models.py", line 8, in <module>
webserver |     from . import fs
webserver |   File "/root/DVA/server/dvaapp/fs.py", line 9, in <module>
webserver |     from dva.in_memory import redis_client
webserver |   File "/root/DVA/server/dva/in_memory.py", line 2, in <module>
webserver |     import redis
webserver | ImportError: No module named redis
webserver | Traceback (most recent call last):
webserver |   File "manage.py", line 22, in <module>
webserver |     execute_from_command_line(sys.argv)
webserver |   File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 363, in execute_from_command_line
webserver |     utility.execute()
webserver |   File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 337, in execute
webserver |     django.setup()
webserver |   File "/usr/local/lib/python2.7/dist-packages/django/__init__.py", line 27, in setup
webserver |     apps.populate(settings.INSTALLED_APPS)
webserver |   File "/usr/local/lib/python2.7/dist-packages/django/apps/registry.py", line 108, in populate
webserver |     app_config.import_models()
webserver |   File "/usr/local/lib/python2.7/dist-packages/django/apps/config.py", line 202, in import_models
webserver |     self.models_module = import_module(models_module_name)
webserver |   File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
webserver |     __import__(name)
webserver |   File "/root/DVA/server/dvaapp/models.py", line 8, in <module>
webserver |     from . import fs
webserver |   File "/root/DVA/server/dvaapp/fs.py", line 9, in <module>
webserver |     from dva.in_memory import redis_client
webserver |   File "/root/DVA/server/dva/in_memory.py", line 2, in <module>
webserver |     import redis
webserver | ImportError: No module named redis
webserver | Traceback (most recent call last):
webserver |   File "./start_container.py", line 14, in <module>
webserver |     subprocess.check_call(['./migrate.sh',])
webserver |   File "/usr/lib/python2.7/subprocess.py", line 541, in check_call
webserver |     raise CalledProcessError(retcode, cmd)
webserver | subprocess.CalledProcessError: Command '['./migrate.sh']' returned non-zero exit status 1
webserver exited with code 1

***********************************************************************************************************
Could you help me? Thank you very much!

**Comment by AKSHAYUBHAT** [comment]
Please pull latest container image from docker hub by running .
`docker pull akshayubhat/dva-auto:latest
