### ISSUE TITLE
Can not access webui after run start_tutorial.py

### ISSUE THREAD

**Issue by jetta** [AKSHAYUBHAT/DeepVideoAnalytics#117]
I run the script follow these steps:
>git clone https://github.com/AKSHAYUBHAT/DeepVideoAnalytics
cd DeepVideoAnalytics/docs/tutorial && python start_tutorial.py

But i can not access webui through `127.0.0.1:8888` or `127.0.0.1:80`

# the output logs is:
>Checking if docker-compose is available
Name   Command   State   Ports  
\------------------------------
Pulling/Refreshing container images, first time it might take a while to download the image
latest: Pulling from akshayubhat/dva-auto
Digest: sha256:99d1177901bc9e61b35bea594282f0b1eed8ee52e529ee60d9e3c92d981c83f3
Status: Image is up to date for akshayubhat/dva-auto:latest
Trying to launch containers
Waiting for 20 minutes, while checking if DVA is running
Creating network "cpu_default" with the default driver
Creating volume "cpu_dvadata" with default driver
Creating volume "cpu_dvapgdata" with default driver
Creating volume "cpu_dvaredis" with default driver
Creating dva-redis ... done
Creating webserver ... done
Creating dva-redis ...
Creating dva-pg ...
Creating webserver ...
Waiting for 19 minutes, while checking if DVA is running

# check list
- OS and docker version
> mac os: 10.13.2
docker: 17.12.0-ce

- docker images
>REPOSITORY             TAG                 IMAGE ID            CREATED             SIZE
akshayubhat/dva-auto   latest              b99b612a45d8        7 days ago          3.63GB
rabbitmq               latest              d53246bdedd1        2 weeks ago         127MB
bitnami/redis          latest              d0b997c315ff        3 weeks ago         113MB
postgres               9.6.6               5579c7505b1b        4 weeks ago         268MB

- docker ps -a (the container webserver is running)
>CONTAINER ID        IMAGE                         COMMAND                  CREATED              STATUS              PORTS                                                        NAMES
c971c80f64a5        akshayubhat/dva-auto:latest   "bash -c 'git pull &…"   About a minute ago   Up About a minute   6006/tcp, 127.0.0.1:8888->8888/tcp, 127.0.0.1:8000->80/tcp   webserver
9cc7a1d87115        postgres:9.6.6                "docker-entrypoint.s…"   About a minute ago   Up About a minute   5432/tcp                                                     dva-pg
b2f6ee6fb22b        bitnami/redis:latest          "/app-entrypoint.sh …"   About a minute ago   Up About a minute   6379/tcp                                                     dva-redis
af5833ed4320        rabbitmq                      "docker-entrypoint.s…"   About a minute ago   Up About a minute   4369/tcp, 5671-5672/tcp, 25672/tcp                           dva-rmq

- docker logs webserver
From https://github.com/akshayubhat/DeepVideoAnalytics
   056a75a..ce807cc  master     -> origin/master
Updating 056a75a..ce807cc
Fast-forward
 .travis.yml                                        |   2 +-
 client/dvaclient/context.py                        |  11 +-
 client/dvaclient/query.py                          | 178 ++--
 client/dvaclient/visual_search_results.py          |  11 +-
 deploy/common.env                                  |   3 +-
 deploy/cpu/docker-compose.yml                      |   1 +
 deploy/gpu/docker-compose-2-gpus.yml               |   1 +
 ...ompose-3-gpus.yml => docker-compose-4-gpus.yml} |  43 +-
 deploy/gpu/docker-compose-gpu.yml                  |   1 +
 deploy/gpu/gcp/gcp_tunnel.sh                       |   2 +-
 deploy/gpu/generate_multi_gpu.py                   |  18 +-
 deploy/kube/config_example.py                      |   2 +
 deploy/kube/create_secrets.py                      |   2 +
 deploy/kube/delete.sh                              |   2 +
 deploy/kube/deployments/coco.yaml                  |  10 +
 deploy/kube/deployments/crnn.yaml                  |  10 +
 deploy/kube/deployments/extractor.yaml             |  10 +
 deploy/kube/deployments/face.yaml                  |  10 +
 deploy/kube/deployments/facenet.yaml               |  10 +
 deploy/kube/deployments/facenet_retriever.yaml     |  10 +
 deploy/kube/deployments/global_retriever.yaml      |  10 +
 deploy/kube/deployments/inception.yaml             |  10 +
 deploy/kube/deployments/inception_retriever.yaml   |  10 +
 deploy/kube/deployments/redis.yaml                 |  13 +-
 deploy/kube/deployments/scheduler.yaml             |  10 +
 deploy/kube/deployments/tagger.yaml                |  10 +
 deploy/kube/deployments/textbox.yaml               |  10 +
 deploy/kube/deployments/webserver.yaml             |  10 +
 deploy/kube/launch.sh                              |   6 +-
 deploy/kube/secrets_template.yml                   |   9 +
 .../1_filesystem_and_database.ipynb                |   0
 .../2_execution_processes_and_tasks.ipynb          |   0
 .../3_DVAPQL_explained.ipynb                       |   0
 .../4_processing_a_video_a_walkthrough.ipynb       |   0
 .../6_processing_dataset_of_images.ipynb           |   0
 ...7_retrievers_and_performing_visual_search.ipynb |   0
 ...ks_on_arbitary_subsets_of_videos_datasets.ipynb |   0
 ...oring_management_testing_and_benchmarking.ipynb |   0
 docs/readme.md                                     |   2 +-
 docs/tutorial/0_quick_intro.ipynb                  | 904 ---------------------
 docs/tutorial/query_leo.jpg                        | Bin 13163 -> 0 bytes
 docs/tutorial/quick_demo.ipynb                     | 311 +++++++
 docs/tutorial/readme.md                            |   9 +-
 docs/tutorial/start_tutorial.py                    |  39 +
 docs/tutorial/stop_and_delete_volumes.py           |  10 +
 docs/tutorial/stop_tutorial.py                     |  10 +
 server/dva/in_memory.py                            |   4 +
 server/dva/settings.py                             |   3 +
 server/dvaapp/fs.py                                |  46 +-
 .../dvaapp/migrations/0001_auto_20170825_1749.py   |  36 -
 server/dvaapp/migrations/0001_initial.py           | 388 +++++----
 server/dvaapp/migrations/0001_trainedmodel_uuid.py |  21 +
 server/dvaapp/migrations/0002_detector_queue.py    |  20 -
 .../dvaapp/migrations/0003_auto_20170826_0041.py   |  31 -
 .../dvaapp/migrations/0004_auto_20170826_0641.py   |  43 -
 .../dvaapp/migrations/0005_auto_20170826_1539.py   |  26 -
 .../dvaapp/migrations/0006_auto_20170826_1617.py   |  20 -
 .../dvaapp/migrations/0007_auto_20170826_1644.py   |  20 -
 .../dvaapp/migrations/0008_auto_20170826_1644.py   |  20 -
 .../dvaapp/migrations/0009_auto_20170826_1918.py   |  41 -
 .../dvaapp/migrations/0010_auto_20170827_1626.py   |  26 -
 .../dvaapp/migrations/0011_auto_20170828_2143.py   |  20 -
 .../dvaapp/migrations/0012_auto_20170829_0528.py   |  34 -
 .../migrations/0013_indexentries_indexer_shasum.py |  21 -
 .../dvaapp/migrations/0014_auto_20170829_0635.py   |  33 -
 server/dvaapp/migrations/0015_retriever_name.py    |  20 -
 .../dvaapp/migrations/0016_auto_20170829_0959.py   |  26 -
 .../dvaapp/migrations/0017_auto_20170829_1016.py   |  28 -
 .../dvaapp/migrations/0018_auto_20170831_2141.py   |  33 -
 .../dvaapp/migrations/0019_auto_20170831_2238.py   |  25 -
 .../dvaapp/migrations/0020_retriever_last_built.py |  20 -
 .../dvaapp/migrations/0021_remove_video_query.py   |  19 -
 .../dvaapp/migrations/0022_auto_20170901_2329.py   |  53 --
 .../dvaapp/migrations/0023_auto_20170902_0516.py   |  67 --
 server/dvaapp/migrations/0024_systemstate.py       |  28 -
 .../dvaapp/migrations/0025_auto_20170903_0141.py   |  31 -
 server/dvaapp/migrations/0026_worker.py            |  24 -
 server/dvaapp/migrations/0027_worker_queue_name.py |  20 -
 .../dvaapp/migrations/0028_auto_20170905_1842.py   |  25 -
 server/dvaapp/migrations/0029_queryregion.py       |  38 -
 .../migrations/0030_queryregionindexvector.py      |  26 -
 .../dvaapp/migrations/0031_auto_20170913_1927.py   |  21 -
 .../dvaapp/migrations/0032_queryregionresults.py   |  31 -
 .../dvaapp/migrations/0033_auto_20170920_0340.py   |  41 -
 .../dvaapp/migrations/0034_auto_20171004_0351.py   |  67 --
 .../dvaapp/migrations/0035_auto_20171004_0403.py   |  20 -
 server/dvaapp/migrations/0036_deepmodel_parent.py  |  21 -
 .../dvaapp/migrations/0037_auto_20171022_0619.py   |  26 -
 .../dvaapp/migrations/0038_auto_20171022_0642.py   |  20 -
 server/dvaapp/migrations/0039_worker_alive.py      |  20 -
 server/dvaapp/migrations/0040_tevent_worker.py     |  21 -
 .../migrations/0041_managementaction_ping_index.py |  20 -
 server/dvaapp/migrations/0042_delete_vdnserver.py  |  18 -
 .../dvaapp/migrations/0043_auto_20171215_1206.py   |  22 -
 .../dvaapp/migrations/0044_auto_20171222_0539.py   |  20 -
 .../dvaapp/migrations/0045_auto_20171222_0650.py   |  42 -
 server/dvaapp/migrations/0046_trainingset.py       |  28 -
 server/dvaapp/migrations/0047_workerrequest.py     |  23 -
 .../dvaapp/migrations/0048_auto_20171224_2250.py   |  19 -
 server/dvaapp/migrations/0049_trainingset_built.py |  20 -
 .../dvaapp/migrations/0050_delete_workerrequest.py |  18 -
 .../dvaapp/migrations/0051_auto_20171229_1000.py   |  61 --
 .../dvaapp/migrations/0052_auto_20171230_0152.py   |  20 -
 .../0053_retriever_approximator_shashum.py         |  21 -
 .../dvaapp/migrations/0054_auto_20171230_0407.py   |  30 -
 .../dvaapp/migrations/0055_auto_20171230_0534.py   |  25 -
 .../dvaapp/migrations/0056_auto_20171230_1206.py   |  19 -
 .../dvaapp/migrations/0057_tevent_task_group_id.py |  20 -
 .../dvaapp/migrations/0058_auto_20171231_2311.py   |  20 -
 .../dvaapp/migrations/0059_auto_20180101_1037.py   |  23 -
 .../dvaapp/migrations/0060_auto_20180101_2228.py   |  20 -
 .../dvaapp/migrations/0061_auto_20180101_2245.py   |  20 -
 server/dvaapp/models.py                            |  46 +-
 server/dvaapp/operations/analysis.py               |   4 +-
 server/dvaapp/operations/approximation.py          |   2 +-
 server/dvaapp/operations/indexing.py               |   6 +-
 server/dvaapp/processing.py                        |  24 +-
 server/dvaapp/serializers.py                       |   9 +-
 server/dvaapp/task_handlers.py                     |   6 +-
 server/dvaapp/task_shared.py                       |  30 +-
 server/dvaapp/tasks.py                             |   4 +-
 server/dvaapp/views.py                             |   1 +
 server/dvaui/urls.py                               |   8 +-
 server/dvaui/views.py                              |   8 +-
 server/launch_from_env.py                          |   4 +-
 server/templates/dvaui/query_list.html             |   2 +-
 126 files changed, 1033 insertions(+), 2974 deletions(-)
 rename deploy/gpu/{docker-compose-3-gpus.yml => docker-compose-4-gpus.yml} (94%)
 rename docs/{tutorial => documentation}/1_filesystem_and_database.ipynb (100%)
 rename docs/{tutorial => documentation}/2_execution_processes_and_tasks.ipynb (100%)
 rename docs/{tutorial => documentation}/3_DVAPQL_explained.ipynb (100%)
 rename docs/{tutorial => documentation}/4_processing_a_video_a_walkthrough.ipynb (100%)
 rename docs/{tutorial => documentation}/6_processing_dataset_of_images.ipynb (100%)
 rename docs/{tutorial => documentation}/7_retrievers_and_performing_visual_search.ipynb (100%)
 rename docs/{tutorial => documentation}/8_map_tasks_on_arbitary_subsets_of_videos_datasets.ipynb (100%)
 rename docs/{tutorial => documentation}/9_monitoring_management_testing_and_benchmarking.ipynb (100%)
 delete mode 100644 docs/tutorial/0_quick_intro.ipynb
 delete mode 100755 docs/tutorial/query_leo.jpg
 create mode 100644 docs/tutorial/quick_demo.ipynb
 create mode 100755 docs/tutorial/start_tutorial.py
 create mode 100755 docs/tutorial/stop_and_delete_volumes.py
 create mode 100755 docs/tutorial/stop_tutorial.py
 create mode 100644 server/dva/in_memory.py
 delete mode 100644 server/dvaapp/migrations/0001_auto_20170825_1749.py
 create mode 100644 server/dvaapp/migrations/0001_trainedmodel_uuid.py
 delete mode 100644 server/dvaapp/migrations/0002_detector_queue.py
 delete mode 100644 server/dvaapp/migrations/0003_auto_20170826_0041.py
 delete mode 100644 server/dvaapp/migrations/0004_auto_20170826_0641.py
 delete mode 100644 server/dvaapp/migrations/0005_auto_20170826_1539.py
 delete mode 100644 server/dvaapp/migrations/0006_auto_20170826_1617.py
 delete mode 100644 server/dvaapp/migrations/0007_auto_20170826_1644.py
 delete mode 100644 server/dvaapp/migrations/0008_auto_20170826_1644.py
 delete mode 100644 server/dvaapp/migrations/0009_auto_20170826_1918.py
 delete mode 100644 server/dvaapp/migrations/0010_auto_20170827_1626.py
 delete mode 100644 server/dvaapp/migrations/0011_auto_20170828_2143.py
 delete mode 100644 server/dvaapp/migrations/0012_auto_20170829_0528.py
 delete mode 100644 server/dvaapp/migrations/0013_indexentries_indexer_shasum.py
 delete mode 100644 server/dvaapp/migrations/0014_auto_20170829_0635.py
 delete mode 100644 server/dvaapp/migrations/0015_retriever_name.py
 delete mode 100644 server/dvaapp/migrations/0016_auto_20170829_0959.py
 delete mode 100644 server/dvaapp/migrations/0017_auto_20170829_1016.py
 delete mode 100644 server/dvaapp/migrations/0018_auto_20170831_2141.py
 delete mode 100644 server/dvaapp/migrations/0019_auto_20170831_2238.py
 delete mode 100644 server/dvaapp/migrations/0020_retriever_last_built.py
 delete mode 100644 server/dvaapp/migrations/0021_remove_video_query.py
 delete mode 100644 server/dvaapp/migrations/0022_auto_20170901_2329.py
 delete mode 100644 server/dvaapp/migrations/0023_auto_20170902_0516.py
 delete mode 100644 server/dvaapp/migrations/0024_systemstate.py
 delete mode 100644 server/dvaapp/migrations/0025_auto_20170903_0141.py
 delete mode 100644 server/dvaapp/migrations/0026_worker.py
 delete mode 100644 server/dvaapp/migrations/0027_worker_queue_name.py
 delete mode 100644 server/dvaapp/migrations/0028_auto_20170905_1842.py
 delete mode 100644 server/dvaapp/migrations/0029_queryregion.py
 delete mode 100644 server/dvaapp/migrations/0030_queryregionindexvector.py
 delete mode 100644 server/dvaapp/migrations/0031_auto_20170913_1927.py
 delete mode 100644 server/dvaapp/migrations/0032_queryregionresults.py
 delete mode 100644 server/dvaapp/migrations/0033_auto_20170920_0340.py
 delete mode 100644 server/dvaapp/migrations/0034_auto_20171004_0351.py
 delete mode 100644 server/dvaapp/migrations/0035_auto_20171004_0403.py
 delete mode 100644 server/dvaapp/migrations/0036_deepmodel_parent.py
 delete mode 100644 server/dvaapp/migrations/0037_auto_20171022_0619.py
 delete mode 100644 server/dvaapp/migrations/0038_auto_20171022_0642.py
 delete mode 100644 server/dvaapp/migrations/0039_worker_alive.py
 delete mode 100644 server/dvaapp/migrations/0040_tevent_worker.py
 delete mode 100644 server/dvaapp/migrations/0041_managementaction_ping_index.py
 delete mode 100644 server/dvaapp/migrations/0042_delete_vdnserver.py
 delete mode 100644 server/dvaapp/migrations/0043_auto_20171215_1206.py
 delete mode 100644 server/dvaapp/migrations/0044_auto_20171222_0539.py
 delete mode 100644 server/dvaapp/migrations/0045_auto_20171222_0650.py
 delete mode 100644 server/dvaapp/migrations/0046_trainingset.py
 delete mode 100644 server/dvaapp/migrations/0047_workerrequest.py
 delete mode 100644 server/dvaapp/migrations/0048_auto_20171224_2250.py
 delete mode 100644 server/dvaapp/migrations/0049_trainingset_built.py
 delete mode 100644 server/dvaapp/migrations/0050_delete_workerrequest.py
 delete mode 100644 server/dvaapp/migrations/0051_auto_20171229_1000.py
 delete mode 100644 server/dvaapp/migrations/0052_auto_20171230_0152.py
 delete mode 100644 server/dvaapp/migrations/0053_retriever_approximator_shashum.py
 delete mode 100644 server/dvaapp/migrations/0054_auto_20171230_0407.py
 delete mode 100644 server/dvaapp/migrations/0055_auto_20171230_0534.py
 delete mode 100644 server/dvaapp/migrations/0056_auto_20171230_1206.py
 delete mode 100644 server/dvaapp/migrations/0057_tevent_task_group_id.py
 delete mode 100644 server/dvaapp/migrations/0058_auto_20171231_2311.py
 delete mode 100644 server/dvaapp/migrations/0059_auto_20180101_1037.py
 delete mode 100644 server/dvaapp/migrations/0060_auto_20180101_2228.py
 delete mode 100644 server/dvaapp/migrations/0061_auto_20180101_2245.py
WARNING:root:Could not import indexer / clustering assuming running in front-end mode
System check identified some issues:

WARNINGS:
?: (rest_framework.W001) You have specified a default PAGE_SIZE pagination rest_framework setting,without specifying also a DEFAULT_PAGINATION_CLASS.
	HINT: The default for DEFAULT_PAGINATION_CLASS is None. In previous versions this was PageNumberPagination. If you wish to define PAGE_SIZE globally whilst defining pagination_class on a per-view basis you may silence this check.
No changes detected
WARNING:root:Could not import indexer / clustering assuming running in front-end mode
System check identified some issues:

WARNINGS:
?: (rest_framework.W001) You have specified a default PAGE_SIZE pagination rest_framework setting,without specifying also a DEFAULT_PAGINATION_CLASS.
	HINT: The default for DEFAULT_PAGINATION_CLASS is None. In previous versions this was PageNumberPagination. If you wish to define PAGE_SIZE globally whilst defining pagination_class on a per-view basis you may silence this check.
Operations to perform:
  Apply all migrations: admin, auth, authtoken, contenttypes, django_celery_beat, django_celery_results, dvaapp, dvaui, sessions
Running migrations:
  Applying contenttypes.0001_initial... OK
  Applying auth.0001_initial... OK
  Applying admin.0001_initial... OK
  Applying admin.0002_logentry_remove_auto_add... OK
  Applying contenttypes.0002_remove_content_type_name... OK
  Applying auth.0002_alter_permission_name_max_length... OK
  Applying auth.0003_alter_user_email_max_length... OK
  Applying auth.0004_alter_user_username_opts... OK
  Applying auth.0005_alter_user_last_login_null... OK
  Applying auth.0006_require_contenttypes_0002... OK
  Applying auth.0007_alter_validators_add_error_messages... OK
  Applying auth.0008_alter_user_username_max_length... OK
  Applying authtoken.0001_initial... OK
  Applying authtoken.0002_auto_20160226_1747... OK
  Applying django_celery_beat.0001_initial... OK
  Applying django_celery_beat.0002_auto_20161118_0346... OK
  Applying django_celery_beat.0003_auto_20161209_0049... OK
  Applying django_celery_beat.0004_auto_20170221_0000... OK
  Applying django_celery_results.0001_initial... OK
  Applying dvaapp.0001_initial... OK
  Applying dvaapp.custom_migration... OK
  Applying dvaapp.0001_trainedmodel_uuid... OK
  Applying dvaui.0001_initial... OK
  Applying dvaui.0002_auto_20171216_0733... OK
  Applying dvaui.0003_storeddvapql_server... OK
  Applying sessions.0001_initial... OK

**Comment by AKSHAYUBHAT** [comment]
Try `127.0.0.1:8000`  not 80

**Comment by jetta** [comment]
`127.0.0.1:8000` doesn't work

**Comment by AKSHAYUBHAT** [comment]
```
Creating webserver ...
Waiting for 19 minutes, while checking if DVA is running
```

```
Applying dvaui.0002_auto_20171216_0733... OK
Applying dvaui.0003_storeddvapql_server... OK
Applying sessions.0001_initial... OK
```

This indicates that the server has not launched, you need to wait few more minutes before process of downloading models has finished. Can you check again?

**Comment by jetta** [comment]
It seems that nothing changed.

>Checking if docker-compose is available
Name   Command   State   Ports
------------------------------
Pulling/Refreshing container images, first time it might take a while to download the image
latest: Pulling from akshayubhat/dva-auto
Digest: sha256:99d1177901bc9e61b35bea594282f0b1eed8ee52e529ee60d9e3c92d981c83f3
Status: Image is up to date for akshayubhat/dva-auto:latest
Trying to launch containers
Waiting for 20 minutes, while checking if DVA is running
Creating network "cpu_default" with the default driver
Creating volume "cpu_dvadata" with default driver
Creating volume "cpu_dvapgdata" with default driver
Creating volume "cpu_dvaredis" with default driver
Creating dva-pg ... done
Creating webserver ... done
Creating dva-redis ...
Creating dva-pg ...
Creating webserver ...
Waiting for 19 minutes, while checking if DVA is running
Waiting for 18 minutes, while checking if DVA is running
Waiting for 17 minutes, while checking if DVA is running
Waiting for 16 minutes, while checking if DVA is running
Waiting for 15 minutes, while checking if DVA is running
Waiting for 14 minutes, while checking if DVA is running
Waiting for 13 minutes, while checking if DVA is running
Waiting for 12 minutes, while checking if DVA is running
Waiting for 11 minutes, while checking if DVA is running
Waiting for 10 minutes, while checking if DVA is running
Waiting for 9 minutes, while checking if DVA is running
Waiting for 8 minutes, while checking if DVA is running
Waiting for 7 minutes, while checking if DVA is running
Waiting for 6 minutes, while checking if DVA is running
Waiting for 5 minutes, while checking if DVA is running
Waiting for 4 minutes, while checking if DVA is running
Waiting for 3 minutes, while checking if DVA is running
Waiting for 2 minutes, while checking if DVA is running
Waiting for 1 minutes, while checking if DVA is running

docker logs webserver:
>Running migrations:
  Applying contenttypes.0001_initial... OK
  Applying auth.0001_initial... OK
  Applying admin.0001_initial... OK
  Applying admin.0002_logentry_remove_auto_add... OK
  Applying contenttypes.0002_remove_content_type_name... OK
  Applying auth.0002_alter_permission_name_max_length... OK
  Applying auth.0003_alter_user_email_max_length... OK
  Applying auth.0004_alter_user_username_opts... OK
  Applying auth.0005_alter_user_last_login_null... OK
  Applying auth.0006_require_contenttypes_0002... OK
  Applying auth.0007_alter_validators_add_error_messages... OK
  Applying auth.0008_alter_user_username_max_length... OK
  Applying authtoken.0001_initial... OK
  Applying authtoken.0002_auto_20160226_1747... OK
  Applying django_celery_beat.0001_initial... OK
  Applying django_celery_beat.0002_auto_20161118_0346... OK
  Applying django_celery_beat.0003_auto_20161209_0049... OK
  Applying django_celery_beat.0004_auto_20170221_0000... OK
  Applying django_celery_results.0001_initial... OK
  Applying dvaapp.0001_initial... OK
  Applying dvaapp.custom_migration... OK
  Applying dvaapp.0001_trainedmodel_uuid... OK
  Applying dvaui.0001_initial... OK
  Applying dvaui.0002_auto_20171216_0733... OK
  Applying dvaui.0003_storeddvapql_server... OK
  Applying sessions.0001_initial... OK

**Comment by AKSHAYUBHAT** [comment]
Thats weird, can you post output of

`docker exec -it webserver ls /root/media/models`

`docker exec -u="root" -it webserver bash -c 'cat /var/log/supervisor/app-*'`

and 

`docker exec -it webserver cat ../logs/startq.log`

Are you in a region with Dropbox blocked, since that's used to distribute model weights.

**Comment by jetta** [comment]
I'm in the region with Dropbox bolocked, and use VPN to download these models.
It seems that the download of these models is time consuming?

### docker exec -it webserver ls /root/media/models
> 01a103a3-1c8a-498e-a45e-466bcdb28c56  b2bb3256-9d4c-4984-98c8-09b9bdd2fdbd
1805b5a6-6111-4d15-aa27-56efc3456a68  c01f4272-fe70-4180-9cae-da55e62bbd80
62689cdb-92e0-4ebd-8d6a-a755fa56b05b  e9b1dc0d-3197-443d-8b4c-d439936e3198
773976a8-ab0e-4124-ac21-2b65d6de3407  f571c260-29b7-4b04-87be-c7f92ec55328
99990610-779c-42ee-bf40-c2460cbc39f3

**Comment by AKSHAYUBHAT** [comment]
It appears that the models are being downloaded but very slowly, I assume due to VPN being throttled. After the models  have been downloaded you can copy them to host os by running

`docker cp webserver:/root/media/models  .`  

For future runs you can use custom_defaults and host those models on a local file server etc. 
You can seen an example of this being done here 

https://github.com/tongpi/DeepVideoAnalytics/blob/master/configs/custom_defaults/trained_models.json
