### ISSUE TITLE
 I can't find the ocr notebooks in the new update in jupyter

### ISSUE THREAD

**Issue by JoshuaMolina** [AKSHAYUBHAT/DeepVideoAnalytics#121]
Hello,

I can't find the folder to run the _**detect_text.ipynb**_ and _**recognize_text.ipynb**_ files in jupyter with the new update.

I'm going to put the steps I do:
First of all I execute this command in the cmd: _**docker run -p 8888: 8888 -it akshayubhat/dva-auto: latest**_, and it starts downloading the repository as seen in the following image:
![descarga](https://user-images.githubusercontent.com/14922989/35197126-8b83f2c6-fedb-11e7-99e8-71b58313162d.jpg)

Once the download is finished, the url tells me to connect to jupyter notebook through the browser, as shown in the following image:
![notebook](https://user-images.githubusercontent.com/14922989/35197129-9a3b7faa-fedb-11e7-900a-70ee89dd45ea.png)

Finally we arrived at the url indicated and it is here where I can not find the two files discussed above to be able to execute them.
![jupyter](https://user-images.githubusercontent.com/14922989/35197237-e64f033e-fedc-11e7-83ac-e031d9394440.png)

Let's see if anyone can help me, and tell me where they are after the last repository update.

@AKSHAYUBHAT and about the errors that they gave me in the two files (_**detect_text.ipynb**_ and _**recognize_text.ipynb**_) as I had told you in previous issues, here you can see how I downloaded the repository from a PC that has no docker image.

**Comment by AKSHAYUBHAT** [comment]
The two files are at https://github.com/AKSHAYUBHAT/DeepVideoAnalytics/tree/master/docs/experiments/ocr

Rather than using `docker run` instead run start_tutorial.py . 

```
git clone https://github.com/AKSHAYUBHAT/DeepVideoAnalytics
cd DeepVideoAnalytics/docs/tutorial && python start_tutorial.py
```

To stop and delete containers and volumes run
```
cd DeepVideoAnalytics/docs/tutorial && python stop_and_delete_volumes.py
```

**Comment by AKSHAYUBHAT** [comment]
I have tested/updated the OCR notebooks your should be able to use them now.
