### ISSUE TITLE
Disable models

### ISSUE THREAD

**Issue by bartengine27** [AKSHAYUBHAT/DeepVideoAnalytics#125]
Hi,

  Thanks for this great tool!

  How can I disable some of the models used in the default pipeline?

Thanks,
Bart

**Comment by AKSHAYUBHAT** [comment]
You can edit following files. 
- [framelist processing]( https://github.com/AKSHAYUBHAT/DeepVideoAnalytics/blob/master/configs/custom_defaults/framelist_processing.json)

- [dataset processing](https://github.com/AKSHAYUBHAT/DeepVideoAnalytics/blob/master/configs/custom_defaults/dataset_processing.json)

- [video processing](https://github.com/AKSHAYUBHAT/DeepVideoAnalytics/blob/master/configs/custom_defaults/video_processing.json)

Make sure that the files are not overwritten when `git pull` is performed.

**Comment by bartengine27** [comment]
I noticed that https://github.com/AKSHAYUBHAT/DeepVideoAnalytics/blob/master/deploy/gpu/docker-compose-2-gpus.yml contains references to coco, face, facenet, etc. while https://github.com/AKSHAYUBHAT/DeepVideoAnalytics/blob/master/deploy/gpu/docker-compose-gpu.yml does not.

Is that on purpose and what is the relation to the files mentioned in your previous post?

Thanks!
Bart
