### ISSUE TITLE
out of memory

### ISSUE THREAD

**Issue by bartengine27** [AKSHAYUBHAT/DeepVideoAnalytics#126]
# Checklist for submitting an issue 

- Have you verified that docker is installed correctly and e.g. GFW is not preventing downloads?
yes

- Which docker-compose.yml file are you using?
docker-compose-gpu.yml

- Please post output of `docker ps -a` or confirm that all containers are running?
CONTAINER ID        IMAGE                      COMMAND                  CREATED             STATUS                    PORTS                                                        NAMES
efb802082410        akshayubhat/dva-auto:gpu   "bash -c 'git pull..."   21 hours ago        Up 11 minutes             6006/tcp, 127.0.0.1:8888->8888/tcp, 127.0.0.1:8000->80/tcp   webserver
d2e13adbcf52        rabbitmq                   "docker-entrypoint..."   21 hours ago        Up 12 minutes             4369/tcp, 5671-5672/tcp, 25672/tcp                           dva-rmq
2fd0e8209a15        postgres:9.6.6             "docker-entrypoint..."   21 hours ago        Up 11 minutes             5432/tcp                                                     dva-pg
229cd958388d        bitnami/redis:latest       "/app-entrypoint.s..."   21 hours ago        Up 11 minutes             6379/tcp                                                     dva-redis
be6aae454e87        hello-world                "/hello"                 47 hours ago        Exited (0) 47 hours ago                                                                eager_wescoff
- If a specific container is not running or "exited" please post output of `docker logs <name of the container>`

- Is your question about OCR blog post in notebooks/OCR/ ? 
no

When I upload an image and try to use textbox, I see the following output in the logs:
`
webserver | 2018-01-26 18:00:12.993146: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1030] Found device 0 with properties: 
webserver | name: GeForce GTX 1080 Ti major: 6 minor: 1 memoryClockRate(GHz): 1.582
webserver | pciBusID: 0000:01:00.0
webserver | totalMemory: 10.91GiB freeMemory: 9.99GiB
webserver | 2018-01-26 18:00:12.993160: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1120] Creating TensorFlow device (/device:GPU:0) -> (device: 0, name: GeForce GTX 1080 Ti, pci bus id: 0000:01:00.0, compute capability: 6.1)
webserver | WARNING:tensorflow:<tensorflow.python.ops.rnn_cell_impl.BasicLSTMCell object at 0x7f8c7c1afcd0>: Using a concatenated state is slower and will soon be deprecated.  Use state_is_tuple=True.
webserver | INFO:tensorflow:Restoring parameters from /root/media//models/958563df-a735-45ca-b78a-5d98ca931114/VGGnet_fast_rcnn_iter_50000.ckpt
webserver | 2018-01-26 18:00:20.898579: W tensorflow/core/common_runtime/bfc_allocator.cc:217] Allocator (GPU_0_bfc) ran out of memory trying to allocate 3.23GiB. The caller indicates that this is not a failure, but may mean that there could be performance gains if more memory is available.
webserver | 2018-01-26 18:00:20.939270: W tensorflow/core/common_runtime/bfc_allocator.cc:217] Allocator (GPU_0_bfc) ran out of memory trying to allocate 2.32GiB. The caller indicates that this is not a failure, but may mean that there could be performance gains if more memory is available.
webserver | 2018-01-26 18:00:20.965677: W tensorflow/core/common_runtime/bfc_allocator.cc:217] Allocator (GPU_0_bfc) ran out of memory trying to allocate 3.09GiB. The caller indicates that this is not a failure, but may mean that there could be performance gains if more memory is available.
`

Based on 
`totalMemory: 10.91GiB freeMemory: 9.99GiB`

I would expect that the GPU has more than enough memory. Am I missing anything?

Thanks!
Bart

**Comment by AKSHAYUBHAT** [comment]
1080 ti does not have enough memory, I will update with a low memory script that launches indexing models in CPU mode.

**Comment by bartengine27** [comment]
thx for the feedback!

I'm now using only coco (based on your info in https://github.com/AKSHAYUBHAT/DeepVideoAnalytics/issues/125) and I'm now seeing connection issues with AMQP

good idea to install a second GPU?

**Comment by AKSHAYUBHAT** [comment]
You can try using this new docker-compose file. Essentially it runs all models except textbox detector and coco mobilenet ssd on CPU. The two detectors are run on GPU with each model allocated 45% of the memory. 

https://github.com/AKSHAYUBHAT/DeepVideoAnalytics/blob/master/deploy/gpu/docker-compose-gpu-low-memory.yml
