### ISSUE TITLE
git error at startup

### ISSUE THREAD

**Issue by bartengine27** [AKSHAYUBHAT/DeepVideoAnalytics#127]
# Checklist for submitting an issue 

- Have you verified that docker is installed correctly and e.g. GFW is not preventing downloads?
yes

- Which docker-compose.yml file are you using?
docker-compose-gpu.yml

- Please post output of `docker ps -a` or confirm that all containers are running?
issue at startup

- If a specific container is not running or "exited" please post output of `docker logs <name of the container>`

- Is your question about OCR blog post in notebooks/OCR/ ? 
no

at startup the following error is logged (clone of the latest version):

webserver | From https://github.com/akshayubhat/DeepVideoAnalytics
webserver |    6f27946..38a8e47  master     -> origin/master
webserver | error: Your local changes to the following files would be overwritten by merge:
webserver | 	repos/tf_ctpn_cpu/lib/utils/bbox.c
webserver | 	repos/tf_ctpn_cpu/lib/utils/cython_nms.c
webserver | 	repos/tf_ctpn_cpu/lib/utils/gpu_nms.c
webserver | Please, commit your changes or stash them before you can merge.
webserver | Aborting
webserver | Updating a38f7a9..38a8e47

and the webserver exits

**Comment by bartengine27** [comment]
great, thx!

will test after your commit (similar issue with the new docker-compose-gpu-low-memory.yml)

**Comment by bartengine27** [comment]
after https://github.com/AKSHAYUBHAT/DeepVideoAnalytics/commit/55cc516c1b26053f2a6f817ec438268a2d2c2dc6 :

webserver | From https://github.com/akshayubhat/DeepVideoAnalytics
webserver |    056a75a..55cc516  master     -> origin/master
webserver | error: Your local changes to the following files would be overwritten by merge:
webserver | 	configs/custom_defaults/trained_models_mac.json
webserver | 	repos/tf_ctpn_cpu/lib/utils/gpu_nms.c
webserver | Please, commit your changes or stash them before you can merge.
webserver | Aborting
webserver | Updating 056a75a..55cc516

**Comment by AKSHAYUBHAT** [comment]
Fix in latest commit.
