### ISSUE TITLE
AttributeError: 'TrainedModel' object has no attribute 'get_yolo_args'

### ISSUE THREAD

**Issue by bartengine27** [AKSHAYUBHAT/DeepVideoAnalytics#128]
# Checklist for submitting an issue 

- Have you verified that docker is installed correctly and e.g. GFW is not preventing downloads?
yes

- Which docker-compose.yml file are you using?
docker-compose-gpu-low-memory.yml

- Please post output of `docker ps -a` or confirm that all containers are running?
CONTAINER ID        IMAGE                         COMMAND                  CREATED             STATUS                  PORTS                                                        NAMES
910bf8da180d        akshayubhat/dva-auto:latest   "bash -c 'git rese..."   9 minutes ago       Up 9 minutes            6006/tcp, 127.0.0.1:8888->8888/tcp, 127.0.0.1:8000->80/tcp   webserver
f8ad63c02a09        akshayubhat/dva-auto:gpu      "bash -c 'git rese..."   9 minutes ago       Up 9 minutes            80/tcp, 6006/tcp, 8888/tcp                                   gpu_coco_1
47b38f5b6583        akshayubhat/dva-auto:gpu      "bash -c 'git rese..."   9 minutes ago       Up 9 minutes            80/tcp, 6006/tcp, 8888/tcp                                   gpu_textbox_1
d2e13adbcf52        rabbitmq                      "docker-entrypoint..."   2 days ago          Up 9 minutes            4369/tcp, 5671-5672/tcp, 25672/tcp                           dva-rmq
2fd0e8209a15        postgres:9.6.6                "docker-entrypoint..."   2 days ago          Up 9 minutes            5432/tcp                                                     dva-pg
229cd958388d        bitnami/redis:latest          "/app-entrypoint.s..."   2 days ago          Up 9 minutes            6379/tcp                                                     dva-redis
be6aae454e87        hello-world                   "/hello"                 3 days ago          Exited (0) 3 days ago                                                                eager_wescoff

- If a specific container is not running or "exited" please post output of `docker logs <name of the container>`

- Is your question about OCR blog post in notebooks/OCR/ ? 
no

As yolo is not enabled in this docker-compose, it should not be possible to select "license plate detector" 

webserver  | [2018-01-27 22:21:37,840] ERROR in app: Exception on /156/ [GET]
webserver  | Traceback (most recent call last):
webserver  |   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1982, in wsgi_app
webserver  |     response = self.full_dispatch_request()
webserver  |   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1614, in full_dispatch_request
webserver  |     rv = self.handle_user_exception(e)
webserver  |   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1517, in handle_user_exception
webserver  |     reraise(exc_type, exc_value, tb)
webserver  |   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1612, in full_dispatch_request
webserver  |     rv = self.dispatch_request()
webserver  |   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1598, in dispatch_request
webserver  |     return self.view_functions[rule.endpoint](**req.view_args)
webserver  |   File "scripts/run_flask.py", line 29, in process_task
webserver  |     handle_perform_detection(start)
webserver  |   File "scripts/../dvaapp/task_handlers.py", line 93, in handle_perform_detection
webserver  |     detection.Detectors.load_detector(cd)
webserver  |   File "scripts/../dvaapp/operations/detection.py", line 26, in load_detector
webserver  |     Detectors._detectors[cd.pk] = detector.YOLODetector(cd.get_yolo_args())
webserver  | AttributeError: 'TrainedModel' object has no attribute 'get_yolo_args'

**Comment by AKSHAYUBHAT** [comment]
- Currently YOLO detector (which the licence plate model uses) is not supported, however I am planning to turn it back on. This is the reason for the error.

- Regarding your argument, DVA uses a "Global model queue" which lets you run a model if there is no dedicated worker for processing it (It looks at the Worker table to determine this). In this case a global model worker will keep least recently used model in memory and use it to process assigned task. E.g. You can try this with tf_face_detector from VDN. which will run on a global model queue. This design allows users to dynamically load and use new models while retaining ability to schedule/optimize by launching dedicated workers.

**Comment by bartengine27** [comment]
thanks for clarifying!
