### ISSUE TITLE
duplicate key violates unique constraint

### ISSUE THREAD

**Issue by bartengine27** [AKSHAYUBHAT/DeepVideoAnalytics#129]
# Checklist for submitting an issue 

- Have you verified that docker is installed correctly and e.g. GFW is not preventing downloads?
yes

- Which docker-compose.yml file are you using?
docker-compose-gpu-low-memory.yml

- Please post output of `docker ps -a` or confirm that all containers are running?
CONTAINER ID        IMAGE                         COMMAND                  CREATED             STATUS                  PORTS                                                        NAMES
910bf8da180d        akshayubhat/dva-auto:latest   "bash -c 'git rese..."   9 minutes ago       Up 9 minutes            6006/tcp, 127.0.0.1:8888->8888/tcp, 127.0.0.1:8000->80/tcp   webserver
f8ad63c02a09        akshayubhat/dva-auto:gpu      "bash -c 'git rese..."   9 minutes ago       Up 9 minutes            80/tcp, 6006/tcp, 8888/tcp                                   gpu_coco_1
47b38f5b6583        akshayubhat/dva-auto:gpu      "bash -c 'git rese..."   9 minutes ago       Up 9 minutes            80/tcp, 6006/tcp, 8888/tcp                                   gpu_textbox_1
d2e13adbcf52        rabbitmq                      "docker-entrypoint..."   2 days ago          Up 9 minutes            4369/tcp, 5671-5672/tcp, 25672/tcp                           dva-rmq
2fd0e8209a15        postgres:9.6.6                "docker-entrypoint..."   2 days ago          Up 9 minutes            5432/tcp                                                     dva-pg
229cd958388d        bitnami/redis:latest          "/app-entrypoint.s..."   2 days ago          Up 9 minutes            6379/tcp                                                     dva-redis
be6aae454e87        hello-world                   "/hello"                 3 days ago          Exited (0) 3 days ago                                                                eager_wescoff

- If a specific container is not running or "exited" please post output of `docker logs <name of the container>`

- Is your question about OCR blog post in notebooks/OCR/ ? 
no

Cannot reproduce, yet.

dva-pg     | ERROR:  duplicate key value violates unique constraint "django_celery_results_taskresult_task_id_key"
dva-pg     | DETAIL:  Key (task_id)=(81bc1cd2-83b3-4930-9c55-f7086e489e23) already exists.
dva-pg     | STATEMENT:  INSERT INTO "django_celery_results_taskresult" ("task_id", "status", "content_type", "content_encoding", "result", "date_done", "traceback", "hidden", "meta") VALUES ('81bc1cd2-83b3-4930-9c55-f7086e489e23', 'STARTED', 'application/json', 'utf-8', '{"hostname": "celery@manager.47b38f5b6583", "pid": 111}', '2018-01-27T22:22:01.330620+00:00'::timestamptz, NULL, false, '{"children": []}') RETURNING "django_celery_results_taskresult"."id"
dva-pg     | ERROR:  duplicate key value violates unique constraint "django_celery_results_taskresult_task_id_key"
dva-pg     | DETAIL:  Key (task_id)=(81bc1cd2-83b3-4930-9c55-f7086e489e23) already exists.
dva-pg     | STATEMENT:  INSERT INTO "django_celery_results_taskresult" ("task_id", "status", "content_type", "content_encoding", "result", "date_done", "traceback", "hidden", "meta") VALUES ('81bc1cd2-83b3-4930-9c55-f7086e489e23', 'STARTED', 'application/json', 'utf-8', '{"hostname": "celery@manager.910bf8da180d", "pid": 545}', '2018-01-27T22:22:01.330593+00:00'::timestamptz, NULL, false, '{"children": []}') RETURNING "django_celery_results_taskresult"."id"
dva-redis  | 21:M 27 Jan 22:24:38.016 * 10 changes in 300 seconds. Saving...
dva-redis  | 21:M 27 Jan 22:24:38.018 * Background saving started by pid 32
dva-redis  | 32:C 27 Jan 22:24:38.239 * DB saved on disk
dva-redis  | 32:C 27 Jan 22:24:38.240 * RDB: 5 MB of memory used by copy-on-write
dva-redis  | 21:M 27 Jan 22:24:38.318 * Background saving terminated with success
dva-pg     | ERROR:  duplicate key value violates unique constraint "django_celery_results_taskresult_task_id_key"
dva-pg     | DETAIL:  Key (task_id)=(05920631-0941-41e5-9348-f6a9e407515e) already exists.
dva-pg     | STATEMENT:  INSERT INTO "django_celery_results_taskresult" ("task_id", "status", "content_type", "content_encoding", "result", "date_done", "traceback", "hidden", "meta") VALUES ('05920631-0941-41e5-9348-f6a9e407515e', 'STARTED', 'application/json', 'utf-8', '{"hostname": "celery@manager.910bf8da180d", "pid": 545}', '2018-01-27T22:25:00.940938+00:00'::timestamptz, NULL, false, '{"children": []}') RETURNING "django_celery_results_taskresult"."id"
dva-pg     | ERROR:  duplicate key value violates unique constraint "django_celery_results_taskresult_task_id_key"
dva-pg     | DETAIL:  Key (task_id)=(05920631-0941-41e5-9348-f6a9e407515e) already exists.
dva-pg     | STATEMENT:  INSERT INTO "django_celery_results_taskresult" ("task_id", "status", "content_type", "content_encoding", "result", "date_done", "traceback", "hidden", "meta") VALUES ('05920631-0941-41e5-9348-f6a9e407515e', 'STARTED', 'application/json', 'utf-8', '{"hostname": "celery@manager.47b38f5b6583", "pid": 111}', '2018-01-27T22:25:00.940980+00:00'::timestamptz, NULL, false, '{"children": []}') RETURNING "django_celery_results_taskresult"."id"

**Comment by AKSHAYUBHAT** [comment]
I have noticed this happening too. My guess is that this happens due to uuid's ("05920631-0941-41e5-9348-f6a9e407515e") are no longer unique when launching "broadcast" tasks. However since I almost never rely on celery task results [1], these errors can be safely ignored. Note that they happen on broadcast monitoring tasks ( '{"hostname": "celery@manager.910bf8da180d", "pid": 545}'). 

[1] http://docs.celeryproject.org/en/latest/userguide/routing.html#id25
