### ISSUE TITLE
query using this detection

### ISSUE THREAD

**Issue by bartengine27** [AKSHAYUBHAT/DeepVideoAnalytics#131]
How is "query using this detection" supposed to work? I get redirect to an URL like http://localhost:8000/query_detection/1078/

**Comment by AKSHAYUBHAT** [comment]
It's merely a shortcut to load the frame into dashboard. Though it future it will crop using bounding box and load the crop rather than loading the entire frame.

**Comment by bartengine27** [comment]
noticed that after moving the frame to bring the object of interest into "focus", removing license plate detector and selecting coco works - great job!

**Comment by AKSHAYUBHAT** [comment]
You can view exceptions directly in UI by going to the page for the specific task which failed (since Celery records exceptions). Even if a query fails, partial results are always available in the query detail page from sidebar.
