### ISSUE TITLE
cannot delete video

### ISSUE THREAD

**Issue by bartengine27** [AKSHAYUBHAT/DeepVideoAnalytics#132]
the "delete (only staff)" button on a page like http://localhost:8000/videos/5c99deed-a7b5-43e2-a955-338f041b083e/ does not work

**Comment by AKSHAYUBHAT** [comment]
Thanks, I am still working on it. 

Self note: 
- Delete should be porte via a DVAPQL query. 
- User deleted_video_pk to do garbage collection on shared file system / remote cloud fs.

**Comment by AKSHAYUBHAT** [comment]
Fixed in the latest commit. 

Garbage collection of deleted videos pending along with stopping cascades process on delete.
