### ISSUE TITLE
invalid link

### ISSUE THREAD

**Issue by bartengine27** [AKSHAYUBHAT/DeepVideoAnalytics#135]
The link https://github.com/AKSHAYUBHAT/DeepVideoAnalytics/blob/master/tests/exampledataset.zip used in the "Upload video / dataset or list of images or exported zip file." pop-up (example of a zip file) is not valid anymore.

**Comment by AKSHAYUBHAT** [comment]
Fixed, will commit shortly. 

https://github.com/AKSHAYUBHAT/DeepVideoAnalytics/blob/master/tests/ci/exampledataset.zip
