### ISSUE TITLE
LAN/VPN access

### ISSUE THREAD

**Issue by bartengine27** [AKSHAYUBHAT/DeepVideoAnalytics#139]
If you need easy access from your LAN or VPN, change the ports section under dva in docker-compose-gpu...yml into

     ports:
       - "0.0.0.0:8000:80" # Since Docker messes up iptables, ufw has no effect as a result bind to localhost and tunnel / Port forward through SSH
       - "0.0.0.0:8888:8888" # Since Docker messes up iptables, ufw has no effect as a result bind to localhost and tunnel / Port forward through SSH

**Comment by AKSHAYUBHAT** [comment]
If you are using SSH I recommend forwarding 8000 and 8888 while keeping the loopback interface but the above solution is also okay, though you need to be careful if you use VPS provider and the provider does not provides any Firewall.
