### ISSUE TITLE
cant wget file from dropbox

### ISSUE THREAD

**Issue by tamirgold** [AKSHAYUBHAT/DeepVideoAnalytics#14]
--2017-03-17 13:04:48--  https://www.dropbox.com/s/0zopjpswug5rjqy/yolo9000.weights
Resolving www.dropbox.com (www.dropbox.com)... 162.125.4.1
Connecting to www.dropbox.com (www.dropbox.com)|162.125.4.1|:443... connected.
HTTP request sent, awaiting response... 500 Internal Server Error
2017-03-17 13:04:48 ERROR 500: Internal Server Error.

**Comment by AKSHAYUBHAT** [comment]
Thanks for reporting there seems to be some problem with dropbox. You can either 

1. Just comment out that line, since it not needed unless you use YOLO 9000 which is otherwise disabled by  default
2. Or use the file from darknet website http://pjreddie.com/media/files/yolo9000.weights

**Comment by AKSHAYUBHAT** [comment]
Update: it appears that Dropbox is having issues 

https://istheservicedown.com/problems/dropbox?utm_source=Twitter&utm_medium=Social&utm_campaign=TweetReply

**Comment by tamirgold** [comment]
yep, saw that as well
