### ISSUE TITLE
lopq index and traing

### ISSUE THREAD

**Issue by gucasbrg** [AKSHAYUBHAT/DeepVideoAnalytics#140]
hi,
  use own images,can I use lopq to generate incremental index on line?

**Comment by AKSHAYUBHAT** [comment]
Yes you can see this example:

https://github.com/VisualDataNetwork/root/blob/master/training/train_lfw_facenet_lopq.json

Essentially you can train an "approximator" which converts the vector space into LOPQ codes. Once the trained approximator is available you can use it by running perform_index_approximation after perform_indexing and using retriever specific to the approximator.
