### ISSUE TITLE
Execute the compose. Yml file and report the error

### ISSUE THREAD

**Issue by MrLichangming** [AKSHAYUBHAT/DeepVideoAnalytics#147]
# Checklist for submitting an issue 

- Have you verified that docker is installed correctly and e.g. GFW is not preventing downloads?
  True
- Which docker-compose.yml file are you using?
  Yes
- Please post output of `docker ps -a` or confirm that all containers are running?
  When I use the docker-compose. Yml file, execute the command docker-compose up, and report the error.
-Excute docker logs webserver output error info
[root@localhost cpu]# docker logs webserver
HEAD is now at a47a90b Merge pull request #146 from AKSHAYUBHAT/master
From https://github.com/akshayubhat/DeepVideoAnalytics
   13eee28..0309113  master     -> origin/master
Already up-to-date.
/usr/local/lib/python2.7/dist-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
WARNING:root:Could not import indexer / clustering assuming running in front-end mode
No changes detected
/usr/local/lib/python2.7/dist-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
WARNING:root:Could not import indexer / clustering assuming running in front-end mode
Operations to perform:
  Apply all migrations: admin, auth, authtoken, contenttypes, django_celery_beat, django_celery_results, dvaapp, dvaui, sessions
Running migrations:
  No migrations to apply.
/usr/local/lib/python2.7/dist-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Traceback (most recent call last):
  File "./init_fs.py", line 59, in <module>
    dm.download()
  File "/root/DVA/server/dvaapp/models.py", line 276, in download
    fs.get_path_to_file(m['url'],dlpath)
  File "/root/DVA/server/dvaapp/fs.py", line 170, in get_path_to_file
    r = requests.get(path + '?dl=1')
  File "/usr/local/lib/python2.7/dist-packages/requests/api.py", line 72, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/adapters.py", line 508, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='www.dropbox.com', port=443): Max retries exceeded with url: /s/bmuo0vhftf8hi27/model.proto?dl=1 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f18872dd650>: Failed to establish a new connection: [Errno 110] Connection timed out',))
Traceback (most recent call last):
  File "./start_container.py", line 15, in <module>
    subprocess.check_call(['./init_fs.py', ])
  File "/usr/lib/python2.7/subprocess.py", line 541, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['./init_fs.py']' returned non-zero exit status 1
HEAD is now at a47a90b Merge pull request #146 from AKSHAYUBHAT/master
Already up-to-date.
/usr/local/lib/python2.7/dist-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
WARNING:root:Could not import indexer / clustering assuming running in front-end mode
No changes detected
/usr/local/lib/python2.7/dist-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
WARNING:root:Could not import indexer / clustering assuming running in front-end mode
Operations to perform:
  Apply all migrations: admin, auth, authtoken, contenttypes, django_celery_beat, django_celery_results, dvaapp, dvaui, sessions
Running migrations:
  No migrations to apply.
/usr/local/lib/python2.7/dist-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Traceback (most recent call last):
  File "./init_fs.py", line 59, in <module>
    dm.download()
  File "/root/DVA/server/dvaapp/models.py", line 276, in download
    fs.get_path_to_file(m['url'],dlpath)
  File "/root/DVA/server/dvaapp/fs.py", line 170, in get_path_to_file
    r = requests.get(path + '?dl=1')
  File "/usr/local/lib/python2.7/dist-packages/requests/api.py", line 72, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/adapters.py", line 508, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='www.dropbox.com', port=443): Max retries exceeded with url: /s/77kmt20jnh31jsd/eigenvals.npy?dl=1 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7ff0e63dd790>: Failed to establish a new connection: [Errno 111] Connection refused',))
Traceback (most recent call last):
  File "./start_container.py", line 15, in <module>
    subprocess.check_call(['./init_fs.py', ])
  File "/usr/lib/python2.7/subprocess.py", line 541, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['./init_fs.py']' returned non-zero exit status 1
HEAD is now at a47a90b Merge pull request #146 from AKSHAYUBHAT/master
Already up-to-date.
/usr/local/lib/python2.7/dist-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
WARNING:root:Could not import indexer / clustering assuming running in front-end mode
No changes detected
/usr/local/lib/python2.7/dist-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
WARNING:root:Could not import indexer / clustering assuming running in front-end mode
Operations to perform:
  Apply all migrations: admin, auth, authtoken, contenttypes, django_celery_beat, django_celery_results, dvaapp, dvaui, sessions
Running migrations:
  No migrations to apply.
/usr/local/lib/python2.7/dist-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Traceback (most recent call last):
  File "./launch_from_env.py", line 22, in <module>
    queue_name = 'q_retriever_{}'.format(dm.pk)
AttributeError: 'NoneType' object has no attribute 'pk'
Traceback (most recent call last):
  File "./start_container.py", line 16, in <module>
    subprocess.check_call(['./launch_from_env.py','0'])
  File "/usr/lib/python2.7/subprocess.py", line 541, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['./launch_from_env.py', '0']' returned non-zero exit status 1

-Terminal output error status information.
webserver | HEAD is now at a47a90b Merge pull request #146 from AKSHAYUBHAT/master
webserver | Already up-to-date.
webserver | /usr/local/lib/python2.7/dist-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
webserver |   from ._conv import register_converters as _register_converters
webserver | WARNING:root:Could not import indexer / clustering assuming running in front-end mode
webserver | No changes detected
webserver | /usr/local/lib/python2.7/dist-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
webserver |   from ._conv import register_converters as _register_converters
webserver | WARNING:root:Could not import indexer / clustering assuming running in front-end mode
webserver | Operations to perform:
webserver |   Apply all migrations: admin, auth, authtoken, contenttypes, django_celery_beat, django_celery_results, dvaapp, dvaui, sessions
webserver | Running migrations:
webserver |   No migrations to apply.
webserver | /usr/local/lib/python2.7/dist-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
webserver |   from ._conv import register_converters as _register_converters
dva-rmq   | 2018-02-27 10:22:32.415 [info] <0.1105.0> accepting AMQP connection <0.1105.0> (172.18.0.5:37276 -> 172.18.0.3:5672)
dva-rmq   | 2018-02-27 10:22:32.547 [info] <0.1105.0> connection <0.1105.0> (172.18.0.5:37276 -> 172.18.0.3:5672): user 'dvauser' authenticated and granted access to vhost '/'
dva-rmq   | 2018-02-27 10:22:32.865 [warning] <0.1105.0> closing AMQP connection <0.1105.0> (172.18.0.5:37276 -> 172.18.0.3:5672, vhost: '/', user: 'dvauser'):
dva-rmq   | client unexpectedly closed TCP connection
webserver | Traceback (most recent call last):
webserver |   File "./launch_from_env.py", line 22, in <module>
webserver |     queue_name = 'q_retriever_{}'.format(dm.pk)
webserver | AttributeError: 'NoneType' object has no attribute 'pk'
webserver | Traceback (most recent call last):
webserver |   File "./start_container.py", line 16, in <module>
webserver |     subprocess.check_call(['./launch_from_env.py','0'])
webserver |   File "/usr/lib/python2.7/subprocess.py", line 541, in check_call
webserver |     raise CalledProcessError(retcode, cmd)
webserver | subprocess.CalledProcessError: Command '['./launch_from_env.py', '0']' returned non-zero exit status 1
webserver exited with code 1

**Comment by AKSHAYUBHAT** [comment]
Hi, Sorry this was due to a Dropbox shared links not working for some time today. Please try again it should would now.
