### ISSUE TITLE
Excute docker-compose.yml file encounter error

### ISSUE THREAD

**Issue by wangning175246** [AKSHAYUBHAT/DeepVideoAnalytics#148]
-Single machine without GPU
  Excute  command:   docker-compose up -f docker-compose.yml
-Error info
webserver | Traceback (most recent call last):
webserver |   File "./launch_from_env.py", line 22, in <module>
webserver |     queue_name = 'q_retriever_{}'.format(dm.pk)
webserver | AttributeError: 'NoneType' object has no attribute 'pk'
webserver | Traceback (most recent call last):
webserver |   File "./start_container.py", line 16, in <module>
webserver |     subprocess.check_call(['./launch_from_env.py','0'])
webserver |   File "/usr/lib/python2.7/subprocess.py", line 541, in check_call
webserver |     raise CalledProcessError(retcode, cmd)
webserver | subprocess.CalledProcessError: Command '['./launch_from_env.py', '0']' returned non-zero exit status 1
webserver exited with code 1

**Comment by AKSHAYUBHAT** [comment]
Hi, Sorry this is same as  

https://github.com/AKSHAYUBHAT/DeepVideoAnalytics/issues/147

Please try again it should work now.
