### ISSUE TITLE
start webserver error

### ISSUE THREAD

**Issue by wangning175246** [AKSHAYUBHAT/DeepVideoAnalytics#149]
webserver | /usr/local/lib/python2.7/dist-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
webserver |   from ._conv import register_converters as _register_converters
webserver | /usr/local/lib/python2.7/dist-packages/psycopg2/__init__.py:144: UserWarning: The psycopg2 wheel package will be renamed from release 2.8; in order to keep installing from binary please use "pip install psycopg2-binary" instead. For details see: <http://initd.org/psycopg/docs/install.html#binary-install-from-pypi>.
webserver |   """)
webserver | Traceback (most recent call last):
webserver |   File "./launch_from_env.py", line 22, in <module>
webserver |     queue_name = 'q_retriever_{}'.format(dm.pk)
webserver | AttributeError: 'NoneType' object has no attribute 'pk'
webserver | Traceback (most recent call last):
webserver |   File "./start_container.py", line 16, in <module>
webserver |     subprocess.check_call(['./launch_from_env.py','0'])
webserver |   File "/usr/lib/python2.7/subprocess.py", line 541, in check_call
webserver |     raise CalledProcessError(retcode, cmd)
webserver | subprocess.CalledProcessError: Command '['./launch_from_env.py', '0']' returned non-zero exit status 1

**Comment by AKSHAYUBHAT** [comment]
closed due to inactivity // cannot reproduce.
