### ISSUE TITLE
starting the pre-build docker

### ISSUE THREAD

**Issue by tamirgold** [AKSHAYUBHAT/DeepVideoAnalytics#15]
thank you for all the hard work !
I started the pre-build docker and logged in to the jupyter ui, what do i do next ?

**Comment by AKSHAYUBHAT** [comment]
you need to use ` docker-compose up` and not ` docker run `.
The docker run will start a jupyter notebook server for exploration. ` docker-compose up ` will start the actual server after automatically setting up the queues and database containers..
