### ISSUE TITLE
Webserver start error

### ISSUE THREAD

**Issue by MrLichangming** [AKSHAYUBHAT/DeepVideoAnalytics#150]
# Checklist for submitting an issue 

- Have you verified that docker is installed correctly and e.g. GFW is not preventing downloads?
True 
Docker version:
   Docker version 17.12.1-ce, build 7390fc6
docker-compose version: 
  docker-compose version 1.19.0, build 9e633ef
  
- Which docker-compose.yml file are you using?
Yes
- Please post output of `docker ps -a` or confirm that all containers are running?
Execept docker-compose up .   encounter  error
- If a specific container is not running or "exited" please post output of `docker logs <name of the container>`
webserver error log:

webserver |   """)
webserver | Illegal instruction (core dumped)
webserver | /usr/local/lib/python2.7/dist-packages/psycopg2/__init__.py:144: UserWarning: The psycopg2 wheel package will be renamed from release 2.8; in order to keep installing from binary please use "pip install psycopg2-binary" instead. For details see: <http://initd.org/psycopg/docs/install.html#binary-install-from-pypi>.
webserver |   """)
webserver | Illegal instruction (core dumped)
webserver | Traceback (most recent call last):
webserver |   File "./start_container.py", line 14, in <module>
webserver |     subprocess.check_call(['./migrate.sh',])
webserver |   File "/usr/lib/python2.7/subprocess.py", line 541, in check_call
webserver |     raise CalledProcessError(retcode, cmd)
webserver | subprocess.CalledProcessError: Command '['./migrate.sh']' returned non-zero exit status 132
webserver exited with code 1

- Is your question about OCR blog post in notebooks/OCR/ ?

**Comment by AKSHAYUBHAT** [comment]
>> Illegal instruction (core dumped)

This is likely due Tensorflow 1.6 using AVX instructions which are not available on older processors. Since 1.6 uses AVX by default and lead to significant speedup I recommend using a latest CPU.

**Comment by MrLichangming** [comment]
OK，thank you，




李常明
On 3/3/2018 01:29，Akshay Bhat<notifications@github.com> wrote：

Illegal instruction (core dumped)

This is likely due Tensorflow 1.6 using AVX instructions which are not available on older processors. Since 1.6 uses AVX by default and lead to significant speedup I recommend using a latest CPU.

**Comment by chengfei211** [comment]
I have some question about this project,but this can not say carefully,can you tell me you message,can i communicate with you underly?
