### ISSUE TITLE
Please clarify Licensing format (OCR) / dvalib

### ISSUE THREAD

**Issue by datascienceteam01** [AKSHAYUBHAT/DeepVideoAnalytics#155]
**Abstract**: It's my intention to test the OCR module. Apparently the currently "open sourced" pieces rely on using your semi closed back-end (the DeepVideoAnalytics claims a copyright notice and the project's hierarchy is meant to be executed within your docker images, rendering its independent  implementation/compilation barely impossible). 

**Questions**:

1. Is the dvalib going to be available soon under an open source license and documentation sufficient to compile / implement it independently from your docker images?
2. What are the limitations on the usage of your trained models? 

These are important questions that are somewhat addressed in an elusive manner in other tickets.

**Comment by AKSHAYUBHAT** [comment]
Hi Alexandre, 

Both Textbox detection and Text recognition models are Open Source 

- https://github.com/eragonruan/text-detection-ctpn
- https://github.com/meijieru/crnn.pytorch

While I agree that there are pending issues regarding license for Deep Video Analytics, you should be able to use both models and code provided by original authors easily in to any program.  Feel free to email me if you have more questions / update on transition to an Open Source license..
