### ISSUE TITLE
Limit number of workers

### ISSUE THREAD

**Issue by dakshvar22** [AKSHAYUBHAT/DeepVideoAnalytics#156]
# Checklist for submitting an issue

- Have you verified that docker is installed correctly and e.g. GFW is not preventing downloads?
Yes

- Which docker-compose.yml file are you using?
docker-compose-gpu.yml

- Please post output of `docker ps -a` or confirm that all containers are running?
All are running

- If a specific container is not running or "exited" please post output of `docker logs <name of the container>`
None

- Is your question about OCR blog post in notebooks/OCR/ ? 
No

Hi,
I am facing a problem with the celery task manager. I am deploying DVA on a 4 core, 64 GB RAM Machine. I am able to open the DVA dashboard, but in a matter of 2 minutes the webserver container is bombarded with celery workers which fully fills up the system resources(CPU and RAM), hence the DVA dashboard is extremely slow.

Can I limit the number of workers somehow in any of the configuration files prior to deployment?

Some additional Info : In the logs of webserver container, I can see multiple warnings from celery module each mentioning this message -
```
/usr/local/lib/python2.7/dist-packages/celery/platforms.py:793: RuntimeWarning: You're running the worker with superuser privileges: this is
absolutely not recommended!

Please specify a different user using the -u option.

User information: uid=0 euid=0 gid=0 egid=0

  uid=uid, euid=euid, gid=gid, egid=egid,
```

**Comment by AKSHAYUBHAT** [comment]
You can ignore those warning. 

4 cores are simply not enough for default configuration, depending on your requirements you can modify deploy/cpu/docker-compose.yml to select which workers you want to launch. e.g. do you need COCO object detection or face recognition etc.
