### ISSUE TITLE
While starting server showing following error and server not getting up

### ISSUE THREAD

**Issue by kumarneeraj2005** [AKSHAYUBHAT/DeepVideoAnalytics#16]
dva-server | libdc1394 error: Failed to initialize libdc1394

dva-server | [tasks]
dva-server |   . alexnet_index_by_id
dva-server |   . alexnet_query_by_image
dva-server |   . dva.celery.debug_task
dva-server |   . dvaapp.tasks.IndexerTask
dva-server |   . extract_frames_by_id
dva-server |   . facenet_query_by_image
dva-server |   . inception_query_by_image
dva-server |   . inpcetion_index_by_id
dva-server |   . perform_face_detection_indexing_by_id
dva-server |   . perform_ssd_detection_by_id
dva-server |   . perform_yolo_detection_by_id
dva-server | 
dva-server | *** Error in `/usr/bin/python': free(): invalid pointer: 0x00007f9c24c9f9c0 ***
dva-server | libdc1394 error: Failed to initialize libdc1394
dva-server | libdc1394 error: Failed to initialize libdc1394
dva-server | *** Error in `/usr/bin/python': free(): invalid pointer: 0x00007ff2fb0279c0 ***
dva-server | *** Error in `/usr/bin/python': free(): invalid pointer: 0x00007fa7dd7849c0 ***

Please help here .

**Comment by AKSHAYUBHAT** [comment]
In my experience such pointer free errors are caused by OpenCV. Can you tell me version of Docker and Nvidia Docker you are running? Upgrading to the latest Docker version and recreating the container image typically fixes this problem.

**Comment by AKSHAYUBHAT** [comment]
I saw that you had a bug report regarding not enough memory available during docker build, it might be related to that too.

**Comment by kumarneeraj2005** [comment]
Previous Problem was solved when increased RAM size in Docker settings, but this problem is new one, actually i was reinstalling everything from scratch,as per your advise i will i will try to uninstall docker and re-install to newer version and let you know, thanks for your valuable reply 👍

**Comment by AKSHAYUBHAT** [comment]
Assuming this was fixed.
