### ISSUE TITLE
manage.py kube issue

### ISSUE THREAD

**Issue by metacomgd** [AKSHAYUBHAT/DeepVideoAnalytics#160]
Two typos that break kube start/stop

https://github.com/AKSHAYUBHAT/DeepVideoAnalytics/blob/1ff7d50cb6d9e1979de4beaf055da1e38a915bc4/manage.py#L319

and 

https://github.com/AKSHAYUBHAT/DeepVideoAnalytics/blob/1ff7d50cb6d9e1979de4beaf055da1e38a915bc4/manage.py#L332

**Comment by AKSHAYUBHAT** [comment]
Sorry, I don't understand. Is the typo inside the scheduler.yaml?

Since the path appears to be correct and same as all other.

**Comment by metacomgd** [comment]
sorry, should have been clearer.

the last two characters are transposed on these lines.

i.e. 
`',`
not
 `,'`

**Comment by AKSHAYUBHAT** [comment]
Thanks!
