### ISSUE TITLE
Dropbox shared links not working

### ISSUE THREAD

**Issue by liwenxi** [AKSHAYUBHAT/DeepVideoAnalytics#161]
# Checklist for submitting an issue 

- Have you verified that docker is installed correctly and e.g. GFW is not preventing downloads?
   I'm in China with Shadowsocks on.
   macOS 10.12.6.

- Which docker-compose.yml file are you using?
  I used command:
`python manage.py restart cpu --init_models https://gist.githubusercontent.com/AKSHAYUBHAT/5adccb7070a921ec244b3b524222d65b/raw/881de719510d7452d7f9915a6a938d1a05a91c15/models.json`

- If a specific container is not running or "exited" please post output of `docker logs <name of the container>`

> HEAD is now at af34c41 Merge pull request #159 from AKSHAYUBHAT/master
> From https://github.com/akshayubhat/DeepVideoAnalytics
>    b03ddcb..845519c  master     -> origin/master
> Already up-to-date.
> /usr/local/lib/python2.7/dist-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
>   from ._conv import register_converters as _register_converters
> Failed to load GPU Faiss: No module named swigfaiss_gpu
> Faiss falling back to CPU-only.
> WARNING:root:Could not import indexer / clustering assuming running in front-end mode
> No changes detected
> /usr/local/lib/python2.7/dist-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
>   from ._conv import register_converters as _register_converters
> Failed to load GPU Faiss: No module named swigfaiss_gpu
> Faiss falling back to CPU-only.
> WARNING:root:Could not import indexer / clustering assuming running in front-end mode
> Operations to perform:
>   Apply all migrations: admin, auth, authtoken, contenttypes, django_celery_beat, django_celery_results, dvaapp, dvaui, sessions
> Running migrations:
>   No migrations to apply.
> /usr/local/lib/python2.7/dist-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
>   from ._conv import register_converters as _register_converters
> Failed to load GPU Faiss: No module named swigfaiss_gpu
> Faiss falling back to CPU-only.
> Traceback (most recent call last):
>   File "./launch_from_env.py", line 22, in <module>
>     queue_name = 'q_retriever_{}'.format(dm.pk)
> AttributeError: 'NoneType' object has no attribute 'pk'
> Traceback (most recent call last):
>   File "./start_container.py", line 18, in <module>
>     subprocess.check_call(['./launch_from_env.py','0'])
>   File "/usr/lib/python2.7/subprocess.py", line 541, in check_call
>     raise CalledProcessError(retcode, cmd)
> subprocess.CalledProcessError: Command '['./launch_from_env.py', '0']' returned non-zero exit status 1

 I think this problem might be same as [#147](https://github.com/AKSHAYUBHAT/DeepVideoAnalytics/issues/147)
So please help me to check it.Thank you!

**Comment by AKSHAYUBHAT** [comment]
Thanks I am checking

**Comment by AKSHAYUBHAT** [comment]
Hey I just checked on Digital Ocean droplet if following command works and it did work. 
```
python manage.py restart cpu --init_models https://gist.githubusercontent.com/AKSHAYUBHAT/5adccb7070a921ec244b3b524222d65b/raw/881de719510d7452d7f9915a6a938d1a05a91c15/models.json
```
```
queue_name = 'q_retriever{}'.format(dm.pk)
AttributeError: 'NoneType' object has no attribute 'pk'
```

This appears when it's attempting to create a retriever for non-existing indexer. The reason an indexer might not exist would be because it did not get downloaded. Which might be because of the GFW. 

You can also try ensuring that you have the latest version of DeepVideoAnalytics repo by doing a `git pull` but I don't think it will solve the issue. Finally you can make copy of the gist and manually upload the weights to a server which is within GFW.
