### ISSUE TITLE
webserver container exited

### ISSUE THREAD

**Issue by lisadeng** [AKSHAYUBHAT/DeepVideoAnalytics#162]
Hi @AKSHAYUBHAT,
For setting DVA up in my local, I came across an issue, that is, after executing command "docker-compose up -d" with DeepVideoAnalytics/deploy/cpu/docker-compose.yml, the webserver container exited. Docker should have been installed correctly since containers of some other applications work 
properly. Below are some info for your reference, hope they could help.

Env: MacOS 10.13.2, Python 2.7

The output of `docker logs <webserver container>` is:
➜  cpu docker logs 6507ef477e31
HEAD is now at af34c41 Merge pull request #159 from AKSHAYUBHAT/master
From https://github.com/akshayubhat/DeepVideoAnalytics
   b03ddcb..e0bc549  master     -> origin/master
Already up-to-date.
/usr/local/lib/python2.7/dist-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Failed to load GPU Faiss: No module named swigfaiss_gpu
Faiss falling back to CPU-only.
WARNING:root:Could not import indexer / clustering assuming running in front-end mode
No changes detected
/usr/local/lib/python2.7/dist-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Failed to load GPU Faiss: No module named swigfaiss_gpu
Faiss falling back to CPU-only.
WARNING:root:Could not import indexer / clustering assuming running in front-end mode
Operations to perform:
  Apply all migrations: admin, auth, authtoken, contenttypes, django_celery_beat, django_celery_results, dvaapp, dvaui, sessions
Running migrations:
  Applying contenttypes.0001_initial... OK
  Applying auth.0001_initial... OK
  Applying admin.0001_initial... OK
  Applying admin.0002_logentry_remove_auto_add... OK
  Applying contenttypes.0002_remove_content_type_name... OK
  Applying auth.0002_alter_permission_name_max_length... OK
  Applying auth.0003_alter_user_email_max_length... OK
  Applying auth.0004_alter_user_username_opts... OK
  Applying auth.0005_alter_user_last_login_null... OK
  Applying auth.0006_require_contenttypes_0002... OK
  Applying auth.0007_alter_validators_add_error_messages... OK
  Applying auth.0008_alter_user_username_max_length... OK
  Applying authtoken.0001_initial... OK
  Applying authtoken.0002_auto_20160226_1747... OK
  Applying django_celery_beat.0001_initial... OK
  Applying django_celery_beat.0002_auto_20161118_0346... OK
  Applying django_celery_beat.0003_auto_20161209_0049... OK
  Applying django_celery_beat.0004_auto_20170221_0000... OK
  Applying django_celery_results.0001_initial... OK
  Applying dvaapp.0001_initial... OK
  Applying dvaapp.custom_migration... OK
  Applying dvaapp.0001_trainedmodel_uuid... OK
  Applying dvaapp.0002_trainedmodel_training_set... OK
  Applying dvaapp.0003_auto_20180120_1817... OK
  Applying dvaapp.0004_remove_trainingset_built_ts... OK
  Applying dvaapp.0005_trainingset_files... OK
  Applying dvaapp.0006_trainingset_uuid... OK
  Applying dvaapp.0007_auto_20180120_2359... OK
  Applying dvaapp.0008_auto_20180129_0719... OK
  Applying dvaapp.0009_video_stream... OK
  Applying dvaapp.0010_remove_video_youtube_video... OK
  Applying dvaapp.0011_auto_20180309_0732... OK
  Applying dvaapp.0012_auto_20180309_0755... OK
  Applying dvaapp.0013_export... OK
  Applying dvaui.0001_initial... OK
  Applying dvaui.0002_auto_20171216_0733... OK
  Applying dvaui.0003_storeddvapql_server... OK
  Applying sessions.0001_initial... OK
/usr/local/lib/python2.7/dist-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Failed to load GPU Faiss: No module named swigfaiss_gpu
Faiss falling back to CPU-only.
Cloning into 'VDN'...
Traceback (most recent call last):
  File "./init_fs.py", line 55, in <module>
    dm.download()
  File "/root/DVA/server/dvaapp/models.py", line 276, in download
    fs.get_path_to_file(m['url'],dlpath)
  File "/root/DVA/server/dvaapp/fs.py", line 175, in get_path_to_file
    r = requests.get(path + '?dl=1')
  File "/usr/local/lib/python2.7/dist-packages/requests/api.py", line 72, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/adapters.py", line 508, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='www.dropbox.com', port=443): Max retries exceeded with url: /s/nzz26b2p4wxygg3/coco_mobilenet.pb?dl=1 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f9c19fcfa10>: Failed to establish a new connection: [Errno 111] Connection refused',))
Traceback (most recent call last):
  File "./start_container.py", line 17, in <module>
    subprocess.check_call(['./init_fs.py', ])
  File "/usr/lib/python2.7/subprocess.py", line 541, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['./init_fs.py']' returned non-zero exit status 1

The output of `docker ps -a` is:
➜  cpu docker-compose ps
  Name                 Command               State                     Ports
---------------------------------------------------------------------------------------------
dva-pg      docker-entrypoint.sh postgres    Up       5432/tcp
dva-redis   /app-entrypoint.sh /run.sh       Up       6379/tcp
dva-rmq     docker-entrypoint.sh rabbi ...   Up       25672/tcp, 4369/tcp, 5671/tcp, 5672/tcp
webserver   bash -c git reset --hard & ...   Exit 1

Could you help to look into what has happened, and looking forward to your reply.
Thanks!

**Comment by AKSHAYUBHAT** [comment]
It appears that the code cannot download model weights from Dropbox.
```
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='www.dropbox.com', port=443): Max retries exceeded with url: /s/nzz26b2p4wxygg3/coco_mobilenet.pb?dl=1 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f9c19fcfa10>: Failed to establish a new connection: [Errno 111] Connection refused',))
```

**Comment by AKSHAYUBHAT** [comment]
Also use `./manage.py start cpu` instead of using manual docker-compose up.
