### ISSUE TITLE
How to solve the result identified by CTPN can‘t directly input to CRNN？

### ISSUE THREAD

**Issue by atVoidYX** [AKSHAYUBHAT/DeepVideoAnalytics#164]
Both CTPN and CRNN have their own datasets to test in the paper.
The dataset of CRNN  is made up of picture of a single word like “apple”  ，“eat” ， “you”.
But the results identified by CTPN usualy are  continuous sentences like “you eat apple” , CRNN doean’t have good performance.
Do you have some advice?

**Comment by AKSHAYUBHAT** [comment]
I recommend using EAST which is better at handling this. I have not integrated it since it has an incompatible license, but it's performance is superior to that of CTPN implementation  and pre-trained network. 

https://github.com/AKSHAYUBHAT/EAST
