### ISSUE TITLE
duplicate key value violates unique constraint "dvaapp_trainedmodel_shasum_key"

### ISSUE THREAD

**Issue by xueminghui** [AKSHAYUBHAT/DeepVideoAnalytics#175]
# Checklist for submitting an issue 

- Have you verified that docker is installed correctly and e.g. GFW is not preventing downloads?
no problem

- Which docker-compose.yml file are you using?
/DeepVideoAnalytics/deploy/compose/cpu/docker-compose.yml

- Please post output of `docker ps -a` or confirm that all containers are running?
CONTAINER ID        IMAGE                         COMMAND                  CREATED             STATUS                     PORTS                                NAMES
8df46f2231ea        akshayubhat/dva-auto:latest   "bash -c 'git rese..."   4 minutes ago       Exited (1) 3 minutes ago                                        webserver
043bc01007e3        rabbitmq                      "docker-entrypoint..."   4 minutes ago       Up 4 minutes               4369/tcp, 5671-5672/tcp, 25672/tcp   dva-rmq
14ebac1dd44a        postgres:9.6.6                "docker-entrypoint..."   4 minutes ago       Up 4 minutes               5432/tcp                             dva-pg
38c3cc21d4cf        bitnami/redis:latest          "/app-entrypoint.s..."   4 minutes ago       Up 4 minutes               6379/tcp                             dva-redis
54aa174e197e        7685a87d56b4                  "/run_jupyter.sh -..."   6 days ago          Exited (0) 6 days ago                                           zen_carson
18da6313a150        7685a87d56b4                  "/run_jupyter.sh -..."   6 days ago          Exited (0) 6 days ago                                           flamboyant_babbage

- If a specific container is not running or "exited" please post output of `docker logs <name of the container>`
webserver | WARNING:root:Could not import indexer / clustering assuming running in front-end mode
webserver | Operations to perform:
webserver |   Apply all migrations: admin, auth, authtoken, contenttypes, django_celery_beat, django_celery_results, dvaapp, dvaui, sessions
webserver | Running migrations:
webserver |   Applying dvaapp.0024_auto_20180605_0019... OK
webserver | /usr/local/lib/python2.7/dist-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
webserver |   from ._conv import register_converters as _register_converters
dva-pg    | ERROR:  duplicate key value violates unique constraint "dvaapp_trainedmodel_shasum_key"
dva-pg    | DETAIL:  Key (shasum)=(48b026cf77dfbd5d9841cca3ee550ef0ee5a0751) already exists.
dva-pg    | STATEMENT:  INSERT INTO "dvaapp_trainedmodel" ("detector_type", "mode", "model_type", "name", "algorithm", "shasum", "model_filename", "created", "arguments", "event_id", "trained", "training_set_id", "url", "files", "produces_labels", "produces_json", "produces_text", "parent_id", "uuid") VALUES (NULL, 'T', 'I', 'inception', '', '48b026cf77dfbd5d9841cca3ee550ef0ee5a0751', '', '2018-06-05T00:19:34.216068+00:00'::timestamptz, '{"components": 2048}', NULL, false, NULL, '', '[{"url": "https://www.dropbox.com/s/fc7li2vwn8lvsyu/network.pb", "filename": "network.pb"}]', false, false, false, NULL, 'd698fd94-b3ed-4668-908f-3ecd9b74ddab'::uuid) RETURNING "dvaapp_trainedmodel"."id"
dva-pg    | ERROR:  duplicate key value violates unique constraint "dvaapp_trainedmodel_shasum_key"
dva-pg    | DETAIL:  Key (shasum)=(9f99caccbc75dcee8cb0a55a0551d7c5cb8a6836) already exists.
dva-pg    | STATEMENT:  INSERT INTO "dvaapp_trainedmodel" ("detector_type", "mode", "model_type", "name", "algorithm", "shasum", "model_filename", "created", "arguments", "event_id", "trained", "training_set_id", "url", "files", "produces_labels", "produces_json", "produces_text", "parent_id", "uuid") VALUES (NULL, 'T', 'I', 'facenet', '', '9f99caccbc75dcee8cb0a55a0551d7c5cb8a6836', '', '2018-06-05T00:19:34.228209+00:00'::timestamptz, '{"components": 128}', NULL, false, NULL, '', '[{"url": "https://www.dropbox.com/s/jytpgw8et09ede9/facenet.pb", "filename": "facenet.pb"}]', false, false, false, NULL, '16badce9-aad6-44d4-b768-acc20924dca8'::uuid) RETURNING "dvaapp_trainedmodel"."id"
webserver | Traceback (most recent call last):
webserver |   File "./launch_from_env.py", line 22, in <module>
webserver |     queue_name = 'q_retriever_{}'.format(dm.pk)
webserver | AttributeError: 'NoneType' object has no attribute 'pk'
webserver | Traceback (most recent call last):
webserver |   File "./start_container.py", line 18, in <module>
webserver |     subprocess.check_call(['./launch_from_env.py','0'])
webserver |   File "/usr/lib/python2.7/subprocess.py", line 541, in check_call
webserver |     raise CalledProcessError(retcode, cmd)
webserver | subprocess.CalledProcessError: Command '['./launch_from_env.py', '0']' returned non-zero exit status 1

- Is your question about OCR blog post in notebooks/OCR/ ? 
no

**Comment by AKSHAYUBHAT** [comment]
Thanks for reporting, I am investigating. Can you try 

`./dvactl clean && ./dvactl start`
