### ISSUE TITLE
docker-compose.yml error

### ISSUE THREAD

**Issue by oscarmh** [AKSHAYUBHAT/DeepVideoAnalytics#18]
Hi, when executing docker-compose up get this error

ERROR: In file './docker-compose.yml' service 'version' doesn't have any configuration options. All top level keys in your docker-compose.yml must map to a dictionary of configuration options.

I already did the ./rebuild... what am I missing ? Thanks !!

**Comment by AKSHAYUBHAT** [comment]
You need to update docker-compose and maybe docker itself to latest version.

https://github.com/docker/compose/issues/3331

**Comment by oscarmh** [comment]
thanks go for it...

**Comment by oscarmh** [comment]
already done, double check.... l´m lost

**Comment by AKSHAYUBHAT** [comment]
is it the same error? are you using the /docker/ cpu version or /docker_GPU/ version.

**Comment by oscarmh** [comment]
using the CPU version teh /docker/ I did reinstall docker (instructions in docker.com), run the helloworld... working ! then the rebuild.sh that takes long time.  Only security warnings.. Docker list shows tensorflow/tensorflow and akshayubhat/dva but when I try again to run docker-compose up but the .yml fails. My machine is Ubuntu 16.04 clean install.....  any hint ? Thanks a lot.

**Comment by AKSHAYUBHAT** [comment]
1.  Try running `git status` to make sure that you have not mistakenly edited the docker-compose.yml. 
2. Make sure you are in correct directory (inside /docker ) when you run docker-compose-up
3. On linux machines there is typically conflict between the version of docker-compose depending on how you installed it.  Run `docker-compose --version` to make sure the version on the PATH is correct. [1]

[1] http://stackoverflow.com/questions/36934675/ubuntu-and-updating-docker

**Comment by oscarmh** [comment]
shame for me, /usr/local/bin different from /usr/bin.... thanks progressing now. Best regards.

**Comment by AKSHAYUBHAT** [comment]
assuming this was fixed.
