### ISSUE TITLE
Webserver issue in GPU mode

### ISSUE THREAD

**Issue by thesunkid19** [AKSHAYUBHAT/DeepVideoAnalytics#181]
It works well in CPU mode, but I don't know why it's not work in GPU mode.
After `./dvactl configure`  and `./dvactl start` steps work done. 
I wait for a while and check `docker ps -a` but webserver is exited, here is `docker logs webserver`:

> HEAD is now at 9e0a4f2 Merge pull request #177 from AKSHAYUBHAT/master
From https://github.com/akshayubhat/DeepVideoAnalytics
   201b31d..b29de6b  master     -> origin/master
Already up-to-date.
WARNING:root:Could not import Tensorflow assuming operating in either frontend or caffe/pytorch mode
WARNING:root:Could not import indexer / clustering assuming running in front-end mode
No changes detected
WARNING:root:Could not import Tensorflow assuming operating in either frontend or caffe/pytorch mode
WARNING:root:Could not import indexer / clustering assuming running in front-end mode
Operations to perform:
  Apply all migrations: admin, auth, authtoken, contenttypes, django_celery_beat, django_celery_results, dvaapp, dvaui, sessions
Running migrations:
  Applying contenttypes.0001_initial... OK
  Applying auth.0001_initial... OK
  Applying admin.0001_initial... OK
  Applying admin.0002_logentry_remove_auto_add... OK
  Applying contenttypes.0002_remove_content_type_name... OK
  Applying auth.0002_alter_permission_name_max_length... OK
  Applying auth.0003_alter_user_email_max_length... OK
  Applying auth.0004_alter_user_username_opts... OK
  Applying auth.0005_alter_user_last_login_null... OK
  Applying auth.0006_require_contenttypes_0002... OK
  Applying auth.0007_alter_validators_add_error_messages... OK
  Applying auth.0008_alter_user_username_max_length... OK
  Applying authtoken.0001_initial... OK
  Applying authtoken.0002_auto_20160226_1747... OK
  Applying django_celery_beat.0001_initial... OK
  Applying django_celery_beat.0002_auto_20161118_0346... OK
  Applying django_celery_beat.0003_auto_20161209_0049... OK
  Applying django_celery_beat.0004_auto_20170221_0000... OK
  Applying django_celery_results.0001_initial... OK
  Applying dvaapp.0001_initial... OK
  Applying dvaapp.custom_migration... OK
  Applying dvaapp.0001_auto_20180608_1651... OK
  Applying dvaapp.0002_hyperregionrelation_hypertuberegionrelation... OK
  Applying dvaapp.0003_auto_20180612_0610... OK
  Applying dvaapp.0004_remove_frame_subdir... OK
  Applying dvaapp.0005_auto_20180617_2110... OK
  Applying dvaapp.0006_remove_region_materialized... OK
  Applying dvaui.0001_initial... OK
  Applying dvaui.0002_auto_20171216_0733... OK
  Applying dvaui.0003_storeddvapql_server... OK
  Applying sessions.0001_initial... OK
Cloning into 'VDN'...
Traceback (most recent call last):
  File "./init_fs.py", line 109, in <module>
    init_process()
  File "./init_fs.py", line 74, in init_process
    get_path_to_file(path, "temp.json")
  File "/root/DVA/server/dvaapp/fs.py", line 214, in get_path_to_file
    raise NotImplementedError("Unknown file system {}".format(path))
NotImplementedError: Unknown file system 1
Traceback (most recent call last):
  File "./start_container.py", line 17, in <module>
    subprocess.check_call(['./init_fs.py', ])
  File "/usr/lib/python2.7/subprocess.py", line 541, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['./init_fs.py']' returned non-zero exit status 1

I run `docker-compose -f deploy/compose//docker-compose-1-gpus.yml up`, here is the result in webserver log:
> HEAD is now at 9e0a4f2 Merge pull request #177 from AKSHAYUBHAT/master
Already up-to-date.
WARNING:root:Could not import Tensorflow assuming operating in either frontend or caffe/pytorch mode
WARNING:root:Could not import indexer / clustering assuming running in front-end mode
No changes detected
WARNING:root:Could not import Tensorflow assuming operating in either frontend or caffe/pytorch mode
WARNING:root:Could not import indexer / clustering assuming running in front-end mode
Operations to perform:
  Apply all migrations: admin, auth, authtoken, contenttypes, django_celery_beat, django_celery_results, dvaapp, dvaui, sessions
Running migrations:
  No migrations to apply.
Traceback (most recent call last):
  File "./init_fs.py", line 109, in <module>
    init_process()
  File "./init_fs.py", line 74, in init_process
    get_path_to_file(path, "temp.json")
  File "/root/DVA/server/dvaapp/fs.py", line 214, in get_path_to_file
    raise NotImplementedError("Unknown file system {}".format(path))
NotImplementedError: Unknown file system 1
Traceback (most recent call last):
  File "./start_container.py", line 17, in <module>
    subprocess.check_call(['./init_fs.py', ])
  File "/usr/lib/python2.7/subprocess.py", line 541, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['./init_fs.py']' returned non-zero exit status 1

My server docker info:

>   Profile: default
Kernel Version: 4.4.0-127-generic
Operating System: Ubuntu 16.04.4 LTS
OSType: linux
Architecture: x86_64
CPUs: 24
Total Memory: 125.8GiB
Name: xxxxxx
ID: VORI:DGAU:S3JG:6OUP:LEDT:LSGU:ORNH:Q6CI:DHDT:SKPO:3RWX:3UPF
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

**Comment by AKSHAYUBHAT** [comment]
Hey with latest commit I was able to run it.

Just run `git pull && rm config.json && ./dvactl configure` select number of GPUs and dont change the init_process and init_models. 

After that you should be able to run `./dvactl start`.

Running on GPU's is tricky since you need to be a careful about memory allocation, you can inspect config.json which contains information about memory allocation and placement. 

Another thing that you need to ensure is that nvidia-docker2 is selected as  default docker run time. [1]

[1] https://github.com/NVIDIA/nvidia-docker/issues/568
