### ISSUE TITLE
Code Cloned from your repo, tried running the demo, but encountering errors, please help...

### ISSUE THREAD

**Issue by shrouti** [AKSHAYUBHAT/DeepVideoAnalytics#199]
Hi Akshay,

I cloned the code and now have it on my local drive. I am using windows 10 with python3.5x installed. I converted most of your code from python 2 to python 3. However getting the following issues when running as suggested in the docker virtual environment. Please help.
--------

Lenovo@LAPTOP-8LNUF9Q4 MINGW64 /e/Learning/DeepVideoAnalytics (master)
$ /c/Users/Lenovo/Anaconda3/python ./dvactl configure
Please select mode { dev, cpu, gpu, kube } >>cpu
Please specify init process or press enter to keep default ( configs/custom_defaults/init_process.json ) >>
Refresh docker images by pulling before start: Y/N , press enter to keep default (Y) >>
Please specify docker CPU image or press enter to keep default ( akshayubhat/dva-auto:latest ) >>
Please specify default models or press enter to keep default ( configs/custom_defaults/trained_models.json ) >>
Please specify upstream branch (stable, master, etc.) or press enter to keep default ( stable ) >>
C:\Users\Lenovo/aws.env not found. not passing AWS creds. Please create ~/aws.env with AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY or manually add them to credentials in config.json
C:\Users\Lenovo/do.env not found. not passing Digital Ocean creds.
Traceback (most recent call last):
  File "./dvactl", line 351, in <module>
    configure()
  File "./dvactl", line 307, in configure
    mode_dict = configure_compose(mode)
  File "./dvactl", line 293, in configure_compose
    return {"mode": mode, 'gpus': gpu_count, 'init_process': read_and_encode(init_process),
  File "./dvactl", line 228, in read_and_encode
    data = base64.b64encode(f.read())
  File "C:\Users\Lenovo\Anaconda3\lib\base64.py", line 58, in b64encode
    encoded = binascii.b2a_base64(s, newline=False)
TypeError: a bytes-like object is required, not 'str'

Lenovo@LAPTOP-8LNUF9Q4 MINGW64 /e/Learning/DeepVideoAnalytics (master)
$ /c/Users/Lenovo/Anaconda3/python ./dvactl start
Traceback (most recent call last):
  File "./dvactl", line 358, in <module>
    mode_dict = get_mode()
  File "./dvactl", line 19, in get_mode
    return json.load(file("config.json"))
NameError: name 'file' is not defined

--------

It would be good, if you can provide a step-by-step guide on how to do the installation and run the demo

Thanks,
Samir

**Comment by AKSHAYUBHAT** [comment]
Please use python 2.
