### ISSUE TITLE
jupyter-notebook error

### ISSUE THREAD

**Issue by oiovoyo** [AKSHAYUBHAT/DeepVideoAnalytics#20]
I install dva in docker, but i get some error in notebook as followed:

ImportError                               Traceback (most recent call last)
<ipython-input-12-51bc88c00c90> in <module>()
      2 from dvaapp.views import handle_uploaded_file, handle_youtube_video
      3 from dvaapp.models import Video
----> 4 from dvaapp.tasks import extract_frames, perform_indexing, perform_detection
      5 for fname in glob.glob('../../tests/ci/*.mp4'):
      6     name = fname.split('/')[-1].split('.')[0]

ImportError: cannot import name perform_indexing

In source code dvaapp.tasks, I can not find extract_frames, perform_indexing, perform_detection.

**Comment by AKSHAYUBHAT** [comment]
https://github.com/AKSHAYUBHAT/DeepVideoAnalytics/blob/master/fabfile.py#L154
See this for reference
I plan to add demo notebook soon.
