### ISSUE TITLE
Could not automatically determine credentials.

### ISSUE THREAD

**Issue by popey456963** [AKSHAYUBHAT/DeepVideoAnalytics#203]
![](https://femto.pw/m4sx.png)

Docker appears to be installed successfully,  I've used it a great deal in the past and it has functioned successfully throughout.  Trying to run it on a Ubuntu 16.04 machine in CPU mode, all other settings are the default.  I cloned from Github, am working on the stable branch, started it successfully.

What credentials does this require?  I followed the installation guide for a "single instance for dev, test and fixed-scale use" but it seems to not mention this.

List of containers:

```femto ~/deep-video-analytics :) > docker ps -a
CONTAINER ID        IMAGE                                  COMMAND                  CREATED             STATUS                     PORTS                                                        NAMES
089309ed9766        akshayubhat/dva-auto:latest            "bash -c 'git reset …"   5 minutes ago       Up 5 minutes               6006/tcp, 127.0.0.1:8000->80/tcp, 127.0.0.1:8889->8888/tcp   webserver
a369b76a1837        postgres:9.6.6                         "docker-entrypoint.s…"   5 minutes ago       Up 5 minutes               5432/tcp                                                     dva-pg
69dd79618cb8        bitnami/redis:latest                   "/entrypoint.sh /run…"   5 minutes ago       Up 5 minutes               6379/tcp                                                     dva-redis
92789d731c01        rabbitmq                               "docker-entrypoint.s…"   5 minutes ago       Up 5 minutes               4369/tcp, 5671-5672/tcp, 25672/tcp                           dva-rmq
```

**Comment by AKSHAYUBHAT** [comment]
Hi you can ignore this error.

it does not requires any credentials to be use.  

This error is thrown because when running in Kubernetes mode it will try to connect to GCS. I will add a line that will suppress the warning in non Kube / fixed scale mode.

**Comment by AKSHAYUBHAT** [comment]
Fixed in a recent commit

**Comment by popey456963** [comment]
Thanks for the quick fix and making this website, has been exceptionally useful!
