### ISSUE TITLE
do.env not found. not passing Digital Ocean creds

### ISSUE THREAD

**Issue by rastinrastini** [AKSHAYUBHAT/DeepVideoAnalytics#207]
Hi
i download files and move to repos/model/ directory
mode is dev
for other only click enter
for "specify path to init models.json...": configs/custom_defaults/trained_models_local.json

but give me error:
"/home/rastin/aws.env not found. not passing AWS creds. Please create ~/aws.env with AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY or manually add them to credentials in config.json
/home/rastin/do.env not found. not passing Digital Ocean creds.
Saved config.json"

how can correct?
Thanks

**Comment by AKSHAYUBHAT** [comment]
Hi You can optionally provide aws and digital ocean credentials if you plan to export import from S3 and/or Digital Ocean spaces. The above message is not an error but rather just a warning to users that no credentials are being passed and you can just ignore it.  I will try to reword the message such that it does not seems like an error.

**Comment by rastinrastini** [comment]
thanks but what about this error?
![image](https://user-images.githubusercontent.com/7768900/45278357-f07a7a80-b4e1-11e8-95b7-6c35baac804a.png)

**Comment by AKSHAYUBHAT** [comment]
Fixed in latest commit.
