### ISSUE TITLE
could not find env file

### ISSUE THREAD

**Issue by rastinrastini** [AKSHAYUBHAT/DeepVideoAnalytics#208]
Hi
how correct this error?
"Couldn't find env file: /home/rastin/Desktop/projects/visual_search_2/deep2/deepvideoanalytics/custom.env"
![image](https://user-images.githubusercontent.com/7768900/45279969-ece9f200-b4e7-11e8-8f1d-82a66a6ccd34.png)

**Comment by AKSHAYUBHAT** [comment]
Oh this happened because you are trying to run `./dvactl clean` before starting for the first time. 
Just `./dvactl start` is fine, since it will create custom.env. if you attempt to clean it before starting there isn't a running environment (and a custom.env ) to stop.
