### ISSUE TITLE
libdc1394 error

### ISSUE THREAD

**Issue by oiovoyo** [AKSHAYUBHAT/DeepVideoAnalytics#21]
in docker I get this error:
 libdc1394 error: Failed to initialize libdc1394

**Comment by AKSHAYUBHAT** [comment]
Yeah ignore that its just quirk of OpenCV

**Comment by AKSHAYUBHAT** [comment]
http://stackoverflow.com/questions/12689304/ctypes-error-libdc1394-error-failed-to-initialize-libdc1394
