### ISSUE TITLE
When everything is well, but I can't visit webserver, here is my webserver logs, please help me!

### ISSUE THREAD

**Issue by apersonw** [AKSHAYUBHAT/DeepVideoAnalytics#210]
When I visit "http://localhost:8000", response is empty!

running build_ext
building 'lib.utils.bbox' extension
creating build
creating build/temp.linux-x86_64-2.7
x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -Wdate-time -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC -I/usr/include/python2.7 -c bbox.c -o build/temp.linux-x86_64-2.7/bbox.o
In file included from /usr/include/python2.7/numpy/ndarraytypes.h:1777:0,
                 from /usr/include/python2.7/numpy/ndarrayobject.h:18,
                 from /usr/include/python2.7/numpy/arrayobject.h:4,
                 from bbox.c:567:
/usr/include/python2.7/numpy/npy_1_7_deprecated_api.h:15:2: warning: #warning "Using deprecated NumPy API, disable it by " "#defining NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-Wcpp]
 #warning "Using deprecated NumPy API, disable it by " \
  ^
creating /root/DVA/repos/tf_ctpn_cpu/lib/utils/lib
creating /root/DVA/repos/tf_ctpn_cpu/lib/utils/lib/utils
x86_64-linux-gnu-gcc -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-Bsymbolic-functions -Wl,-z,relro -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -Wdate-time -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -Wl,-Bsymbolic-functions -Wl,-z,relro -Wdate-time -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security build/temp.linux-x86_64-2.7/bbox.o -o /root/DVA/repos/tf_ctpn_cpu/lib/utils/lib/utils/bbox.so
building 'lib.utils.cython_nms' extension
x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -Wdate-time -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC -I/usr/include/python2.7 -c cython_nms.c -o build/temp.linux-x86_64-2.7/cython_nms.o
In file included from /usr/include/python2.7/numpy/ndarraytypes.h:1777:0,
                 from /usr/include/python2.7/numpy/ndarrayobject.h:18,
                 from /usr/include/python2.7/numpy/arrayobject.h:4,
                 from cython_nms.c:567:
/usr/include/python2.7/numpy/npy_1_7_deprecated_api.h:15:2: warning: #warning "Using deprecated NumPy API, disable it by " "#defining NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-Wcpp]
 #warning "Using deprecated NumPy API, disable it by " \
  ^
x86_64-linux-gnu-gcc -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-Bsymbolic-functions -Wl,-z,relro -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -Wdate-time -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -Wl,-Bsymbolic-functions -Wl,-z,relro -Wdate-time -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security build/temp.linux-x86_64-2.7/cython_nms.o -o /root/DVA/repos/tf_ctpn_cpu/lib/utils/lib/utils/cython_nms.so
Collecting django-debug-toolbar
  Downloading https://files.pythonhosted.org/packages/97/c6/523fc2ca98119d21c709bbc47217b1d5fd17c6f9449ef32490889363d97d/django_debug_toolbar-1.10.1-py2.py3-none-any.whl (207kB)
Collecting sqlparse>=0.2.0 (from django-debug-toolbar)
  Downloading https://files.pythonhosted.org/packages/65/85/20bdd72f4537cf2c4d5d005368d502b2f464ede22982e724a82c86268eda/sqlparse-0.2.4-py2.py3-none-any.whl
Requirement already satisfied: Django>=1.11 in /usr/local/lib/python2.7/dist-packages (from django-debug-toolbar) (1.11.3)
Requirement already satisfied: pytz in /usr/local/lib/python2.7/dist-packages (from Django>=1.11->django-debug-toolbar) (2018.5)
Installing collected packages: sqlparse, django-debug-toolbar
Successfully installed django-debug-toolbar-1.10.1 sqlparse-0.2.4
WARNING:root:Could not import indexer / clustering assuming running in front-end mode
Migrations for 'dvaapp':
  dvaapp/migrations/0001_initial.py
    - Create model DeletedVideo
    - Create model DVAPQL
    - Create model Export
    - Create model Frame
    - Create model HyperRegionRelation
    - Create model HyperTubeRegionRelation
    - Create model IndexEntries
    - Create model ManagementAction
    - Create model QueryRegion
    - Create model QueryResult
    - Create model Region
    - Create model RegionRelation
    - Create model Retriever
    - Create model Segment
    - Create model SystemState
    - Create model TaskRestart
    - Create model TEvent
    - Create model TrainedModel
    - Create model TrainingSet
    - Create model Tube
    - Create model TubeRegionRelation
    - Create model TubeRelation
    - Create model Video
    - Create model Worker
    - Add field video to tuberelation
    - Add field video to tuberegionrelation
    - Add field video to tube
    - Add field training_set to trainedmodel
    - Add field training_set to tevent
    - Add field video to tevent
    - Add field worker to tevent
    - Add field event to segment
    - Add field video to segment
    - Add field event to regionrelation
    - Add field source_region to regionrelation
    - Add field target_region to regionrelation
    - Add field video to regionrelation
    - Add field event to region
    - Add field user to region
    - Add field video to region
    - Add field region to queryresult
    - Add field retrieval_event to queryresult
    - Add field tube to queryresult
    - Add field video to queryresult
    - Add field event to queryregion
    - Add field query to queryregion
    - Add field event to indexentries
    - Add field video to indexentries
    - Add field event to hypertuberegionrelation
    - Add field tube to hypertuberegionrelation
    - Add field video to hypertuberegionrelation
    - Add field event to hyperregionrelation
    - Add field region to hyperregionrelation
    - Add field video to hyperregionrelation
    - Add field event to frame
    - Add field video to frame
    - Add field event to export
    - Alter unique_together for tuberelation (1 constraint(s))
    - Alter unique_together for tuberegionrelation (1 constraint(s))
    - Alter unique_together for tube (1 constraint(s))
    - Alter unique_together for segment (1 constraint(s))
    - Alter unique_together for regionrelation (1 constraint(s))
    - Alter unique_together for region (1 constraint(s))
    - Alter unique_together for hypertuberegionrelation (1 constraint(s))
    - Alter unique_together for hyperregionrelation (1 constraint(s))
    - Alter unique_together for frame (1 constraint(s))
WARNING:root:Could not import indexer / clustering assuming running in front-end mode
Operations to perform:
  Apply all migrations: admin, auth, authtoken, contenttypes, django_celery_beat, django_celery_results, dvaapp, dvaui, sessions
Running migrations:
  Applying contenttypes.0001_initial... OK
  Applying auth.0001_initial... OK
  Applying admin.0001_initial... OK
  Applying admin.0002_logentry_remove_auto_add... OK
  Applying contenttypes.0002_remove_content_type_name... OK
  Applying auth.0002_alter_permission_name_max_length... OK
  Applying auth.0003_alter_user_email_max_length... OK
  Applying auth.0004_alter_user_username_opts... OK
  Applying auth.0005_alter_user_last_login_null... OK
  Applying auth.0006_require_contenttypes_0002... OK
  Applying auth.0007_alter_validators_add_error_messages... OK
  Applying auth.0008_alter_user_username_max_length... OK
  Applying authtoken.0001_initial... OK
  Applying authtoken.0002_auto_20160226_1747... OK
  Applying django_celery_beat.0001_initial... OK
  Applying django_celery_beat.0002_auto_20161118_0346... OK
  Applying django_celery_beat.0003_auto_20161209_0049... OK
  Applying django_celery_beat.0004_auto_20170221_0000... OK
  Applying django_celery_results.0001_initial... OK
  Applying dvaapp.0001_initial... OK
  Applying dvaapp.custom_migration... OK
  Applying dvaui.0001_initial... OK
  Applying dvaui.0002_auto_20171216_0733... OK
  Applying dvaui.0003_storeddvapql_server... OK
  Applying sessions.0001_initial... OK
Cloning into 'VDN'...
ERROR:root:Retriever with name inception not found. Not launching worker.
ERROR:root:Retriever with name facenet not found. Not launching worker.
[I 01:55:37.511 NotebookApp] Writing notebook server cookie secret to /root/.local/share/jupyter/runtime/notebook_cookie_secret
[W 01:55:37.581 NotebookApp] WARNING: The notebook server is listening on all IP addresses and not using encryption. This is not recommended.
[I 01:55:37.606 NotebookApp] Serving notebooks from local directory: /root/DVA
[I 01:55:37.606 NotebookApp] 0 active kernels
[I 01:55:37.606 NotebookApp] The Jupyter Notebook is running at:
[I 01:55:37.606 NotebookApp] http://7960761518ee:8888/?token=5bef0563c4e758b82b3ce2cbbbae6403461bd6d14d0d4e44
[I 01:55:37.606 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 01:55:37.607 NotebookApp] 
    
    Copy/paste this URL into your browser when you connect for the first time,
    to login with a token:
        http://7960761518ee:8888/?token=5bef0563c4e758b82b3ce2cbbbae6403461bd6d14d0d4e44&token=5bef0563c4e758b82b3ce2cbbbae6403461bd6d14d0d4e44
WARNING: yacc table file version is out of date
WARNING: Assuming --restrict-filenames since file system encoding cannot encode all characters. Set the LC_ALL environment variable to fix this.
WARNING:root:Could not import indexer / clustering assuming running in front-end mode
/usr/local/lib/python2.7/dist-packages/celery/platforms.py:796: RuntimeWarning: You're running the worker with superuser privileges: this is
absolutely not recommended!

Please specify a different user using the --uid option.

User information: uid=0 euid=0 gid=0 egid=0

  uid=uid, euid=euid, gid=gid, egid=egid,
WARNING:root:Could not import indexer / clustering assuming running in front-end mode
WARNING:root:Could not import indexer / clustering assuming running in front-end mode
WARNING:root:Could not import indexer / clustering assuming running in front-end mode
WARNING:root:Could not import indexer / clustering assuming running in front-end mode
WARNING:root:Could not import indexer / clustering assuming running in front-end mode
WARNING:root:Could not import indexer / clustering assuming running in front-end mode
WARNING:root:Could not import indexer / clustering assuming running in front-end mode
WARNING:root:Could not import indexer / clustering assuming running in front-end mode
WARNING:root:Could not import indexer / clustering assuming running in front-end mode
WARNING:root:Could not import indexer / clustering assuming running in front-end mode
WARNING:root:Could not import indexer / clustering assuming running in front-end mode
WARNING:root:Could not import indexer / clustering assuming running in front-end mode
WARNING:root:Could not import indexer / clustering assuming running in front-end mode
/usr/local/lib/python2.7/dist-packages/celery/platforms.py:796: RuntimeWarning: You're running the worker with superuser privileges: this is
absolutely not recommended!

Please specify a different user using the --uid option.

User information: uid=0 euid=0 gid=0 egid=0

  uid=uid, euid=euid, gid=gid, egid=egid,
/usr/local/lib/python2.7/dist-packages/celery/platforms.py:796: RuntimeWarning: You're running the worker with superuser privileges: this is
absolutely not recommended!

Please specify a different user using the --uid option.

User information: uid=0 euid=0 gid=0 egid=0

  uid=uid, euid=euid, gid=gid, egid=egid,
/usr/local/lib/python2.7/dist-packages/celery/platforms.py:796: RuntimeWarning: You're running the worker with superuser privileges: this is
absolutely not recommended!

Please specify a different user using the --uid option.

User information: uid=0 euid=0 gid=0 egid=0

  uid=uid, euid=euid, gid=gid, egid=egid,
/usr/local/lib/python2.7/dist-packages/celery/platforms.py:796: RuntimeWarning: You're running the worker with superuser privileges: this is
absolutely not recommended!

Please specify a different user using the --uid option.

User information: uid=0 euid=0 gid=0 egid=0

  uid=uid, euid=euid, gid=gid, egid=egid,
/usr/local/lib/python2.7/dist-packages/celery/platforms.py:796: RuntimeWarning: You're running the worker with superuser privileges: this is
absolutely not recommended!

Please specify a different user using the --uid option.

User information: uid=0 euid=0 gid=0 egid=0

  uid=uid, euid=euid, gid=gid, egid=egid,
/usr/local/lib/python2.7/dist-packages/celery/platforms.py:796: RuntimeWarning: You're running the worker with superuser privileges: this is
absolutely not recommended!

Please specify a different user using the --uid option.

User information: uid=0 euid=0 gid=0 egid=0

  uid=uid, euid=euid, gid=gid, egid=egid,
/usr/local/lib/python2.7/dist-packages/celery/platforms.py:796: RuntimeWarning: You're running the worker with superuser privileges: this is
absolutely not recommended!

Please specify a different user using the --uid option.

User information: uid=0 euid=0 gid=0 egid=0

  uid=uid, euid=euid, gid=gid, egid=egid,
/usr/local/lib/python2.7/dist-packages/celery/platforms.py:796: RuntimeWarning: You're running the worker with superuser privileges: this is
absolutely not recommended!

Please specify a different user using the --uid option.

User information: uid=0 euid=0 gid=0 egid=0

  uid=uid, euid=euid, gid=gid, egid=egid,
/usr/local/lib/python2.7/dist-packages/celery/platforms.py:796: RuntimeWarning: You're running the worker with superuser privileges: this is
absolutely not recommended!

Please specify a different user using the --uid option.

User information: uid=0 euid=0 gid=0 egid=0

  uid=uid, euid=euid, gid=gid, egid=egid,
/usr/local/lib/python2.7/dist-packages/celery/platforms.py:796: RuntimeWarning: You're running the worker with superuser privileges: this is
absolutely not recommended!

Please specify a different user using the --uid option.

User information: uid=0 euid=0 gid=0 egid=0

  uid=uid, euid=euid, gid=gid, egid=egid,
/usr/local/lib/python2.7/dist-packages/celery/platforms.py:796: RuntimeWarning: You're running the worker with superuser privileges: this is
absolutely not recommended!

Please specify a different user using the --uid option.

User information: uid=0 euid=0 gid=0 egid=0

  uid=uid, euid=euid, gid=gid, egid=egid,
/usr/local/lib/python2.7/dist-packages/celery/platforms.py:796: RuntimeWarning: You're running the worker with superuser privileges: this is
absolutely not recommended!

Please specify a different user using the --uid option.

User information: uid=0 euid=0 gid=0 egid=0

  uid=uid, euid=euid, gid=gid, egid=egid,
WARNING:root:Could not import indexer / clustering assuming running in front-end mode
WARNING:root:Could not import indexer / clustering assuming running in front-end mode
/usr/local/lib/python2.7/dist-packages/celery/platforms.py:796: RuntimeWarning: You're running the worker with superuser privileges: this is
absolutely not recommended!

Please specify a different user using the --uid option.

User information: uid=0 euid=0 gid=0 egid=0

  uid=uid, euid=euid, gid=gid, egid=egid,
[14/Sep/2018 01:56:38] "GET / HTTP/1.1" 302 0
[14/Sep/2018 01:56:38] "GET /accounts/login/?next=/ HTTP/1.1" 200 16206
[14/Sep/2018 01:57:14] "GET / HTTP/1.1" 302 0

**Comment by apersonw** [comment]
My machine configuration
Operating system Ubuntu Server 16.04.1 LTS 64-bit
CPU 28 core
Memory 56 GB
Public network bandwidth 100 Mbps

**Comment by AKSHAYUBHAT** [comment]
[14/Sep/2018 01:56:38] "GET / HTTP/1.1" 302 0
[14/Sep/2018 01:56:38] "GET /accounts/login/?next=/ HTTP/1.1" 200 16206
[14/Sep/2018 01:57:14] "GET / HTTP/1.1" 302 0

From above entries It appears that the webserver is serving the request correctly and should show you the login page along with default username and password. 

Maybe there is some browser issue preventing you from accessing the page?

You can try running “wget http://localhost:8000” and examine index.html

**Comment by apersonw** [comment]
thanks for help me! The problem is that I didn't expose the server port!
