### ISSUE TITLE
when i upload a video.

### ISSUE THREAD

**Issue by jackylee1** [AKSHAYUBHAT/DeepVideoAnalytics#213]
IOError at /
[Errno 28] No space left on device
Request Method:	POST
Request URL:	http://localhost:8000/
Django Version:	1.11.3
Exception Type:	IOError
Exception Value:	
[Errno 28] No space left on device
Exception Location:	/root/DVA/server/dvaui/view_shared.py in handle_uploaded_file, line 145
Python Executable:	/usr/bin/python
Python Version:	2.7.12
Python Path:	
['/root/DVA/server',
 '/root/thirdparty/faiss/python',
 '/root/DVA/repos/tf_ctpn_cpu',
 '/root/DVA/repos',
 '/root/DVA/server',
 '/usr/lib/python2.7',
 '/usr/lib/python2.7/plat-x86_64-linux-gnu',
 '/usr/lib/python2.7/lib-tk',
 '/usr/lib/python2.7/lib-old',
 '/usr/lib/python2.7/lib-dynload',
 '/usr/local/lib/python2.7/dist-packages',
 '/usr/local/lib/python2.7/dist-packages/lopq-1.0.3199-py2.7.egg',
 '/usr/local/lib/python2.7/dist-packages/dlib-19.15.0-py2.7-linux-x86_64.egg',
 '/usr/lib/python2.7/dist-packages',
 '/usr/lib/python2.7/dist-packages/PILcompat',
 '/root/DVA/server',
 u'/root/DVA/server/dvaapp/../../client/',
 '/usr/local/lib/python2.7/dist-packages/IPython/extensions',
 '/root/DVA/server/dvalib/../../repos/',
 '/root/thirdparty/faiss/python']
Server time:	Fri, 21 Sep 2018 02:29:56 +0000
Traceback Switch to copy-and-paste view

**Comment by jackylee1** [comment]
are there any differences between cpu mode and dev mode?

**Comment by AKSHAYUBHAT** [comment]
Dev modes uses a /tmp to store files thus limited by size of your RAM. While CPU mode uses disk.
