### ISSUE TITLE
indexing-related failures / "perform_index_approximation" / "could not read index file ..."

### ISSUE THREAD

**Issue by tee-vee** [AKSHAYUBHAT/DeepVideoAnalytics#215]
Hi,
Running DVA latest locally on Ubuntu 16.04 server, GPU mode (two Tesla P100s), 128GB memory, lots of disk storage, no kubernetes. Docker/Nvidia-docker version 18.06.1-ce, build e68fc7a

Issue:
 - Uploaded a (checked/working) MP4 (video: AVC/ audio: AAC) file. (length: 1h, on-disk: 451MB)
 - Under Web UI->Tasks, failures reported in the "perform_index_approximation" operation in the "qglobal_model" queue (count: 64).
 - Narrowed down to one model (id: `54d36514-66b6-452c-b4d8-30c04b7592b0`) 
 - Would like to understand a little more about what this failure means, if the failure is critical how to fix, and how to prevent it in the future. 

Many, many thanks for your help!
-Derek

Additional info:
 - Details were identical (didn't check all 64; just randomly sampled):
 - Traceback:
` File "/root/DVA/server/dvalib/approximator.py", line 113, in load
    raise ValueError("Could not read index file {}".format(self.index_path))
ValueError: Could not read index file /root/media/models/54d36514-66b6-452c-b4d8-30c04b7592b0/faiss.index`
 - Arguments:
 `{u'trainedmodel_selector': {u'shasum': u'5e4b86a0267255426834396a5a855f4fa775691a'}, u'target': u'index_entries', u'filters': {u'event_id': u'85cc2eb6-1b97-471d-94f9-f7abf1b7abf6'}}`
 - Parent task "perform_indexing" (queue: "q_model_5") indicates "Completed" 
 - the "compose_global_model" container reports 
`[2018-10-03 08:14:00,234: ERROR/MainProcess] Task perform_index_approximation[604c21ec-22ae-430f-a762-6e7f96379617] raised unexpected: ValueError('Could not read index file /root/media/models/54d36514-66b6-452c-b4d8-30c04b7592b0/faiss.index',),
ValueError: Could not read index file /root/media/models/54d36514-66b6-452c-b4d8-30c04b7592b0/faiss.index,`
 - oddly I wasn't able to traceback the id `54d36514-66b6-452c-b4d8-30c04b7592b0` in `dva-pg` container logs

- Which docker-compose.yml file are you using?
`docker-compose-2-gpus.yaml`

- Please post output of `docker ps -a` or confirm that all containers are running?
`IMAGE                            STATUS         PORTS                                                    NAMES`
`/dva-auto:gpu         Up 4 days      80/tcp, 6006/tcp, 8888/tcp                               compose_textbox_1`
`/dva-auto:gpu         Up 4 days      80/tcp, 6006/tcp, 8888/tcp                               compose_facenet_1`
`/dva-auto:gpu         Up 4 days      80/tcp, 6006/tcp, 8888/tcp                               compose_global-model_1`
`/dva-auto:latest      Up 4 days      6006/tcp, x.x.x.x:8888->8888/tcp, x.x.x.x:8000->80/tcp   webserver`
`/dva-auto:latest      Up 4 days      80/tcp, 6006/tcp, 8888/tcp                               compose_tagger_1`
`/dva-auto:gpu         Up 4 days      80/tcp, 6006/tcp, 8888/tcp                               compose_coco_1`
`/dva-auto:gpu         Up 4 days      80/tcp, 6006/tcp, 8888/tcp                               compose_face_1`
`/dva-auto:latest      Up 4 days      80/tcp, 6006/tcp, 8888/tcp                               compose_non-gpu-workers_1`
`/dva-auto:gpu         Up 4 days      80/tcp, 6006/tcp, 8888/tcp                               compose_inception_1`
`/dva-auto:gpu         Up 4 days      80/tcp, 6006/tcp, 8888/tcp                               compose_crnn_1`
`postgres:9.6.6                   Up 4 days      5432/tcp                                                 dva-pg`
`rabbitmq                         Up 4 days      4369/tcp, 5671-5672/tcp, 25672/tcp                       dva-rmq`
`/redis:latest             Up 4 days      6379/tcp                                                 dva-redis`
 - If a specific container is not running or "exited" post output of `docker logs <name of container>`
None.

- Is your question about OCR blog post in notebooks/OCR? 
No

**Comment by tee-vee** [comment]
> ```
> shasum faiss.index 
> 5e4b86a0267255426834396a5a855f4fa775691a  faiss.index
> ```
> In your case the model was not correctly downloaded, which can happens for several reasons. I will check if there is any bug where model files are not downloaded correctly in GPU mode. But this can also happen if there is any error while downloading file from Digital Ocean Spaces.

Hi, I appreciate your (very prompt!) response!

I checked within the container and the file `/root/media/models/54d36514-66b6-452c-b4d8-30c04b7592b0/faiss.index` does exist with the expected checksum. 
Just in case, I moved aside the existing faiss.index and put in a _fresh_ (checksum verified) copy.

Unfortunately, the problem persists. 

However, I did all the steps inside the _compose_ container (docker exec -it compose_global-model-1 /bin/bash); should I have used the WebUI? If so, kindly advise the proper procedure as you'd like me to perform it. 

Just to recap for my sanity:
So there exists the correct file, with the expected checksums. 
However, we observe "Task 9eb65efd... running perform_index_approximation on qglobal_model under process 36" fails with:
`File "/root/DVA/server/dvalib/approximator.py", line 113, in load
    raise ValueError("Could not read index file {}".format(self.index_path))
ValueError: Could not read index file /root/media/models/54d36514-66b6-452c-b4d8-30c04b7592b0/faiss.index`

All the while, 
`# docker exec -it compose_global-model_1 shasum /root/media/models/54d36514.../faiss.index`
`5e4b86a0267255426834396a5a855f4fa775691a  /root/media/models/54d36514.../faiss.index`

Any suggestions?

Many thanks,
Derek

**Comment by tee-vee** [comment]
Oy, facing a non-sensical problem seemingly requires an equally non-sensical solution: 
`./dvactl stop ; sleep 10 ; ./dvactl start`

Three test videos -- no failures! 
Just submitted a real video ... early signs are positive.

Let's chalk this up to cosmic rays and close this case. 

Many thanks,
Derek

**Comment by AKSHAYUBHAT** [comment]
Can you enter a shell into the container and manually try to read the index? 

```
docker exec -it compose_global-model_1 bash
python manage.py shell
import faiss
faiss.read_index('/root/media/models/54d36514-66b6-452c-b4d8-30c04b7592b0/faiss.index')
```

It's also possible that the container you are using has not been updated with latest change in stable branch. This would cause index not load.
