### ISSUE TITLE
Gateway time-out / celery segfault

### ISSUE THREAD

**Issue by tee-vee** [AKSHAYUBHAT/DeepVideoAnalytics#217]
Hi, 

Running DVA latest locally on Ubuntu 16.04 server, GPU mode (two Tesla P100s), 128GB memory, lots of disk storage, no kubernetes. Docker/Nvidia-docker version 18.06.1-ce, build e68fc7a
Configured for gpu mode with two gpu; stable branch. Fresh instance, git-cloned 24h ago.
Only mod is in deploy/compose/gpu_skeleton.yaml:
```
     ports:
       - "0.0.0.0:8000:80"
       - "0.0.0.0:8888:8888"
```

Yesterday I added five MP4 video files yesterday morning (720p/1080p / 5min-90min / 20MB to 300MB). I had previously added these files in a separate DVA instance without any problems.
 
This morning, attempts to load web UI result in "504 Gateway Time-out".

I found this in the webserver container kernel log:
`celery[222220]: segfault at 0 ip 00007f46ce66a6bc sp 00007f45e57f8530 error 4 in _pywrap_tensorflow_internal.so[7f46c9ac3000+205a9000]`

Other odd symptoms are:
- running `python tests/test_ci_client.py` returns normal results --> _Seems like REST API is operational_
- there appears to be three specific celery threads consuming lots of cpu 
Parent: `  │   │   │   │           ├─python,93073 ./startq.py qextract 1  `
Child: `   │   │   │   │           │   └─celery,94041 /usr/local/bin/celery -A dva worker -l info -c 4 -Q qextract -n qextract.%h`

Stackoverflow says: 

> Install python-amqp package and remove python-librabbitmq
(From https://stackoverflow.com/a/23784451)

or

> [...] it was solved after deleting .celerybeat file.
(From https://stackoverflow.com/a/10848338)

(With references to https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=736348#10)

I could make these changes, but wanted to check in with you first as those answers are 3+ years old. 

Not sure if this is related, but saw a bunch of errors in dva-rmq:
`{"product","py-amqp"},{"product_version","2.2.2"},[{"connection.blocked",true},{"authentication_failure_close",true},{"consumer_cancel_notify",true}`

Thoughts?

With gratitude,
Derek

# Checklist for submitting an issue 
- Have you verified that docker is installed correctly and e.g. GFW is not preventing downloads?
✅

- Which docker-compose.yml file are you using?
`docker-compose-2-gpus.yaml`

- Please post output of `docker ps -a` or confirm that all containers are running?
✅

- If a specific container is not running or "exited" please post output of `docker logs <name of the container>`
N/A

- Is your question about OCR blog post in notebooks/OCR/ ? 
No

**Comment by AKSHAYUBHAT** [comment]
> This morning, attempts to load web UI result in "504 Gateway Time-out".

Does this means that other containers were in running state when you ran `docker ps -a`? 
E.g. Celery runs in its own container and its failure (or Redis, Postgres) can cause entire system to go down. However other containers (workers and servers) can go down and be individually restarted using Docker. 

In case celery, postgres or redis are down you can "restart" the entire system `./dvactl stop && ./dvactl start`.  Note that DVA "preserves" state in volumes thus running `./dvactl stop` merely brings down containers but keeps volumes intact. 

I will check if there is anything that would prevent such restart.

**Comment by tee-vee** [comment]
> > This morning, attempts to load web UI result in "504 Gateway Time-out".
> 
> Does this means that other containers were in running state when you ran `docker ps -a`?
> E.g. Celery runs in its own container and its failure (or Redis, Postgres) can cause entire system to go down. However other containers (workers and servers) can go down and be individually restarted using Docker.

Correct - All containers are (/were) in running state. I didn't see any specific subsystem failures; 
Went as far as to individually probe each and every subsystem (postgres, redis, rabbitmq). 
 
> In case celery, postgres or redis are down you can "restart" the entire system `./dvactl stop && ./dvactl start`. Note that DVA "preserves" state in volumes thus running `./dvactl stop` merely brings down containers but keeps volumes intact.

So there's been no problems restarting (using ./dvactl stop && ./dvactl start). 

I don't (yet) have a good handle on the stack; looking in `nginx/error.log` I see:
`2018/10/09 07:47:19 [error] 291#291: *1 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 192.168.y, server: *.*, request: "GET / HTTP/1.1", upstream: "uwsgi://unix:/tmp/app.sock", host: "192.168.x:8000"`

I was thinking ... "well, looks like your typical socket-timeout issue" so I'm aimlessly trying out varying socket-timeout related options... At the moment I've broken nginx as it is now stuck trying to start. Could you kindly point me in the right direction?


Many thanks,
Derek

**Comment by AKSHAYUBHAT** [comment]
From the description it appears that the webserver is hanging, I am not sure why this would happen, e.g. a query to the postgres server is taking too long. etc. You can manually view the webserver logs by going into a shell inside the webserver container and looking at supervisor logs which I think are stored in /var/tmp/ etc. that can provide a clue as to why nginx is timing out.
