### ISSUE TITLE
subprocess.CalledProcessError:  returned non-zero exit status 1

### ISSUE THREAD

**Issue by helium390** [AKSHAYUBHAT/DeepVideoAnalytics#218]
When I'm trying to modify the file configs/custom_defaults/traied_models.json (lines 102-120) I'm getting error: 
```
Error response from daemon: Container 9ede8565b7c8775620e3d70b31a843ca5af4777a8095a8fecbfde4b75563cc56 is not running
Traceback (most recent call last):
  File "./dvactl", line 397, in <module>
    gpu_image=mode_dict['gpu_image'])
  File "/home/smotiuser/DeepVideoAnalytics/deploy/compose/__init__.py", line 198, in handle_compose_operations
    get_auth()
  File "/home/smotiuser/DeepVideoAnalytics/deploy/compose/__init__.py", line 169, in get_auth
    token = subprocess.check_output([DOCKER, "exec", "webserver", "scripts/generate_testing_token.py"]).strip()
  File "/home/smotiuser/anaconda3/envs/py2/lib/python2.7/subprocess.py", line 223, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
subprocess.CalledProcessError: Command '['docker', 'exec', 'webserver', 'scripts/generate_testing_token.py']' returned non-zero exit status 1
```
I want to use my own model (ctpn and crnn) for korean language. How can I solve it?

**Comment by helium390** [comment]
I found my mistake.
When I'm using my own CTPN model it doesn't detect textbox. 
The model works in local machine fine. But in DVA it doesn't. Can you explain what should I do.
The model was download without mistake. The DVA is working good, but without detecting textboxes.

**Comment by AKSHAYUBHAT** [comment]
The "dev" mode container runs a Jupyter notebook server inside the container, you can manually examine if the weights are downloaded correctly and if it runs.
