### ISSUE TITLE
docker issue

### ISSUE THREAD

**Issue by john15888** [AKSHAYUBHAT/DeepVideoAnalytics#22]
I am installing using the docker image under Ubuntu 16.04.2. Looks like there is an error for the server.
Please see attached file.
![error1](https://cloud.githubusercontent.com/assets/26845172/24583075/091c3b4c-16f4-11e7-8458-8e41abcb7572.PNG)

Also, if the install is successful, how do I try it out? (use a web page(which URL?) or  run the .PY files?)

Thanks.

**Comment by AKSHAYUBHAT** [comment]
Hi John, 
Can you do a `git pull` and try again. 
I fixed this bug and it should work now. 

Once the container is running you should be able to view the user interface by navigating to `localhost:8000` from any browser.

**Comment by john15888** [comment]
Thank you. It is working now.
