### ISSUE TITLE
How to solve the problem that the client cannot log in

### ISSUE THREAD

**Issue by chengfei211** [AKSHAYUBHAT/DeepVideoAnalytics#222]
Sorry to disturb you! I am now studying for your project, I am a novice, now just debugging good client, it is in the circumstance that did not interact with the server data, supposedly should be able to open, but I this client need password, lead to can't log in, so I want to ask what is the password, how to solve this problem

**Comment by AKSHAYUBHAT** [comment]
username and password is displayed on the page.
