### ISSUE TITLE
ERROR : Service 'dva' failed to build

### ISSUE THREAD

**Issue by umlen-B** [AKSHAYUBHAT/DeepVideoAnalytics#23]
Hey!
I am facing this error while running 'docker-compose up'  in my Ubuntu 14.04 system. I have also tried this command using sudo but still same ERROR.
I even changed the Dockerfile : Run sudo apt-get update && apt-get install wget xz-utils, but still same error.
Wget is already installed in my system, so I tried commenting the above line in Docckerfile, but for next line "Run : wget some_html_link" is giving E: wget not found!
It would be great if anyone could help me with this.
Thanks in advance!

![error](https://cloud.githubusercontent.com/assets/13407561/24599802/84b1351a-186f-11e7-91fc-dba0a168f7c0.png)

**Comment by umlen-B** [comment]
I tried manually executing each command in the Dockerfie
Now "docker-compose up" gives this output : 
![docker](https://cloud.githubusercontent.com/assets/13407561/24612317/8fe8440e-18a2-11e7-8244-555bf223b608.png)
![docker2](https://cloud.githubusercontent.com/assets/13407561/24612319/96d9aa1e-18a2-11e7-9003-0a9cf7982bc4.png)

and now its stuck unless I press CTRL+C.
Please help!!

**Comment by AKSHAYUBHAT** [comment]
This is because  docker cannot conncect to internet due DNS setttings. 

See this for a fix.
http://askubuntu.com/questions/475764/docker-io-dns-doesnt-work-its-trying-to-use-8-8-8-8

**Comment by AKSHAYUBHAT** [comment]
You cannot just manually execute each line thats not how docker works. Each container is a seperate clean linux environment and those commands have to be executed inside that container.

**Comment by umlen-B** [comment]
After trying all these solution, the error is the same.
Docker is connected to internet when I write "docker login" and Username + Password, then output is : Login successful.

I'm under proxy and I have set the proxy in  /etc/default/docker as export http_proxy=uname:pass@proxy_ip:port
Also uncommented DOCKER_OPTS="--dns 8.8.8.8"

Is it because of the user, I am not the root user

**Comment by AKSHAYUBHAT** [comment]
Docker login is different (its merely a host os program) from docker container environment.

What's happening is that you are behind an organization network which prevents use of other DNS servers such as Googles 8.8.8.8 (which is used as default by docker). As a result you should find find the DNS servers used by your local network using

`nmcli dev show | grep 'IP4.DNS'`

Then edit following file with the correct DNS server & restart.

```
# /etc/docker/daemon.json
{
    "dns": ["<the dns allowed/used by your network>"]
}
```

**Comment by AKSHAYUBHAT** [comment]
https://github.com/docker/docker/issues/20394

**Comment by umlen-B** [comment]
I'm really sorry for bothering you.
I created the file /etc/docker/daemon.json and pasted the above lines in that file.
But when I restart the service : 
docker stop/waiting
start: Job failed to start
this is the output.

**Comment by umlen-B** [comment]
I have tried every possible solution.
1. updated /etc/default/docker
2. updated /etc/resolv.conf
3. tried commenting #dnsmasq
I don't know what to do more.
Please help!!

**Comment by AKSHAYUBHAT** [comment]
Since you can pull the images without any issue. You can just pull the docker image from docker hub using.
`
docker pull akshyaubhat/dva:cpu
`
https://hub.docker.com/r/akshayubhat/dva/

**Comment by umlen-B** [comment]
Ok I downloaded the images from docker hub and now what to do?
I am a noob, so please don't mind

**Comment by shuangcoding** [comment]
I have the same problem running 'docker-compose up' at centos7

![image](https://user-images.githubusercontent.com/18232709/27214099-319398a6-529d-11e7-941f-3ef75d60bec7.png)

**Comment by nanqiangyipo** [comment]
I'm in China, my gut tells me it was cased by GRF. So I delete the 'apt-get update' command, then run the 'docker-compose up' and everything works fine. Of cource ,all intercepted sources have been deleted or replaced.(e.g. youtube)

**Comment by AKSHAYUBHAT** [comment]
@shuangcoding can you try running Docker Hello world 

`docker run hello-world`

https://docs.docker.com/get-started/

It appears to me that you have problem with docker installation itself since it fails at the MAINTAINER line. This looks like an issue with docker on Centos 7. 
https://github.com/moby/moby/issues/10294
