### ISSUE TITLE
How to write a new record to dvaapp_video table?

### ISSUE THREAD

**Issue by helium390** [AKSHAYUBHAT/DeepVideoAnalytics#230]
I learned the full process of video uploading and processing. But couldn't find where is writing new record to dvaapp_video table (so, view->view_shared->processing). 
For example
`
DeletedVideo.objects.create(deleter=self.process.user, video_uuid=instance.pk)
`
line is adding a new object to DeletedVideo model.
Is there any function to create video object in Video model?

**Comment by AKSHAYUBHAT** [comment]
https://github.com/AKSHAYUBHAT/DeepVideoAnalytics/blob/ef99adbb3f4f687d3aa8e0089cdfdff5c09b4a9a/server/dvaapp/processing.py#L322

**Comment by AKSHAYUBHAT** [comment]
Essentially video and other objects are specified in JSON and get created before tasks for that process are launched
