### ISSUE TITLE
Split the video problem

### ISSUE THREAD

**Issue by ShaoDu** [AKSHAYUBHAT/DeepVideoAnalytics#233]
sir,
   I would like to ask about the principle of automatic segmentation after uploading video. I looked for the code, but did not find out how video is divided, so I would like to ask how video is divided, can you tell me?     
   thank you!

**Comment by AKSHAYUBHAT** [comment]
https://github.com/AKSHAYUBHAT/DeepVideoAnalytics/blob/ac6ca9c46257750bd966ca9cfcb9878f6e194496/server/dvaapp/operations/decoding.py#L148
