### ISSUE TITLE
WebServer failed to start : Checking if DVA server is running, waiting for another minute and at most x minutes

### ISSUE THREAD

**Issue by steve21124** [AKSHAYUBHAT/DeepVideoAnalytics#242]
# Checklist for submitting an issue 

- Have you verified that docker is installed correctly and e.g. GFW is not preventing downloads? Yes, downloading local image and use local model
  https://github.com/AKSHAYUBHAT/DeepVideoAnalytics/blob/master/docs/gfw.md

- Which docker-compose.yml file are you using?

- Please post output of `docker ps -a` or confirm that all containers are running?
`CONTAINER ID        IMAGE                                   COMMAND                  CREATED             STATUS                      PORTS                                NAMES
810409f5ec03        akshayubhat/dva-auto:latest             "bash -c 'cd /root/D…"   22 minutes ago      Exited (1) 10 minutes ago                                        webserver
ac8c1bb5a681        postgres:9.6.6                          "docker-entrypoint.s…"   22 minutes ago      Up 22 minutes               5432/tcp                             dva-pg
aff666e1af8f        rabbitmq                                "docker-entrypoint.s…"   22 minutes ago      Up 22 minutes               4369/tcp, 5671-5672/tcp, 25672/tcp   dva-rmq
79afbc7e0569        bitnami/redis:latest                    "/entrypoint.sh /run…"   22 minutes ago      Up 22 minutes               6379/tcp                             dva-redis`
- If a specific container is not running or "exited" please post output of `docker logs <name of the container>`

- Is your question about OCR blog post in notebooks/OCR/ ? 

=======================
/usr/local/lib/python2.7/dist-packages/Cython/Compiler/Main.py:367: FutureWarning: Cython directive 'language_level' not set, using 2 for now (Py2). This will change in a later release! File: /root/DVA/repos/tf_ctpn_cpu/lib/utils/bbox.pyx
  tree = Parsing.p_module(s, pxd, full_module_name)
/usr/local/lib/python2.7/dist-packages/Cython/Compiler/Main.py:367: FutureWarning: Cython directive 'language_level' not set, using 2 for now (Py2). This will change in a later release! File: /root/DVA/repos/tf_ctpn_cpu/lib/utils/cython_nms.pyx
  tree = Parsing.p_module(s, pxd, full_module_name)
/usr/local/lib/python2.7/dist-packages/Cython/Compiler/Main.py:367: FutureWarning: Cython directive 'language_level' not set, using 2 for now (Py2). This will change in a later release! File: /root/DVA/repos/tf_ctpn_cpu/lib/utils/gpu_nms.pyx
  tree = Parsing.p_module(s, pxd, full_module_name)
running build_ext
building 'lib.utils.bbox' extension
creating build
creating build/temp.linux-x86_64-2.7
x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -Wdate-time -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC -I/usr/include/python2.7 -c bbox.c -o build/temp.linux-x86_64-2.7/bbox.o
In file included from /usr/include/python2.7/numpy/ndarraytypes.h:1777:0,
                 from /usr/include/python2.7/numpy/ndarrayobject.h:18,
                 from /usr/include/python2.7/numpy/arrayobject.h:4,
                 from bbox.c:613:
/usr/include/python2.7/numpy/npy_1_7_deprecated_api.h:15:2: warning: #warning "Using deprecated NumPy API, disable it by " "#defining NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-Wcpp]
 #warning "Using deprecated NumPy API, disable it by " \
  ^
creating /root/DVA/repos/tf_ctpn_cpu/lib/utils/lib
creating /root/DVA/repos/tf_ctpn_cpu/lib/utils/lib/utils
x86_64-linux-gnu-gcc -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-Bsymbolic-functions -Wl,-z,relro -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -Wdate-time -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -Wl,-Bsymbolic-functions -Wl,-z,relro -Wdate-time -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security build/temp.linux-x86_64-2.7/bbox.o -o /root/DVA/repos/tf_ctpn_cpu/lib/utils/lib/utils/bbox.so
building 'lib.utils.cython_nms' extension
x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -Wdate-time -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC -I/usr/include/python2.7 -c cython_nms.c -o build/temp.linux-x86_64-2.7/cython_nms.o
In file included from /usr/include/python2.7/numpy/ndarraytypes.h:1777:0,
                 from /usr/include/python2.7/numpy/ndarrayobject.h:18,
                 from /usr/include/python2.7/numpy/arrayobject.h:4,
                 from cython_nms.c:613:
/usr/include/python2.7/numpy/npy_1_7_deprecated_api.h:15:2: warning: #warning "Using deprecated NumPy API, disable it by " "#defining NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-Wcpp]
 #warning "Using deprecated NumPy API, disable it by " \
  ^
x86_64-linux-gnu-gcc -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-Bsymbolic-functions -Wl,-z,relro -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -Wdate-time -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -Wl,-Bsymbolic-functions -Wl,-z,relro -Wdate-time -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security build/temp.linux-x86_64-2.7/cython_nms.o -o /root/DVA/repos/tf_ctpn_cpu/lib/utils/lib/utils/cython_nms.so
Collecting django-debug-toolbar
  Downloading https://files.pythonhosted.org/packages/01/9a/3db232bd15882d90d3c53de1f34ce0a522327849593c9198899713267cfe/django_debug_toolbar-1.11-py2.py3-none-any.whl (201kB)
Collecting sqlparse>=0.2.0 (from django-debug-toolbar)
  Downloading https://files.pythonhosted.org/packages/ef/53/900f7d2a54557c6a37886585a91336520e5539e3ae2423ff1102daf4f3a7/sqlparse-0.3.0-py2.py3-none-any.whl
Requirement already satisfied: Django>=1.11 in /usr/local/lib/python2.7/dist-packages (from django-debug-toolbar) (1.11.15)
Requirement already satisfied: pytz in /usr/local/lib/python2.7/dist-packages (from Django>=1.11->django-debug-toolbar) (2018.7)
Installing collected packages: sqlparse, django-debug-toolbar
Successfully installed django-debug-toolbar-1.11 sqlparse-0.3.0
You are using pip version 18.1, however version 19.1.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
rm: cannot remove 'dvaapp/migrations/*.pyc': No such file or directory
WARNING:root:Could not import indexer / clustering assuming running in front-end mode
Migrations for 'dvaapp':
  dvaapp/migrations/0001_initial.py
    - Create model DeletedVideo
    - Create model DVAPQL
    - Create model Export
    - Create model Frame
    - Create model HyperRegionRelation
    - Create model HyperTubeRegionRelation
    - Create model IndexEntries
    - Create model ManagementAction
    - Create model QueryRegion
    - Create model QueryResult
    - Create model Region
    - Create model RegionRelation
    - Create model Retriever
    - Create model Segment
    - Create model SystemState
    - Create model TaskRestart
    - Create model TEvent
    - Create model TrainedModel
    - Create model TrainingSet
    - Create model Tube
    - Create model TubeRegionRelation
    - Create model TubeRelation
    - Create model Video
    - Create model Worker
    - Add field video to tuberelation
    - Add field video to tuberegionrelation
    - Add field video to tube
    - Add field training_set to trainedmodel
    - Add field training_set to tevent
    - Add field video to tevent
    - Add field worker to tevent
    - Add field event to segment
    - Add field video to segment
    - Add field event to regionrelation
    - Add field source_region to regionrelation
    - Add field target_region to regionrelation
    - Add field video to regionrelation
    - Add field event to region
    - Add field user to region
    - Add field video to region
    - Add field region to queryresult
    - Add field retrieval_event to queryresult
    - Add field tube to queryresult
    - Add field video to queryresult
    - Add field event to queryregion
    - Add field query to queryregion
    - Add field event to indexentries
    - Add field video to indexentries
    - Add field event to hypertuberegionrelation
    - Add field tube to hypertuberegionrelation
    - Add field video to hypertuberegionrelation
    - Add field event to hyperregionrelation
    - Add field region to hyperregionrelation
    - Add field video to hyperregionrelation
    - Add field event to frame
    - Add field video to frame
    - Add field event to export
    - Alter unique_together for tuberelation (1 constraint(s))
    - Alter unique_together for tuberegionrelation (1 constraint(s))
    - Alter unique_together for tube (1 constraint(s))
    - Alter unique_together for segment (1 constraint(s))
    - Alter unique_together for regionrelation (1 constraint(s))
    - Alter unique_together for region (1 constraint(s))
    - Alter unique_together for hypertuberegionrelation (1 constraint(s))
    - Alter unique_together for hyperregionrelation (1 constraint(s))
    - Alter unique_together for frame (1 constraint(s))
WARNING:root:Could not import indexer / clustering assuming running in front-end mode
Operations to perform:
  Apply all migrations: admin, auth, authtoken, contenttypes, django_celery_beat, django_celery_results, dvaapp, dvaui, sessions
Running migrations:
  No migrations to apply.
[I 21:51:20.345 NotebookApp] Writing notebook server cookie secret to /root/.local/share/jupyter/runtime/notebook_cookie_secret
[I 21:51:20.734 NotebookApp] Serving notebooks from local directory: /root/DVA
[I 21:51:20.734 NotebookApp] The Jupyter Notebook is running at:
[I 21:51:20.734 NotebookApp] http://(810409f5ec03 or 127.0.0.1):8888/?token=baf57ee2464efbdb346baed9eed7599555fdfd35cb47f31a
[I 21:51:20.735 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 21:51:20.736 NotebookApp] 
    
    Copy/paste this URL into your browser when you connect for the first time,
    to login with a token:
        http://(810409f5ec03 or 127.0.0.1):8888/?token=baf57ee2464efbdb346baed9eed7599555fdfd35cb47f31a
WARNING: yacc table file version is out of date
Traceback (most recent call last):
  File "./launch_from_env.py", line 148, in <module>
    launch_server()
  File "./launch_from_env.py", line 102, in launch_server
    subprocess.check_output(["python", "manage.py", "collectstatic", "--no-input"])
  File "/usr/lib/python2.7/subprocess.py", line 574, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
subprocess.CalledProcessError: Command '['python', 'manage.py', 'collectstatic', '--no-input']' returned non-zero exit status -9
WARNING: Assuming --restrict-filenames since file system encoding cannot encode all characters. Set the LC_ALL environment variable to fix this.
Traceback (most recent call last):
  File "./start_container.py", line 18, in <module>
    subprocess.check_call(['./launch_from_env.py','0'])
  File "/usr/lib/python2.7/subprocess.py", line 541, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['./launch_from_env.py', '0']' returned non-zero exit status 1

**Comment by steve21124** [comment]
======== message so far ===========
Cloning into 'VDN'...
[I 21:34:33.604 NotebookApp] Writing notebook server cookie secret to /root/.local/share/jupyter/runtime/notebook_cookie_secret
[I 21:34:34.023 NotebookApp] Serving notebooks from local directory: /root/DVA
[I 21:34:34.023 NotebookApp] The Jupyter Notebook is running at:
[I 21:34:34.023 NotebookApp] http://(f83fb782b0cc or 127.0.0.1):8888/?token=7d2f61b6ee3951a5fa431707db4ba3f1b9a98ff5d9b8b4e7
[I 21:34:34.024 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 21:34:34.027 NotebookApp] 
    
    Copy/paste this URL into your browser when you connect for the first time,
    to login with a token:
        http://(f83fb782b0cc or 127.0.0.1):8888/?token=7d2f61b6ee3951a5fa431707db4ba3f1b9a98ff5d9b8b4e7
Traceback (most recent call last):
  File "./launch_from_env.py", line 148, in <module>
    launch_server()
  File "./launch_from_env.py", line 102, in launch_server
    subprocess.check_output(["python", "manage.py", "collectstatic", "--no-input"])
  File "/usr/lib/python2.7/subprocess.py", line 574, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
subprocess.CalledProcessError: Command '['python', 'manage.py', 'collectstatic', '--no-input']' returned non-zero exit status -9
===========================
./dvactl configure
Please select mode { dev, cpu, gpu, kube } >>dev
Please specify path to init process.json or press enter to keep default ( configs/custom_defaults/init_process.json ) >>
Refresh docker images by pulling before start: Y/N , press enter to keep default (Y) >>
Please specify docker CPU image or press enter to keep default ( akshayubhat/dva-auto:latest ) >>
Please specify path to init models.json or press enter to keep default ( configs/custom_defaults/trained_models.json ) >>configs/custom_defaults/trained_models_local.json
/Users/stevem/aws.env not found. not passing AWS creds. This is optional and only required if you wish to import/export from AWS S3. To provide credentials please create ~/aws.env with AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY or manually add them to credentials in config.json
/Users/steve/do.env not found. not passing Digital Ocean creds. This is optional and only required if you wish to import/export from Digital Ocean Spaces
Saved config.json
./dvactl start

**Comment by bhardwaj007** [comment]
Are your terminal is connected to internet , because it uses git repository everytime when you enter ./dvactl start. In my case i have configured it to cpu mode , so i dont use ./dvactl , i change directory to deploy then to docker-compose-cpu.yaml and write in terminal sudo docker-compose -f docker-compose-cpu.yaml up -d , and webserver starts and rest of the containers start too.
Note: before doing above process just see docker-compose-cpu.yaml file (in my case i dont know yours), and remove all git requests, it will work fine.

**Comment by bhardwaj007** [comment]
Is your terminal is connected to internet , because it uses git repository everytime when you enter ./dvactl start. In my case (i dont use internet) i have configured it to cpu mode , so i dont use ./dvactl , i change directory to deploy then to docker-compose-cpu.yaml and write in terminal sudo docker-compose -f docker-compose-cpu.yaml up -d , and webserver starts and rest of the containers start too.
Note: before doing above process just see docker-compose-cpu.yaml file (in my case i dont know yours), and remove all git requests, it will work fine.

**Comment by steve21124** [comment]
thanks. It has been a while I have not check back to this thread. been busy doing other part. 
yes, at that time it is connected to internet. may be with recent commit it start working. when weekend come and free, I will check it out again
