### ISSUE TITLE
Replace Dropbox shared links with a different mechanism for distributing model weights.

### ISSUE THREAD

**Issue by AKSHAYUBHAT** [AKSHAYUBHAT/DeepVideoAnalytics#249]
I have deleted Dropbox shared links used for distributing models, as a result this repo will stop working. I will update once I have decided on a new solution.

**Comment by micuentadecasa** [comment]
Hi, any update on this?

regards.

**Comment by rozgo** [comment]
A docker registry over IPFS? https://github.com/miguelmota/ipdr

Then a few of us can host IPFS nodes. I can help set this up.

**Comment by AKSHAYUBHAT** [comment]
I will share a gzip file containing all model weights etc. essentially everything that was previously distributed over Dropbox. Along with a change to codebase that allows specifying a source for download. Hopefully should have it by end of the 2019.

**Comment by BourneXu** [comment]
Hi, any updates for the weights files? I'm wondering if there is a separate docker service for OCR?

**Comment by tianhuat** [comment]
Any updates on this issue?

**Comment by AKSHAYUBHAT** [comment]
hey sorry still working on this

**Comment by tianhuat** [comment]
What about just put the gzip file containing all models (without code changes for downloading etc.) as a stop-gap solution? Without model files, the repo is not usable.

**Comment by AKSHAYUBHAT** [comment]
Sure let me post link to all sources. 
All models are taken from other projects so this should be pretty easy

**Comment by tianhuat** [comment]
That's great, I supposed you have not posted it yet?

**Comment by AKSHAYUBHAT** [comment]
Please email me if you would like to get the zip file with the model.

**Comment by sebastianfelipe** [comment]
Hi. I'd like to have the models to get the project work please. Thanks.

**Comment by ziliang8658** [comment]
hey, mind sening me the zip file of the models, thanks ~
