### ISSUE TITLE
Default SSE4.1 in Tensorflow 1.0 alpha causes core dump on older AMD processors

### ISSUE THREAD

**Issue by havardl** [AKSHAYUBHAT/DeepVideoAnalytics#27]
Hi,

After installing Docker and Docker Compose I get the following error after running docker-compose up of the cloned repo. Running on Ubuntu 16.04.2 LTS (GNU/Linux 4.4.0-72-generic x86_64). Any ideas?

```bash
dva-server | libdc1394 error: Failed to initialize libdc1394
dva-server | F tensorflow/core/platform/cpu_feature_guard.cc:35] The TensorFlow library was compiled to use SSE4.1 instructions, but these aren't available on your machine.
dva-server | Aborted (core dumped)
dva-server |
dva-server | Fatal error: local() encountered an error (return code 134) while executing 'python manage.py makemigrations'
dva-server |
dva-server | Aborting.
dva-server | [localhost] local: sleep 20
dva-server | [localhost] local: python manage.py makemigrations
dva-server exited with code 1
```

**Comment by AKSHAYUBHAT** [comment]
`dva-server | Aborted (core dumped)`
Typically means some issue with Docker itself.

Can you tell me your docker version? 

If you are using CPU version, then you can try to pull the latest image from the Docker hub [1]
[1] https://hub.docker.com/r/akshayubhat/dva-auto/tags/

**Comment by AKSHAYUBHAT** [comment]
HI, I recreated the CPU docker container image from scratch on linode, and it worked without any issues. You can just pull this image and try. 
```

docker pull akshayubhat/dva:cpu

```
https://hub.docker.com/r/akshayubhat/dva/tags/

**Comment by ericpresas** [comment]
I'm getting the same error, i tried what you said and still getting this:

`dva-server | libdc1394 error: Failed to initialize libdc1394`
`dva-server | F tensorflow/core/platform/cpu_feature_guard.cc:35] The TensorFlow library was compiled to use SSE4.1 instructions, but these aren't available on your machine.`
`dva-server | Aborted (core dumped)`
`dva-server | `
`dva-server | Fatal error: local() encountered an error (return code 134) while executing 'python manage.py makemigrations'`
`dva-server | `
`dva-server | Aborting.`
`dva-server | [localhost] local: sleep 20`
`dva-server | [localhost] local: python manage.py makemigrations`
`dva-server exited with code 1`

My Docker version is:

`Client:`
` Version:      17.05.0-ce`
` API version:  1.29`
 `Go version:   go1.7.5`
` Git commit:   89658be`
` Built:        Thu May  4 22:10:54 2017`
 `OS/Arch:      linux/amd64`

`Server:`
 `Version:      17.05.0-ce`
` API version:  1.29 (minimum version 1.12)`
 `Go version:   go1.7.5`
` Git commit:   89658be`
` Built:        Thu May  4 22:10:54 2017`
` OS/Arch:      linux/amd64`
` Experimental: false`

**Comment by AKSHAYUBHAT** [comment]
```
The TensorFlow library was compiled to use SSE4.1 instructions, but these aren't available on your machine.
```
This is likely cause of the core dump. 

0. Can you give me the exact `docker-compose` command you ran? 
1.  Are you using GPU docker container or CPU container ?
2. Are you building the containers yourself by running ./rebuild.sh ?
3. To test you can run `docker run -a stdin -a stdout -i -t akshayubhat/dva:cpu python`

Once you are at python terminal inside the container
```
import tensorflow as tf
hello = tf.constant('Hello, TensorFlow!')
sess = tf.Session()
print sess.run(hello)
```

Finally you can pull non SSE optimized builds from docker hub. 
https://hub.docker.com/r/akshayubhat/dva-auto/tags/

You would need to edit the compose file and replace `akshayubhat/dva:cpu` with `akshayubhat/dva-auto:latest`

**Comment by ericpresas** [comment]
Thanks for the quick answer!

0. I run with `docker-compose up`
1. I'm using a CPU container
2. I'm not running `./rebuild.sh`
3. Then i run `docker run -a stdin -a stdout -i -t akshayubhat/dva-auto:latest python`
When i import tensorflow it throws me:
`>>> import tensorflow as tf`
`F tensorflow/core/platform/cpu_feature_guard.cc:35] The TensorFlow library was compiled to use SSE4.1 instructions, but these aren't available on your machine.
`

**Comment by AKSHAYUBHAT** [comment]
Does it crashes afterwards, or can you run rest of the commands?

1. Run `docker ps -a` and remove any stopped containers using `docker rm <container_id>`.
2. Then remove all old images by running `docker image ls` followed by `docker rmi <image_id>`
3. Finally do `git pull`.
4. Followed by `docker pull akshayubhat/dva-auto:latest` to pull latest image from docker hub.

**Comment by ericpresas** [comment]
I've tried it, now after `docker-compose up` it throws me:

`dva-rmq is up-to-date`
`dva-pg is up-to-date`
`Recreating 0db797efdc03_0db797efdc03_dva-server`

`ERROR: for dva  no such image: ``sha256:9fff5a29013a537e532a9a443ebf7530ab29cd6c692deaec46bf677a51d2942b: No such image: sha256:9fff5a29013a537e532a9a443ebf7530ab29cd6c692deaec46bf677a51d2942b`
`ERROR: Encountered errors while bringing up the project.`

thanks!!!

**Comment by AKSHAYUBHAT** [comment]
If you are not using Docker for any other project. You can run  following commands to remove all stopped containers and dangling nodes.
```
docker-compose down -v
docker system prune
```
After that do 

`git pull && docker pull akshayubhat/dva-auto:latest && docker-compose up`

**Comment by ericpresas** [comment]
still getting:

`dva-server | libdc1394 error: Failed to initialize libdc1394`
`dva-server | F tensorflow/core/platform/cpu_feature_guard.cc:35] The TensorFlow library was compiled to use SSE4.1 instructions, but these aren't available on your machine.`
`dva-server | Aborted (core dumped)`
`dva-server | `
`dva-server | Fatal error: local() encountered an error (return code 134) while executing 'python manage.py makemigrations'`
`dva-server | `
`dva-server | Aborting.`
`dva-server | [localhost] local: sleep 20`
`dva-server | [localhost] local: python manage.py makemigrations`
`dva-server exited with code 1`

I did exactly what you said

**Comment by AKSHAYUBHAT** [comment]
Can you post output of `docker image ls`? 

I dont know why you keep getting a container image with SSE enabled which I am sure is disabled.  The only thing I can thubk of is that you have a `dva_cpu_base` image which was built locally instead of being pulled. Since that image contains Tensorflow install and gets inherited by dva-auto build.

**Comment by ericpresas** [comment]
okay, i will change it. Which version of tensorflow i have to install?

**Comment by AKSHAYUBHAT** [comment]
As a quick fix you can locally edit following line

https://github.com/AKSHAYUBHAT/DeepVideoAnalytics/blob/master/docker/docker-compose.yml#L41

from 
```
     command: bash -c "youtube-dl -U && git pull && fab start_container"
```
to 
```
     command: bash -c "youtube-dl -U && pip install --upgrade https://storage.googleapis.com/tensorflow/linux/cpu/tensorflow-1.0.0-cp27-none-linux_x86_64.whl && git pull && fab start_container"
```

This will ensure that the Tensorflow image version is updated from 1.0.0 alpha to 1.0.0 stable before launching any processes.

**Comment by ericpresas** [comment]
I tried with other computer and works propperly, that's because i was using an old laptop. It's because my laptop don't support SSE4.1 instructions.

I did the quick fix that you said and it works also!!

Thank you for your patience ;)

**Comment by AKSHAYUBHAT** [comment]
Fixed both CPU & GPU images have been updated Tensorflow 1.1.0
