### ISSUE TITLE
Server not running from AMI using GPU

### ISSUE THREAD

**Issue by hamstah** [AKSHAYUBHAT/DeepVideoAnalytics#28]
Hi,

I ran into a few issues when trying to run the gpu version on aws.
The server didn't start even after 10mins.
I logged into the server to investigate, here are the things I tried to get it to work, I will update the issue as I make progress 

## Dependencies not installed

I logged into the server and nothing was running on it. I followed the steps from https://github.com/AKSHAYUBHAT/DeepVideoAnalytics/blob/master/notes/ami.md and managed to get all the dependencies installed.

The dependencies were not installed initially, **but** the repo had been checked out already. I suspect something went wrong when creating the ami.

## The AMI check out is a few weeks old

As I could not get docker to start (see below) I checked the version of the code in the AMI, it was from March 24th. I did a git pull to update to 099d6998ad3fa353f44188f925fa22be7b484993

## Could not start the containers

I tried
```
~/deepvideoanalytics/docker_GPU$ docker-compose -f nvidia-docker-compose.yml up
```

But it fails with the following error
```
Warning: Command(s) not found:
start_server_container_gpu
```
In the list of supported commands listed under the error, start_server_container_gpu is not listed. I can see it in the fabfile, so maybe it's just the container being out of date

## Could not rebuild containers

Before pullint the latest version, there was a `rebuild.sh` script in the same folder, but running it failed with an error. I don't have the exact error anymore, but it was related to an unsupported docker version.

The new folder doesn't have the rebuild script in it.

**Comment by hamstah** [comment]
Found the `rebuild_gpu.sh` in docker and tried it again with the same result as before.
Here is the exact error
```
~/deepvideoanalytics/docker$ ./rebuild_gpu.sh 
nvidia-docker | 2017/04/29 09:18:57 Error: unsupported Docker version

~/deepvideoanalytics/docker$ nvidia-docker -v
nvidia-docker | 2017/04/29 09:19:02 Error: unsupported Docker version

~/deepvideoanalytics/docker$ docker -v
Docker version 17.04.0-ce, build 4845c56
```
Will look into nvidia-docker and see if I can resolve it

**Comment by hamstah** [comment]
The issue is that the AMI is using docker 17.04, but nvidia docker's latest release 1.0.1 only supports 17.03.
The solution is to downgrade docker
```
sudo apt-get remove docker-engine
sudo apt-get install docker-engine=17.03.1~ce-0~ubuntu-xenial
```
And re-install `docker-nvidia` (it gets removed when removing docker)
```
wget -P /tmp https://github.com/NVIDIA/nvidia-docker/releases/download/v1.0.1/nvidia-docker_1.0.1-1_amd64.deb
sudo dpkg -i /tmp/nvidia-docker*.deb && rm /tmp/nvidia-docker*.deb
```
Now nvidia-docker works
```
~/deepvideoanalytics/docker$ nvidia-docker -v
Docker version 17.03.1-ce, build c6d412e
```

**Comment by hamstah** [comment]
Even after a rebuild, the same error persists.

I've tried to use
```
nvidia-docker-compose -f docker/docker-compose-gpu-aws.yml up
```

But keep running into issues

## cryspy-forms import error in dva-workers. 

I manually added `pip install django-crispy-forms` to the command in the docker-compose file to work around it

Here is the full stacktrace
```
dva-worker-2 | Traceback (most recent call last):
dva-worker-2 |   File "/usr/local/lib/python2.7/dist-packages/fabric/main.py", line 756, in main
dva-worker-2 |     *args, **kwargs
dva-worker-2 |   File "/usr/local/lib/python2.7/dist-packages/fabric/tasks.py", line 426, in execute
dva-worker-2 |     results['<local-only>'] = task.run(*args, **new_kwargs)
dva-worker-2 |   File "/usr/local/lib/python2.7/dist-packages/fabric/tasks.py", line 173, in run
dva-worker-2 |     return self.wrapped(*args, **kwargs)
dva-worker-2 |   File "/root/DVA/fabfile.py", line 293, in startq
dva-worker-2 |     django.setup()
dva-worker-2 |   File "/usr/local/lib/python2.7/dist-packages/django/__init__.py", line 27, in setup
dva-worker-2 |     apps.populate(settings.INSTALLED_APPS)
dva-worker-2 |   File "/usr/local/lib/python2.7/dist-packages/django/apps/registry.py", line 85, in populate
dva-worker-2 |     app_config = AppConfig.create(entry)
dva-worker-2 |   File "/usr/local/lib/python2.7/dist-packages/django/apps/config.py", line 90, in create
dva-worker-2 |     module = import_module(entry)
dva-worker-2 |   File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
dva-worker-2 |     __import__(name)
dva-worker-2 | ImportError: No module named crispy_forms
```
## Queue not found in dva-worker

```
dva-worker-1 | Traceback (most recent call last):
dva-worker-1 |   File "/usr/local/lib/python2.7/dist-packages/fabric/main.py", line 756, in main
dva-worker-1 |     *args, **kwargs
dva-worker-1 |   File "/usr/local/lib/python2.7/dist-packages/fabric/tasks.py", line 426, in execute
dva-worker-1 |     results['<local-only>'] = task.run(*args, **new_kwargs)
dva-worker-1 |   File "/usr/local/lib/python2.7/dist-packages/fabric/tasks.py", line 173, in run
dva-worker-1 |     return self.wrapped(*args, **kwargs)
dva-worker-1 |   File "/root/DVA/fabfile.py", line 303, in startq
dva-worker-1 |     raise ValueError, "Queue {} not found".format(queue_name)
dva-worker-1 | ValueError: Queue extractor not found
```

## Start container gpu not found

```
dva-server | 
dva-server | Warning: Command(s) not found:
dva-server |     setup_container_gpu
dva-server | 
```

**Comment by AKSHAYUBHAT** [comment]
I have started an EC2 instance to check.

Are you using the AMI that I provided or creating a new AMI from scratch?

For my AMI you should follow instructions on the homepage (https://deepvideoanalytics.com).
Once the AMI / EC2 instance is you manually need to following commands to (a. updated the repo b. pull & rebuild the docker image & c. launch the containers.)

``` 
rm -rf deepvideoanalytics && git clone https://github.com/akshayubhat/deepvideoanalytics
cd deepvideoanalytics/docker
./rebuild_gpu.sh
nvidia-docker-compose -f docker-compose-gpu.yml up
```

It seems you never "rebuild_gpu.sh" which updates/rebuilds the dva-server container image.

**Comment by hamstah** [comment]
Hi
Thanks for the reply.
I used the Ami mentioned on the homepage.
I did rebuild the image with rebuild GPU from the docker subfolder and it
succeeded.

**Comment by AKSHAYUBHAT** [comment]
Wait so its working? Should I close the issue?

**Comment by AKSHAYUBHAT** [comment]
Okay I just ran AWS EC2 P2 instance with following commands[1]
```

rm -rf deepvideoanalytics && git clone https://github.com/akshayubhat/deepvideoanalytics
cd deepvideoanalytics/docker
./rebuild_gpu.sh
nvidia-docker-compose -f docker-compose-gpu.yml up
```

And verified that it works.
https://github.com/AKSHAYUBHAT/DeepVideoAnalytics/blob/master/experiments/fabfile.py#L76

**Comment by AKSHAYUBHAT** [comment]
Okay verified it second time on the AMI with exactly the four command above.

**Comment by hamstah** [comment]
Ok I will try this.
Did you not have the issues I described with the NVIDIA docker version etc?

**Comment by AKSHAYUBHAT** [comment]
Nope you don't need to follow instructions in https://github.com/AKSHAYUBHAT/DeepVideoAnalytics/blob/master/notes/ami.md unless you are starting from scratch. 

Also there is docker/shell.sh that lets you enter a running dva-server container with an interactive shell for exploration and debugging.

**Comment by hamstah** [comment]
Ok, apologies I had misunderstood the instructions on the homepage, should have waited to be awake....
I thought the server would come up automatically and missed the extra commands.

Thanks anyway for your quick replies, I've got it to work!
