### ISSUE TITLE
yolo9000 weights

### ISSUE THREAD

**Issue by Aspirinkb** [AKSHAYUBHAT/DeepVideoAnalytics#30]
I can not get the yolo9000.weights from dropbox by `wget` command for the network environment of my country. So I directly download the weights by some other way, where should I put the `yolo9000.weights` file and how can I skip this step when I execute the `docker-compose up`?
<img width="1093" alt="wget error when download yolo9000.weights" src="https://cloud.githubusercontent.com/assets/5260197/25616575/381b05f6-2f70-11e7-8779-b364d6fb8c42.png">

**Comment by AKSHAYUBHAT** [comment]
You can edit docker/Dockerfile and docker/Dockerfile.gpu with your link insteadbof Dropbox links. You can alternatively just pull prebuilt Docker containers from Docker hub.
