### ISSUE TITLE
when run docker-compose up get following problem

### ISSUE THREAD

**Issue by 913647909** [AKSHAYUBHAT/DeepVideoAnalytics#32]
dva-server |
dva-server | Done.
dva-server | Segmentation fault (core dumped)
dva-server |
dva-server | Done.
dva-server | WARNING:root:Could not import torch
dva-server | WARNING:root:Could not import torch
dva-server | /usr/local/lib/python2.7/dist-packages/sklearn/cross_validation.py:44: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
dva-server |   "This module will be removed in 0.20.", DeprecationWarning)
dva-server | /usr/local/lib/python2.7/dist-packages/sklearn/cross_validation.py:44: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
dva-server |   "This module will be removed in 0.20.", DeprecationWarning)
dva-server | /usr/local/lib/python2.7/dist-packages/celery/platforms.py:812: RuntimeWarning: You are running the worker with superuser privileges, which is
dva-server | absolutely not recommended!
dva-server |
dva-server | Please specify a different user using the -u option.
dva-server |
dva-server | User information: uid=0 euid=0 gid=0 egid=0
dva-server |
dva-server |   uid=uid, euid=euid, gid=gid, egid=egid,
dva-server | /usr/local/lib/python2.7/dist-packages/celery/platforms.py:812: RuntimeWarning: You are running the worker with superuser privileges, which is
dva-server | absolutely not recommended!
dva-server |
dva-server | Please specify a different user using the -u option.
dva-server |
dva-server | User information: uid=0 euid=0 gid=0 egid=0
dva-server |
dva-server |   uid=uid, euid=euid, gid=gid, egid=egid,
dva-rmq   |
dva-rmq   | =INFO REPORT==== 4-May-2017::03:23:47 ===
dva-rmq   | accepting AMQP connection <0.311.0> (172.18.0.4:51734 -> 172.18.0.2:5672)
dva-rmq   |
dva-rmq   | =INFO REPORT==== 4-May-2017::03:23:47 ===
dva-rmq   | accepting AMQP connection <0.314.0> (172.18.0.4:51736 -> 172.18.0.2:5672)
dva-rmq   |
dva-rmq   | =INFO REPORT==== 4-May-2017::03:23:47 ===
dva-rmq   | connection <0.311.0> (172.18.0.4:51734 -> 172.18.0.2:5672): user 'dvauser' authenticated and granted access to vhost '/' dva-rmq   |
dva-rmq   | =INFO REPORT==== 4-May-2017::03:23:47 ===
dva-rmq   | connection <0.314.0> (172.18.0.4:51736 -> 172.18.0.2:5672): user 'dvauser' authenticated and granted access to vhost '/' dva-rmq   |
dva-rmq   | =INFO REPORT==== 4-May-2017::03:23:47 ===
dva-rmq   | accepting AMQP connection <0.324.0> (172.18.0.4:51740 -> 172.18.0.2:5672)
dva-rmq   |
dva-rmq   | =INFO REPORT==== 4-May-2017::03:23:47 ===
dva-rmq   | accepting AMQP connection <0.321.0> (172.18.0.4:51738 -> 172.18.0.2:5672)
dva-rmq   |
dva-rmq   | =INFO REPORT==== 4-May-2017::03:23:47 ===
dva-rmq   | connection <0.324.0> (172.18.0.4:51740 -> 172.18.0.2:5672): user 'dvauser' authenticated and granted access to vhost '/' dva-rmq   |
dva-rmq   | =INFO REPORT==== 4-May-2017::03:23:47 ===
dva-rmq   | connection <0.321.0> (172.18.0.4:51738 -> 172.18.0.2:5672): user 'dvauser' authenticated and granted access to vhost '/' dva-server | libdc1394 error: Failed to initialize libdc1394
dva-server | WARNING:root:Could not import torch
dva-server | /usr/local/lib/python2.7/dist-packages/sklearn/cross_validation.py:44: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
dva-server |   "This module will be removed in 0.20.", DeprecationWarning)

**Comment by AKSHAYUBHAT** [comment]
`
dva-server | Segmentation fault (core dumped)

`
This is typically the result of having an older version of Docker, can you tell me which docker version you are running and if its GPU or CPU container?

**Comment by 913647909** [comment]
thanks for your reply
when i try to use a 4G server，this problem doesn't appear and i can run the whole project
thanks a lot:)
