### ISSUE TITLE
login Deep Video Analytics

### ISSUE THREAD

**Issue by Aspirinkb** [AKSHAYUBHAT/DeepVideoAnalytics#36]
I update the project to 2017.5.18 to find that I need input username and password to login the deep video analytics page, but I do not have one.  How can I get the username and password?

<img width="485" alt="2017-05-22 14 04 53" src="https://cloud.githubusercontent.com/assets/5260197/26294664/0637e08a-3ef8-11e7-89c9-750be1042c5f.png">

**Comment by AKSHAYUBHAT** [comment]
Just add AUTH_DISABLED=1 to environment variables in docker-compse file you are using.
