### ISSUE TITLE
Error while using docker-compose up

### ISSUE THREAD

**Issue by kousik97** [AKSHAYUBHAT/DeepVideoAnalytics#39]
Getting the following error while using docker-compose up

ERROR: Couldn't connect to Docker daemon at http+docker://localunixsocket - is it running?

If it's at a non-standard location, specify the URL with the DOCKER_HOST environment variable.

**Comment by AKSHAYUBHAT** [comment]
This looks like an error with Docker (not being able to connect with docker-daemon), can you try the docker hello world example here.

https://docs.docker.com/get-started/#setup
