### ISSUE TITLE
when i upload a video(.mp4), it occurs the error

### ISSUE THREAD

**Issue by oyosc** [AKSHAYUBHAT/DeepVideoAnalytics#40]
when i upload a video(.mp4), it occurs the error:
  Forbidden (CSRF token missing or incorrect.): /
but if i upload a zip file,it is ok! so what happend?

**Comment by AKSHAYUBHAT** [comment]
Can you try again? This might have happened because you turned the server on/off resulting in incorrect CSRF token being sent when you tried it with .mp4 file.

**Comment by oyosc** [comment]
i try many times,and it is also. the follow is the logs:

dva-server | Forbidden (CSRF token missing or incorrect.): /

dva-server | [05/Jun/2017 03:20:07] "POST / HTTP/1.1" 403 2502

dva-server | Forbidden (CSRF token missing or incorrect.): /

dva-server | [05/Jun/2017 03:21:02] "POST / HTTP/1.1" 403 2502

2017-06-05 11:18 GMT+08:00 Akshay Bhat <notifications@github.com>:
