### ISSUE TITLE
Ongoing User Interface improvements

### ISSUE THREAD

**Issue by AKSHAYUBHAT** [AKSHAYUBHAT/DeepVideoAnalytics#41]
- [x] Fix dashboard search results remove hardcoded indexers, ensure uniformity with query_detail
- [x] create a JSON language DVAPQL for ingestion, query, processing which enable other clients.
- [x] Direct uploads to S3 for cloud deployment configuration
- [ ] Show video by embedding from youtube in cloud deploy config to save bandwidth
- [x] Task status is inconsistent, with Celery 4.0 it should be fixable

**Comment by nanqiangyipo** [comment]
There should be a delete button where users can delete the data they uploaded on Video Viewer page and also on Past queries page.

**Comment by AKSHAYUBHAT** [comment]
Thanks, currently you can delete the Video SQL entry and all deletes will cascade. I have not implemented Delete functionality through UI since DVA lacked a User / Permissions model (Should User A be allowed to delete videos uploaded by B, etc.), however with authentication and users now in place I will start integrating deletes.

**Comment by AKSHAYUBHAT** [comment]
@nanqiangyipo Added delete video button in video_detail (renaming next), further it stores deleted video_id in another model for clearing fs/bucket. However currently the way retrievers are structured there is no easy way to "invalidate" loaded indexes.
