### ISSUE TITLE
how to use Admin 

### ISSUE THREAD

**Issue by zarchary** [AKSHAYUBHAT/DeepVideoAnalytics#44]
hi, 
 I have build the docker and run it successfully，but I can't enter Admin

**Comment by AKSHAYUBHAT** [comment]
Use `shell.sh` inside DeepVideoAnalytics/docker to enter into container and then run `python manage.py createsuperuser`.

You can also add AUTH_DISABLED=1 in the docker-compose.yml to disable authentication.
