### ISSUE TITLE
hi,if i want to visit the site through port 80

### ISSUE THREAD

**Issue by oyosc** [AKSHAYUBHAT/DeepVideoAnalytics#47]
hi,if i want to visit the site through port 80,what should i do ,thanks !

**Comment by oyosc** [comment]
and whether can i control the start time of video,when i set the video.currentTime,it is not correct and no use

**Comment by nanqiangyipo** [comment]
firstly, find start_container function  in fabfile.py and change 8000 to 80 behind the runserver command.
second , open the file docker-compose.yml in project_root/docker and change the 8000:8000 to 80:80.

**Comment by oyosc** [comment]
i have got this, but whether can i control the start time of video,when i set the video.currentTime, no use

**Comment by AKSHAYUBHAT** [comment]
@oyosc video handling is a bit iffy and varies from browser to browser, ideally sometime in future I will wrap the native <video> tag into something like video.js which comes with multiple plugins to make handling easier [1]

[1] http://videojs.com/plugins/

I am closing this issue for now but feel free to ask more questions below.
