### ISSUE TITLE
perform_face_detection crash

### ISSUE THREAD

**Issue by wikipedia2008** [AKSHAYUBHAT/DeepVideoAnalytics#49]
dva-server | Traceback (most recent call last):
dva-server |   File "/usr/local/lib/python2.7/dist-packages/fabric/main.py", line 757, in main
dva-server |     *args, **kwargs
dva-server |   File "/usr/local/lib/python2.7/dist-packages/fabric/tasks.py", line 426, in execute
dva-server |     results['<local-only>'] = task.run(*args, **new_kwargs)
dva-server |   File "/usr/local/lib/python2.7/dist-packages/fabric/tasks.py", line 173, in run
dva-server |     return self.wrapped(*args, **kwargs)
dva-server |   File "/root/DVA/fabfile.py", line 576, in perform_face_detection
dva-server |     perform_face_indexing(int(video_id))
dva-server |   File "/root/DVA/dvaapp/tasks.py", line 556, in perform_face_indexing
dva-server |     face_indexer = indexer.FacenetIndexer()
dva-server | NameError: global name 'indexer' is not defined

**Comment by AKSHAYUBHAT** [comment]
@wikipedia2008 

The reason this can happen is when dvalib.indexer does not gets imported. 
E.g. When running code on heroku in frontend, the code never uses any dvalib methods and its fine if the import silently fails. 

Can you verify that there is no import error, for reference following code is where indexer gets imported.

```
try:
    from dvalib import entity
    from dvalib import detector
    from dvalib import indexer
    from dvalib import clustering
    from dvalib.yolo import trainer
    from PIL import Image
    from scipy import misc
except ImportError:
    logging.warning("Could not import dvalib assuming operating in frontend only mode")

```
