### ISSUE TITLE
Building End to End Trainable OCR Pipeline

### ISSUE THREAD

**Issue by rayush7** [AKSHAYUBHAT/DeepVideoAnalytics#51]
@AKSHAYUBHAT This is a great implementation combining CTPN with CRNN. I have also read about people combining Textboxes with CRNN for the same. However this is still not a end to end trainable pipeline because CTPN is implemented in Caffe and CRNN is implemented in Torch7 and PyTorch. Any ideas how can I go about building an end to end trainable model for OCR i.e. combining text detection and text recognition in the same deepnet?

**Comment by AKSHAYUBHAT** [comment]
Yeah its not End-To-End trainable, I am looking at several other options Textboxes etc. once I have finalized it I will implement fine-tuning training.
