### ISSUE TITLE
Error during template rendering

### ISSUE THREAD

**Issue by vijnasu** [AKSHAYUBHAT/DeepVideoAnalytics#56]
Any idea about the following error:-

Request Method:
--
http://localhost:8000/
1.11.2
ProgrammingError
column dvaapp_indexentries.indexer_id does not exist
LINE 1: ...es_file_name", "dvaapp_indexentries"."algorithm", "dvaapp_in...
                                                             ^
/usr/local/lib/python2.7/dist-packages/django/db/models/sql/compiler.py in execute_sql, line 886
/usr/bin/python
2.7.6
['/root/DVA',
 '/usr/local/lib/python2.7/dist-packages/lopq-1.0.1139-py2.7.egg',
 '/usr/lib/python2.7',
 '/usr/lib/python2.7/plat-x86_64-linux-gnu',
 '/usr/lib/python2.7/lib-tk',
 '/usr/lib/python2.7/lib-old',
 '/usr/lib/python2.7/lib-dynload',
 '/usr/local/lib/python2.7/dist-packages',
 '/usr/lib/python2.7/dist-packages',
 '/usr/lib/python2.7/dist-packages/PILcompat',
 '/root/DVA']
Mon, 10 Jul 2017 11:13:23 +0000

**Comment by AKSHAYUBHAT** [comment]
Have you applied migrations using `python manage.py migrate` or `fab migrate`. Currently since the code is in active development, the underlying data model frequently changes hence its essential to check by running migrations.

**Comment by vijnasu** [comment]
After applying the migrations also same problem persists. While running docker-compose up, it says no migrations to apply.

**Comment by AKSHAYUBHAT** [comment]
Can you go inside the server container using docker/shell.sh. Once inside do a `git pull` and fab migrate.

**Comment by vijnasu** [comment]
Inside the server container the git pull gives Already up-to-date and fab migrate says no migrations to apply. But programming error named problem persists in home page loading.

**Comment by AKSHAYUBHAT** [comment]
Are you sure you are connecting to the correct server?

Can you post contents of your `davapp/models.py`

**Comment by vijnasu** [comment]
models.py is same as that in repository. If I run python models.py it gives an error:-
Traceback (most recent call last):
  File "models.py", line 4, in <module>
    from django.contrib.auth.models import User
  File "/usr/local/lib/python2.7/dist-packages/django/contrib/auth/models.py", line 4, in <module>
    from django.contrib.auth.base_user import AbstractBaseUser, BaseUserManager
  File "/usr/local/lib/python2.7/dist-packages/django/contrib/auth/base_user.py", line 52, in <module>
    class AbstractBaseUser(models.Model):
  File "/usr/local/lib/python2.7/dist-packages/django/contrib/auth/base_user.py", line 53, in AbstractBaseUser
    password = models.CharField(_('password'), max_length=128)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/fields/__init__.py", line 1061, in __init__
    super(CharField, self).__init__(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/fields/__init__.py", line 172, in __init__
    self.db_tablespace = db_tablespace or settings.DEFAULT_INDEX_TABLESPACE
  File "/usr/local/lib/python2.7/dist-packages/django/conf/__init__.py", line 56, in __getattr__
    self._setup(name)
  File "/usr/local/lib/python2.7/dist-packages/django/conf/__init__.py", line 39, in _setup
    % (desc, ENVIRONMENT_VARIABLE))
django.core.exceptions.ImproperlyConfigured: Requested setting DEFAULT_INDEX_TABLESPACE, but settings are not configured. You must either define the environment variable DJANGO_SETTINGS_MODULE or call settings.configure() before accessing settings.

**Comment by AKSHAYUBHAT** [comment]
you don't run models.py it merely contains information about Database schema, in your case what has happened is that the database schema has not been updated (migrated) correctly, thus you get a "Prgramming error" as it cannot find the column specified in models.py in your dvaapp_indexentries table.

If you don't have any data you can always just run `docker-compose down -v` (which will ERASE all database and other dva volumes) and then create a new stack by running `docker-compose up`.

**Comment by vijnasu** [comment]
Error is resolved and page loads now. Thank you for the inputs. 
When I give a frame from say 'Tomorrow never dies' video for an exact search; It doesn't return back. Faced same issue before. Any feedback for this?

**Comment by AKSHAYUBHAT** [comment]
Make sure that all tasks are finished (indexes have been computed)
