### ISSUE TITLE
Finding hard to run the project

### ISSUE THREAD

**Issue by gmegharaj** [AKSHAYUBHAT/DeepVideoAnalytics#59]
./shell.sh 
Cannot connect to the Docker daemon. Is the docker daemon running on this host?

**Comment by gmegharaj** [comment]
Please Help me in running this project.

**Comment by e212156822000** [comment]
You can try to use `sudo` to run the command or `sudo usermod -a -G docker username`.

**Comment by AKSHAYUBHAT** [comment]
@gmegharaj Hi, Sorry with a correctly setup docker the project is very easy to run. Please check stackoverflow for instructions regarding troubleshooting docker.
