### ISSUE TITLE
Overlay detections on video/image

### ISSUE THREAD

**Issue by OmriShiv** [AKSHAYUBHAT/DeepVideoAnalytics#6]
Is it possible to overlay the detections on the video/image in the preview?

**Comment by AKSHAYUBHAT** [comment]
I think its surely possible, the screenshots in readme.md are not updated but the current UI shows individual detections at bottom in the frame detail page, this allows showing other information such as confidence and name. 

I am considering using the Fabric Canvas (just like the dashboard page) to render the frame image and add rectangles on the bounding box in the frame details page. This will allow easy zoom/hide/show and additional information to be displayed.

**Comment by OmriShiv** [comment]
That would be really useful, especially being able to easily toggle it on/off. thank you

**Comment by AKSHAYUBHAT** [comment]
Added it in the frame annotation user interface commit @839e036fa4e9c29921a327399533fc9a9f2d5ff0
