### ISSUE TITLE
Fatal error: local() encountered an error (return code 1) while executing 'python manage.py migrate'

### ISSUE THREAD

**Issue by e212156822000** [AKSHAYUBHAT/DeepVideoAnalytics#60]
## Context of the issue

I've used the command below, and already built it successfully.
`git clone https://github.com/AKSHAYUBHAT/DeepVideoAnalytics`
`cd DeepVideoAnalytics/docker && docker-compose up`

I uploaded a video on the website with port 8000, then used `Ctrl + c` in the terminal to end it.
after I ran `docker-compose up` to restart it , it showed up error messages.

## Expected result
start up successfully as the first time on port 8000.

## Current result

> dva-server | Updated youtube-dl. Restart youtube-dl to use the new version.
dva-server | From https://github.com/akshayubhat/DeepVideoAnalytics
dva-server |    bea6e6d..0ef2577  master     -> origin/master
dva-server | Updating bea6e6d..0ef2577
dva-server | Fast-forward
dva-server |  dva/celery.py                                      |   2 +
dva-server |  dva/worker_config.py                               |  28 ++--
dva-server |  dvaapp/migrations/0001_auto_20170704_0417.py       |  86 ----------
dva-server |  dvaapp/migrations/0001_auto_20170729_1645.py       | 186 +++++++++++++++++++++
dva-server |  dvaapp/migrations/0002_auto_20170709_0837.py       |  22 ---
dva-server |  dvaapp/migrations/0003_deletedvideo.py             |  30 ----
dva-server |  dvaapp/migrations/0004_auto_20170716_2204.py       |  46 -----
dva-server |  dvaapp/migrations/0005_auto_20170717_1856.py       |  25 ---
dva-server |  dvaapp/migrations/0006_auto_20170718_0342.py       |  25 ---
dva-server |  .../0007_indexerquery_source_filter_json.py        |  20 ---
dva-server |  dvaapp/migrations/0008_auto_20170726_1957.py       |  28 ----
dva-server |  dvaapp/migrations/custom_migration.py              |  32 ++--
dva-server |  dvaapp/models.py                                   |   3 +-
dva-server |  dvaapp/operations/query_processing.py              | 145 +++++++++++++---
dva-server |  dvaapp/shared.py                                   |   2 +
dva-server |  dvaapp/tasks.py                                    | 119 +++++++------
dva-server |  dvaapp/views.py                                    |   2 +-
dva-server |  dvalib/indexer.py                                  |  75 ---------
dva-server |  dvalib/retriever.py                                |  54 ++++++
dva-server |  fabfile.py                                         |   6 +-
dva-server |  20 files changed, 462 insertions(+), 474 deletions(-)
dva-server |  delete mode 100644 dvaapp/migrations/0001_auto_20170704_0417.py
dva-server |  create mode 100644 dvaapp/migrations/0001_auto_20170729_1645.py
dva-server |  delete mode 100644 dvaapp/migrations/0002_auto_20170709_0837.py
dva-server |  delete mode 100644 dvaapp/migrations/0003_deletedvideo.py
dva-server |  delete mode 100644 dvaapp/migrations/0004_auto_20170716_2204.py
dva-server |  delete mode 100644 dvaapp/migrations/0005_auto_20170717_1856.py
dva-server |  delete mode 100644 dvaapp/migrations/0006_auto_20170718_0342.py
dva-server |  delete mode 100644 dvaapp/migrations/0007_indexerquery_source_filter_json.py
dva-server |  delete mode 100644 dvaapp/migrations/0008_auto_20170726_1957.py
dva-server |  create mode 100644 dvalib/retriever.py
dva-server | /usr/local/lib/python2.7/dist-packages/sklearn/cross_validation.py:44: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
dva-server |   "This module will be removed in 0.20.", DeprecationWarning)
dva-server | No changes detected
dva-server | /usr/local/lib/python2.7/dist-packages/sklearn/cross_validation.py:44: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
dva-server |   "This module will be removed in 0.20.", DeprecationWarning)
dva-server | Operations to perform:
dva-server |   Apply all migrations: admin, auth, authtoken, contenttypes, django_celery_results, dvaapp, sessions, vdnapp
dva-server | Running migrations:
dva-pg    | ERROR:  relation "dvaapp_deletedvideo" already exists
dva-pg    | STATEMENT:  CREATE TABLE "dvaapp_deletedvideo" ("id" serial NOT NULL PRIMARY KEY, "name" varchar(500) NOT NULL, "description" text NOT NULL, "url" text NOT NULL, "original_pk" integer NOT NULL, "deleter_id" integer NOT NULL, "uploader_id" integer NULL)
dva-server |   Applying dvaapp.0001_auto_20170729_1645...Traceback (most recent call last):
dva-server |   File "manage.py", line 22, in <module>
dva-server |     execute_from_command_line(sys.argv)
dva-server |   File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 363, in execute_from_command_line
dva-server |     utility.execute()
dva-server |   File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 355, in execute
dva-server |     self.fetch_command(subcommand).run_from_argv(self.argv)
dva-server |   File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 283, in run_from_argv
dva-server |     self.execute(*args, **cmd_options)
dva-server |   File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 330, in execute
dva-server |     output = self.handle(*args, **options)
dva-server |   File "/usr/local/lib/python2.7/dist-packages/django/core/management/commands/migrate.py", line 204, in handle
dva-server |     fake_initial=fake_initial,
dva-server |   File "/usr/local/lib/python2.7/dist-packages/django/db/migrations/executor.py", line 115, in migrate
dva-server |     state = self._migrate_all_forwards(state, plan, full_plan, fake=fake, fake_initial=fake_initial)
dva-server |   File "/usr/local/lib/python2.7/dist-packages/django/db/migrations/executor.py", line 145, in _migrate_all_forwards
dva-server |     state = self.apply_migration(state, migration, fake=fake, fake_initial=fake_initial)
dva-server |   File "/usr/local/lib/python2.7/dist-packages/django/db/migrations/executor.py", line 244, in apply_migration
dva-server |     state = migration.apply(state, schema_editor)
dva-server |   File "/usr/local/lib/python2.7/dist-packages/django/db/migrations/migration.py", line 129, in apply
dva-server |     operation.database_forwards(self.app_label, schema_editor, old_state, project_state)
dva-server |   File "/usr/local/lib/python2.7/dist-packages/django/db/migrations/operations/models.py", line 97, in database_forwards
dva-server |     schema_editor.create_model(model)
dva-server |   File "/usr/local/lib/python2.7/dist-packages/django/db/backends/base/schema.py", line 303, in create_model
dva-server |     self.execute(sql, params or None)
dva-server |   File "/usr/local/lib/python2.7/dist-packages/django/db/backends/base/schema.py", line 120, in execute
dva-server |     cursor.execute(sql, params)
dva-server |   File "/usr/local/lib/python2.7/dist-packages/django/db/backends/utils.py", line 80, in execute
dva-server |     return super(CursorDebugWrapper, self).execute(sql, params)
dva-server |   File "/usr/local/lib/python2.7/dist-packages/django/db/backends/utils.py", line 65, in execute
dva-server |     return self.cursor.execute(sql, params)
dva-server |   File "/usr/local/lib/python2.7/dist-packages/django/db/utils.py", line 94, in __exit__
dva-server |     six.reraise(dj_exc_type, dj_exc_value, traceback)
dva-server |   File "/usr/local/lib/python2.7/dist-packages/django/db/backends/utils.py", line 63, in execute
dva-server |     return self.cursor.execute(sql)
dva-server | django.db.utils.ProgrammingError: relation "dvaapp_deletedvideo" already exists
dva-server |
dva-server |
dva-server | Fatal error: local() encountered an error (return code 1) while executing 'python manage.py migrate'
dva-server |
dva-server | Aborting.
dva-server | [localhost] local: sleep 20
dva-server | [localhost] local: python manage.py makemigrations
dva-server | [localhost] local: python manage.py migrate
dva-server exited with code 1

## Already tried
`docker-compose down` 
`docker-compose --force-recreate`
reinstall the whole repo but still no use.

**Comment by AKSHAYUBHAT** [comment]
Hi this happened because migration files were deleted. 

If you DONT have any data stored in the volumes you can delete volumes by running 

`docker-compose down -v`

If you DO have data then you can remove "git pull" from docker-compose.yml, start containers and manually perform migration.

**Comment by AKSHAYUBHAT** [comment]
`force-recreate` merely recreates containers however database state is stored in volumes which persist independently and require deleting.

**Comment by e212156822000** [comment]
Thank you very much!! It worked perfectly !
I will be more careful not to delete the database next time.
I followed your guild [here](https://github.com/AKSHAYUBHAT/DeepVideoAnalytics/issues/24#issuecomment-293762929) before to rebuild it.
It seems that `./rebuild.sh` will create containers . That made `docker-compose up` error.
when I deleted all the containers , it worked.

**Comment by AKSHAYUBHAT** [comment]
> I will be more careful not to delete the database next time.

The migration files in `dvaapp/migrations` were deleted by me. Since the data model is rapidly evolving sometimes its not possible to generate migrations correctly. I try to avoid deleting migrations but sometimes its just easy to start from scratch.
