### ISSUE TITLE
License

### ISSUE THREAD

**Issue by samuel-davis** [AKSHAYUBHAT/DeepVideoAnalytics#62]
Sir, 

The license ticket I previously commented on was closed. 

I am creating this one so that when / if you determine to relax the licensing restraints there will be a way to easy way for me to be notified.  

Of course if you choose to keep the license as it is, you can just close the ticket.

**Comment by AKSHAYUBHAT** [comment]
Sure I will keep this open and close once its finalized.

**Comment by AKSHAYUBHAT** [comment]
Still working on this..

**Comment by samuel-davis** [comment]
Awesome great to hear !

**Comment by posix4e** [comment]
Any guidance?

**Comment by AKSHAYUBHAT** [comment]
Hi, Sorry I know this is overdue, but I am still waiting for them.

**Comment by moskiteau** [comment]
+1

**Comment by forseeking** [comment]
+1
