### ISSUE TITLE
Can't access web interface

### ISSUE THREAD

**Issue by ckpearson** [AKSHAYUBHAT/DeepVideoAnalytics#65]
After following the installation instructions, and running the docker-compose up step; I find myself unable to access the web interface.

I've looked for the ip-address with (docker ps | grep IPAddress) and found that, and even seen the ports 80 and 8000 on the docker ps output.

Yet no matter how much I try to access that IP:port combination, the browser always fails to respond.

No 404, but a "could not be reached" style error.

**Comment by AKSHAYUBHAT** [comment]
Are you running on local machine or remote machine?

- If you are running locally did you try localhost:8000 ?

- If you are running on a remote machine can you SSH and do `wget localhost:8000`

**Comment by AKSHAYUBHAT** [comment]
You can also try entering the running dva-server container (see docker/shell.sh in the repo) and check using `ps` etc. If nginx is running.

**Comment by ckpearson** [comment]
Locally, but it worked once I used the docker machine IP :+1:
