### ISSUE TITLE
How to start training indexer model ?

### ISSUE THREAD

**Issue by e212156822000** [AKSHAYUBHAT/DeepVideoAnalytics#66]
## Context of the issue
I'v known that [custom indexer model](https://github.com/AKSHAYUBHAT/DeepVideoAnalytics/issues/34) did not build up in dva , but I wish to investigate this part.
I would like to know if there's any hint I could start with?

## Expected result
made a custom indexer model (ex. obama indexer)

![image](https://user-images.githubusercontent.com/11701668/29441207-29ffc9b2-83fc-11e7-977f-6364f2ed5969.png)

## Already known
how to train [classifier](http://cmusatyalab.github.io/openface/demo-3-classifier/) in OpenFace.

**Comment by AKSHAYUBHAT** [comment]
Hi I will get back to you in couple of days. I am making changes which should make this simple and documented

**Comment by AKSHAYUBHAT** [comment]
@e212156822000 
An indexer refers to a model that generates "feature vectors" (IndexEntries) for a gives of frames / regions. E.g. The facenet indexer generates 128D floating point features for images / regions. Similarly inception generates 2048 dimensional feature vector from pool_3 layer. It seems to me what you are looking for is an "Analyzer" which produces label (e.g. name of the person for given face region). Currently the textbox region -> text recognizer is an example of an analyzer. In this case CRNN which is an "Analyzer". Similarly you can implement an Face Analyzer which labels images using a model that predicts the label. I am currently working on updating the "Open Images Annotation" model which generates text tags for given image / region in this manner. 

Feel free to ask more questions.

**Comment by AKSHAYUBHAT** [comment]
Also note that currently the query processing pipeline can only be used with Indexers & Retrievers. 
However I am working on updating perform_detection and perform_analysis, which would allow creation of query processing task flows that e.g. retrieves similar images, detect objects & label images.
