### ISSUE TITLE
Update instructions for exploring OCR using dvalib

### ISSUE THREAD

**Issue by lisayan** [AKSHAYUBHAT/DeepVideoAnalytics#69]
I was following this instruction, but the link no longer exists.

To run following two notebooks, start docker container (nvidia-docker/GPU preferred) using following script. https://github.com/AKSHAYUBHAT/DeepVideoAnalytics/blob/master/docker/ctpn/run_ocr_container.sh

Is there an updated script or a note for which docker file we should use?

Thanks!

**Comment by AKSHAYUBHAT** [comment]
Hi, I removed the OCR specific container, currently dva-auto:caffe container contains Caffe + TextBox detection algorithm but it does not contains CRNN algorithm. You can manually install PyTorch and then use the script. I will try to write the updated script sometime over the weekend.

**Comment by lisayan** [comment]
Hi, thanks for the quick response!

Just to confirm, is this the dva-auto:caffe container you are talking about?
[(https://github.com/AKSHAYUBHAT/DeepVideoAnalytics/blob/master/docker/dockerfiles/Dockerfile.caffe)]

Also, sorry I am not too familiar with notebooks. Is the TextBox detection algorithm the script in recognize_text.ipynb? Thanks for your work, it's awesome!

**Comment by AKSHAYUBHAT** [comment]
The textbox detection algorithm is in this file/line
https://github.com/AKSHAYUBHAT/DeepVideoAnalytics/blob/master/dvalib/detector.py#L231

The textbox -> text algorithm is in this file/line 
https://github.com/AKSHAYUBHAT/DeepVideoAnalytics/blob/master/dvalib/analyzer.py#L104

**Comment by Chenfu1994** [comment]
Hi sorry, I am a bit unfamiliar with how notebooks work with docker. I pulled the container from the docker hub and ran it with 

`nvidia-docker run -it akshayubhat/dva-auto:caffe`

It prompted me to go to a link for the Jupyter notebook, but I was unable to navigate to that link. Am I supposed to start Jupyter notebook first?

Also, will there be a demo available where we can run the textbox detection algorithm and then textbook -> text algorithm on an image?

Thank you!

**Comment by AKSHAYUBHAT** [comment]
`nvidia-docker run -p 8888:8888 -it akshayubhat/dva-auto:caffe`

Try this command, you need to expose the port.

I will add the tutorial that shows image -> textbox -> text example tonight.

**Comment by lisayan** [comment]
I would definitely be interested in that tutorial too! Thanks so much, looking forward to updates.

**Comment by AKSHAYUBHAT** [comment]
I have updated the readme. Now you can run both detection and recognition in CPU only mode. 
You can find the updated instructions here: https://github.com/AKSHAYUBHAT/DeepVideoAnalytics/tree/master/notebooks/OCR

**Comment by lisayan** [comment]
Thanks for this! When I tried GPU mode, I was only able to run the text detection notebook. When I ran the second notebook, it says ImportError: no module named torch. Do I have to manually install Torch, or should it already exist in the docker container?

**Comment by lisayan** [comment]
Oops sorry, just realized you mentioned CPU only mode. Thank you!
