### ISSUE TITLE
 mv: cannot stat 'docker_GPU/configs/nginx.conf': No such file or directory

### ISSUE THREAD

**Issue by lvbabc** [AKSHAYUBHAT/DeepVideoAnalytics#7]
When I run "sudo ./rebuild.sh && nvidia-docker-compose up" at first time,I could make it work.But after press "Ctrl+C" and run "sudo nvidia-docker-compose up " again，I always meet the following problem：

dva-server | Operations to perform:
dva-server |   Apply all migrations: admin, auth, contenttypes, djcelery, dvaapp, sessions
dva-server | Running migrations:
dva-server |   No migrations to apply.
dva-server | mv: cannot stat 'docker_GPU/configs/nginx.conf': No such file or directory
dva-server | 
dva-server | Fatal error: local() encountered an error (return code 1) while executing 'mv docker_GPU/configs/nginx.conf /etc/nginx/'
dva-server | 
dva-server | Aborting.
dva-server | [localhost] local: sleep 60
dva-server | [localhost] local: python manage.py makemigrations
dva-server | [localhost] local: python manage.py migrate
dva-server | [localhost] local: chmod 0777 -R /tmp
dva-server | [localhost] local: mv docker_GPU/configs/nginx.conf /etc/nginx/
dva-server exited with code 1

Please tell me, what should I do?

**Comment by AKSHAYUBHAT** [comment]
When you run `./rebuild.sh` it should have built the latest version of the container i.e. aub3dva:gpu. 

It is possible that you have an old clone of the repo, run `git pull && sudo nvidia-docker-compose up`

**Comment by AKSHAYUBHAT** [comment]
Alternatively its possible that when you ran ./rebuild.sh it did not store the latest container image.
Try running ./rebuild.sh and check for message at the end. Finally if you are using the AMI you do not need "sudo" since user ubuntu is added group sudo.

**Comment by lvbabc** [comment]
Thanks for your answer.But it dosen`t work.
Once I rebuilt the container with "docker-compose rm && nvidia-docker-compose up",the problem would disappear.But after press "Ctrl+C" and run "nvidia-docker-compose up " ,the problem wuold be back.
And I'm pretty sure the "nginx.conf" file is exist in "docker_GPU/configs/".

**Comment by lvbabc** [comment]
Alternatively I don`t use AMI ,I run this project on my own machine.

**Comment by AKSHAYUBHAT** [comment]
Can you post contents of the docker-compose.yml you are using if its same as the one on master?

Also docker-compose.yml has a command section which you can change to "sleep 3600" and them manually go inside the running container  using shell.sh which is present in the folder. This way you can interactively execute commands and figure out what differs

**Comment by AKSHAYUBHAT** [comment]
Okay I think I know whats happening. 

Pressing ctrl+c merely stops the container but does not removes it.  So when you run up again it starts the container and this time it cannot find the nginx.conf since it has already moved it. I didn't think of this case since I am retaining entire state inside volumes thus you stop & remove containers and state will be retained unless you remove volumes as well. Let me fix this by changing mv to cp

**Comment by lvbabc** [comment]
Thanks！
