### ISSUE TITLE
Installation question

### ISSUE THREAD

**Issue by dickyj** [AKSHAYUBHAT/DeepVideoAnalytics#72]
Hi,
I am new to this project, after running docker-compose up, what is the url and port I need to access to open the console? Thanks.

Dicky

**Comment by AKSHAYUBHAT** [comment]
localhost:8000

On Windows you will need to replace localhost by IP address of the Docker Machine.

**Comment by dickyj** [comment]
Hi, I tried installing on a Mac, but it does not work. I am uploading the screen
<img width="865" alt="screen shot 2017-09-06 at 10 20 28 am" src="https://user-images.githubusercontent.com/6478334/30093193-f05eca72-92ed-11e7-899a-640d88456797.png">

**Comment by AKSHAYUBHAT** [comment]
can you run `docker ps -a` in another terminal copy paste the status.

**Comment by dickyj** [comment]
Ok here it is:
CONTAINER ID        IMAGE                         COMMAND                  CREATED             STATUS                      PORTS                                NAMES
4b517a716aab        akshayubhat/dva-auto:latest   "bash -c 'youtube-..."   24 minutes ago      Up 22 minutes               80/tcp, 0.0.0.0:8000->8000/tcp       dva-server
a08859c07dbc        akshayubhat/dva-auto:latest   "bash -c 'git pull..."   24 minutes ago      Exited (1) 20 minutes ago                                        dva-crnn
0cc50d1df3a1        postgres                      "docker-entrypoint..."   24 minutes ago      Up 22 minutes               5432/tcp                             dva-pg
5b4a37b61ab7        rabbitmq                      "docker-entrypoint..."   24 minutes ago      Up 22 minutes               4369/tcp, 5671-5672/tcp, 25672/tcp   dva-rmq

**Comment by AKSHAYUBHAT** [comment]
Okay can you run

```
docker-compose down -v
git pull
docker-compose up 
```
I just changed docker-compose.yml and there is no dva-crnn container now.

**Comment by AKSHAYUBHAT** [comment]
I tested locally on my mac and it worked make sure you have latest container images from 
https://hub.docker.com/r/akshayubhat/dva-auto/tags/ (last updated 13 days ago)

You should see the UI on http://localhost:8000

**Comment by dickyj** [comment]
Great, the website is up. But when I try to upload an image, and run the "Search By Image", it did not work. Here is the error:

dva-server | [06/Sep/2017 04:32:01] "POST /Search HTTP/1.1" 500 526309
dva-server | [06/Sep/2017 04:34:22] "GET / HTTP/1.1" 200 29518
dva-server | [06/Sep/2017 04:34:22] "GET /static/bootstrap/css/bootstrap.min.css HTTP/1.1" 304 0
dva-server | [06/Sep/2017 04:34:22] "GET /static/dist/css/AdminLTE.min.css HTTP/1.1" 304 0
dva-server | [06/Sep/2017 04:34:22] "GET /static/custom-lte.css HTTP/1.1" 304 0
dva-server | [06/Sep/2017 04:34:22] "GET /static/plugins/datatables/dataTables.bootstrap.css HTTP/1.1" 304 0
dva-server | [06/Sep/2017 04:34:22] "GET /static/app/app.css HTTP/1.1" 304 0
dva-server | [06/Sep/2017 04:34:22] "GET /static/dist/css/skins/_all-skins.min.css HTTP/1.1" 304 0
dva-server | [06/Sep/2017 04:34:22] "GET /static/plugins/jQuery/jquery-2.2.3.min.js HTTP/1.1" 304 0
dva-server | [06/Sep/2017 04:34:22] "GET /static/select2/css/select2.min.css HTTP/1.1" 304 0
dva-server | [06/Sep/2017 04:34:22] "GET /static/select2/css/select2-bootstrap.min.css HTTP/1.1" 304 0
dva-server | [06/Sep/2017 04:34:22] "GET /static/plugins/flot/jquery.flot.js HTTP/1.1" 304 0
dva-server | [06/Sep/2017 04:34:22] "GET /static/plugins/flot/jquery.flot.pie.js HTTP/1.1" 304 0
dva-server | [06/Sep/2017 04:34:22] "GET /static/bootstrap/js/bootstrap.min.js HTTP/1.1" 304 0
dva-server | [06/Sep/2017 04:34:22] "GET /static/plugins/flot/jquery.flot.resize.js HTTP/1.1" 304 0
dva-server | [06/Sep/2017 04:34:22] "GET /static/dist/js/app.min.js HTTP/1.1" 304 0
dva-server | [06/Sep/2017 04:34:22] "GET /static/tables.js HTTP/1.1" 304 0
dva-server | [06/Sep/2017 04:34:22] "GET /static/plugins/datatables/jquery.dataTables.min.js HTTP/1.1" 304 0
dva-server | [06/Sep/2017 04:34:22] "GET /static/plugins/datatables/dataTables.bootstrap.min.js HTTP/1.1" 304 0
dva-server | [06/Sep/2017 04:34:22] "GET /static/select2/js/select2.min.js HTTP/1.1" 304 0
dva-server | [06/Sep/2017 04:34:22] "GET /static/ace/ace.js HTTP/1.1" 304 0
dva-server | [06/Sep/2017 04:34:22] "GET /static/plugins/underscore-min.js HTTP/1.1" 304 0
dva-server | [06/Sep/2017 04:34:22] "GET /static/plugins/jquery.mousewheel.min.js HTTP/1.1" 304 0
dva-server | [06/Sep/2017 04:34:22] "GET /static/vision/pf-segmentation.js HTTP/1.1" 304 0
dva-server | [06/Sep/2017 04:34:22] "GET /static/vision/jsfeat-min.js HTTP/1.1" 304 0
dva-server | [06/Sep/2017 04:34:22] "GET /static/vision/slic-segmentation.js HTTP/1.1" 304 0
dva-server | [06/Sep/2017 04:34:22] "GET /static/vision/dat.gui.min.js HTTP/1.1" 304 0
dva-server | [06/Sep/2017 04:34:22] "GET /static/vision/compatibility.js HTTP/1.1" 304 0
dva-server | [06/Sep/2017 04:34:22] "GET /static/app/utils.js HTTP/1.1" 304 0
dva-server | [06/Sep/2017 04:34:22] "GET /static/app/app_config.js HTTP/1.1" 304 0
dva-server | [06/Sep/2017 04:34:22] "GET /static/fabric/fabric.js HTTP/1.1" 304 0
dva-server | [06/Sep/2017 04:34:22] "GET /static/app/controller.js HTTP/1.1" 304 0
dva-server | [06/Sep/2017 04:34:22] "GET /static/app/app.js HTTP/1.1" 304 0
dva-server | [06/Sep/2017 04:34:22] "GET /static/plotly-latest.min.js HTTP/1.1" 304 0
dva-server | Internal Server Error: /Search
dva-server | Traceback (most recent call last):
dva-server |   File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/exception.py", line 41, in inner
dva-server |     response = get_response(request)
dva-server |   File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 249, in _legacy_get_response
dva-server |     response = self._get_response(request)
dva-server |   File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 187, in _get_response
dva-server |     response = self.process_exception_by_middleware(e, request)
dva-server |   File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 185, in _get_response
dva-server |     response = wrapped_callback(request, *callback_args, **callback_kwargs)
dva-server |   File "/usr/local/lib/python2.7/dist-packages/django/contrib/auth/decorators.py", line 23, in _wrapped_view
dva-server |     return view_func(request, *args, **kwargs)
dva-server |   File "/root/DVA/dvaapp/views.py", line 554, in search
dva-server |     qp.wait()
dva-server |   File "/root/DVA/dvaapp/operations/processing.py", line 279, in wait
dva-server |     raise ValueError(e)
dva-server | ValueError: The operation timed out.
dva-server | ERROR:django.request:Internal Server Error: /Search
dva-server | Traceback (most recent call last):
dva-server |   File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/exception.py", line 41, in inner
dva-server |     response = get_response(request)
dva-server |   File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 249, in _legacy_get_response
dva-server |     response = self._get_response(request)
dva-server |   File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 187, in _get_response
dva-server |     response = self.process_exception_by_middleware(e, request)
dva-server |   File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 185, in _get_response
dva-server |     response = wrapped_callback(request, *callback_args, **callback_kwargs)
dva-server |   File "/usr/local/lib/python2.7/dist-packages/django/contrib/auth/decorators.py", line 23, in _wrapped_view
dva-server |     return view_func(request, *args, **kwargs)
dva-server |   File "/root/DVA/dvaapp/views.py", line 554, in search
dva-server |     qp.wait()
dva-server |   File "/root/DVA/dvaapp/operations/processing.py", line 279, in wait
dva-server |     raise ValueError(e)
dva-server | ValueError: The operation timed out.
dva-server | [06/Sep/2017 04:35:16] "POST /Search HTTP/1.1" 500 463493
dva-server | [2017-09-06 04:35:16,537] - Broken pipe from ('172.18.0.1', 59694)
dva-server | 
dva-server | Internal Server Error: /Search
dva-server | Traceback (most recent call last):
dva-server |   File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/exception.py", line 41, in inner
dva-server |     response = get_response(request)
dva-server |   File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 249, in _legacy_get_response
dva-server |     response = self._get_response(request)
dva-server |   File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 187, in _get_response
dva-server |     response = self.process_exception_by_middleware(e, request)
dva-server |   File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 185, in _get_response
dva-server |     response = wrapped_callback(request, *callback_args, **callback_kwargs)
dva-server |   File "/usr/local/lib/python2.7/dist-packages/django/contrib/auth/decorators.py", line 23, in _wrapped_view
dva-server |     return view_func(request, *args, **kwargs)
dva-server |   File "/root/DVA/dvaapp/views.py", line 554, in search
dva-server |     qp.wait()
dva-server |   File "/root/DVA/dvaapp/operations/processing.py", line 279, in wait
dva-server |     raise ValueError(e)
dva-server | ValueError: The operation timed out.
dva-server | ERROR:django.request:Internal Server Error: /Search
dva-server | Traceback (most recent call last):
dva-server |   File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/exception.py", line 41, in inner
dva-server |     response = get_response(request)
dva-server |   File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 249, in _legacy_get_response
dva-server |     response = self._get_response(request)
dva-server |   File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 187, in _get_response
dva-server |     response = self.process_exception_by_middleware(e, request)
dva-server |   File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 185, in _get_response
dva-server |     response = wrapped_callback(request, *callback_args, **callback_kwargs)
dva-server |   File "/usr/local/lib/python2.7/dist-packages/django/contrib/auth/decorators.py", line 23, in _wrapped_view
dva-server |     return view_func(request, *args, **kwargs)
dva-server |   File "/root/DVA/dvaapp/views.py", line 554, in search
dva-server |     qp.wait()
dva-server |   File "/root/DVA/dvaapp/operations/processing.py", line 279, in wait
dva-server |     raise ValueError(e)
dva-server | ValueError: The operation timed out.
dva-server | [06/Sep/2017 04:35:39] "POST /Search HTTP/1.1" 500 526349

**Comment by AKSHAYUBHAT** [comment]
The very first time it might give a timeout error, since the indexers are busy loading the network or processing the video.

`dva-server | ValueError: The operation timed out.`

You can check, http://localhost:8000/queries page for the results. Since all operations are async it will show up once the results are available.
