### ISSUE TITLE
Server is unable to start - "Could not start indexer"

### ISSUE THREAD

**Issue by Weihnachtswurst** [AKSHAYUBHAT/DeepVideoAnalytics#73]
Environment
-

 - Ubuntu 16.04.3 LTS (Freshly installed)
 - Docker 17.06.2-ce Build cec0b72
 - Docker-Compose 1.16.1 Build 6d1ac21
 - Running inside a vmware-vm. No GPU

Steps to reproduce
-

 - Open a Terminal
 - Run the following commands
                        `git clone https://github.com/AKSHAYUBHAT/DeepVideoAnalytics`
                         `cd DeepVideoAnalytics/docker && docker-compose up`

Error
-

The log indicates that the _dva-server_ `could not import indexer` multiple times resulting in multiple error-reports. See the complete server log below.

The server will hang at the end (waited ~15min) with no further error messages and no significant CPU and/or I/O load.

> sudo docker-compose up
> Starting dva-pg ... 
> Starting dva-rmq ... 
> Starting dva-pg
> Starting dva-pg ... done
> Starting dva-server ... 
> Starting dva-server ... done
> Attaching to dva-rmq, dva-pg, dva-server
> dva-pg    | LOG:  database system was shut down at 2017-09-07 20:41:04 UTC
> dva-pg    | LOG:  MultiXact member wraparound protections are now enabled
> dva-pg    | LOG:  database system is ready to accept connections
> dva-pg    | LOG:  autovacuum launcher started
> dva-server | WARNING: Assuming --restrict-filenames since file system encoding cannot encode all characters. Set the LC_ALL environment variable to fix this.
> dva-server | youtube-dl is up-to-date (2017.09.02)
> dva-rmq   | 
> dva-rmq   |               RabbitMQ 3.6.11. Copyright (C) 2007-2017 Pivotal Software, Inc.
> dva-rmq   |   ##  ##      Licensed under the MPL.  See http://www.rabbitmq.com/
> dva-rmq   |   ##  ##
> dva-rmq   |   ##########  Logs: tty
> dva-rmq   |   ######  ##        tty
> dva-rmq   |   ##########
> dva-rmq   |               Starting broker...
> dva-rmq   | 
> dva-rmq   | =INFO REPORT==== 7-Sep-2017::20:42:46 ===
> dva-rmq   | Starting RabbitMQ 3.6.11 on Erlang 19.2.1
> dva-rmq   | Copyright (C) 2007-2017 Pivotal Software, Inc.
> dva-rmq   | Licensed under the MPL.  See http://www.rabbitmq.com/
> dva-rmq   | 
> dva-rmq   | =INFO REPORT==== 7-Sep-2017::20:42:46 ===
> dva-rmq   | node           : rabbit@99db69b4c636
> dva-rmq   | home dir       : /var/lib/rabbitmq
> dva-rmq   | config file(s) : /etc/rabbitmq/rabbitmq.config
> dva-rmq   | cookie hash    : MPNXRlKJFg+OeWyiRiInmA==
> dva-rmq   | log            : tty
> dva-rmq   | sasl log       : tty
> dva-rmq   | database dir   : /var/lib/rabbitmq/mnesia/rabbit@99db69b4c636
> dva-server | Already up-to-date.
> dva-rmq   | 
> dva-rmq   | =INFO REPORT==== 7-Sep-2017::20:42:48 ===
> dva-rmq   | Memory high watermark set to 2086 MiB (2188217548 bytes) of 5217 MiB (5470543872 bytes) total
> dva-rmq   | 
> dva-rmq   | =INFO REPORT==== 7-Sep-2017::20:42:48 ===
> dva-rmq   | Enabling free disk space monitoring
> dva-rmq   | 
> dva-rmq   | =INFO REPORT==== 7-Sep-2017::20:42:48 ===
> dva-rmq   | Disk free limit set to 50MB
> dva-rmq   | 
> dva-rmq   | =INFO REPORT==== 7-Sep-2017::20:42:48 ===
> dva-rmq   | Limiting to approx 1048476 file handles (943626 sockets)
> dva-rmq   | 
> dva-rmq   | =INFO REPORT==== 7-Sep-2017::20:42:48 ===
> dva-rmq   | FHC read buffering:  OFF
> dva-rmq   | FHC write buffering: ON
> dva-rmq   | 
> dva-rmq   | =INFO REPORT==== 7-Sep-2017::20:42:48 ===
> dva-rmq   | Waiting for Mnesia tables for 30000 ms, 9 retries left
> dva-rmq   | 
> dva-rmq   | =INFO REPORT==== 7-Sep-2017::20:42:48 ===
> dva-rmq   | Waiting for Mnesia tables for 30000 ms, 9 retries left
> dva-rmq   | 
> dva-rmq   | =INFO REPORT==== 7-Sep-2017::20:42:48 ===
> dva-rmq   | Priority queues enabled, real BQ is rabbit_variable_queue
> dva-rmq   | 
> dva-rmq   | =INFO REPORT==== 7-Sep-2017::20:42:48 ===
> dva-rmq   | Starting rabbit_node_monitor
> dva-rmq   | 
> dva-rmq   | =INFO REPORT==== 7-Sep-2017::20:42:48 ===
> dva-rmq   | msg_store_transient: using rabbit_msg_store_ets_index to provide index
> dva-rmq   | 
> dva-rmq   | =INFO REPORT==== 7-Sep-2017::20:42:48 ===
> dva-rmq   | msg_store_persistent: using rabbit_msg_store_ets_index to provide index
> dva-rmq   | 
> dva-rmq   | =INFO REPORT==== 7-Sep-2017::20:42:48 ===
> dva-rmq   | started TCP Listener on [::]:5672
> dva-rmq   |  completed with 0 plugins.
> dva-rmq   | 
> dva-rmq   | =INFO REPORT==== 7-Sep-2017::20:42:49 ===
> dva-rmq   | Server startup complete; 0 plugins started.
> dva-server | WARNING:root:Could not import indexer / clustering assuming running in front-end mode / Heroku
> dva-server | No changes detected
> dva-server | WARNING:root:Could not import indexer / clustering assuming running in front-end mode / Heroku
> dva-server | Operations to perform:
> dva-server |   Apply all migrations: admin, auth, authtoken, contenttypes, django_celery_beat, django_celery_results, dvaapp, sessions
> dva-server | Running migrations:
> dva-server |   No migrations to apply.
> dva-server | [localhost] local: python manage.py makemigrations
> dva-server | [localhost] local: python manage.py migrate
> dva-server | 
> dva-server | Done.
> dva-server | WARNING:root:Could not import indexer / clustering assuming running in front-end mode / Heroku
> dva-server | WARNING:root:Could not import indexer / clustering assuming running in front-end mode / Heroku
> dva-server | Using TensorFlow backend.
> dva-server | WARNING:root:Could not import indexer / clustering assuming running in front-end mode / Heroku
> dva-server | /usr/local/lib/python2.7/dist-packages/celery/platforms.py:793: RuntimeWarning: You're running the worker with superuser privileges: this is
> dva-server | absolutely not recommended!
> dva-server | 
> dva-server | Please specify a different user using the -u option.
> dva-server | 
> dva-server | User information: uid=0 euid=0 gid=0 egid=0
> dva-server | 
> dva-server |   uid=uid, euid=euid, gid=gid, egid=egid,
> dva-rmq   | 
> dva-rmq   | =INFO REPORT==== 7-Sep-2017::20:43:14 ===
> dva-rmq   | accepting AMQP connection <0.360.0> (172.18.0.4:43608 -> 172.18.0.3:5672)
> dva-rmq   | 
> dva-rmq   | =INFO REPORT==== 7-Sep-2017::20:43:14 ===
> dva-rmq   | connection <0.360.0> (172.18.0.4:43608 -> 172.18.0.3:5672): user 'dvauser' authenticated and granted access to vhost '/'
> dva-rmq   | 
> dva-rmq   | =INFO REPORT==== 7-Sep-2017::20:43:14 ===
> dva-rmq   | accepting AMQP connection <0.368.0> (172.18.0.4:43620 -> 172.18.0.3:5672)
> dva-rmq   | 
> dva-rmq   | =INFO REPORT==== 7-Sep-2017::20:43:14 ===
> dva-rmq   | connection <0.368.0> (172.18.0.4:43620 -> 172.18.0.3:5672): user 'dvauser' authenticated and granted access to vhost '/'
> dva-rmq   | 
> dva-rmq   | =INFO REPORT==== 7-Sep-2017::20:43:14 ===
> dva-rmq   | accepting AMQP connection <0.383.0> (172.18.0.4:43622 -> 172.18.0.3:5672)
> dva-rmq   | 
> dva-rmq   | =INFO REPORT==== 7-Sep-2017::20:43:14 ===
> dva-rmq   | connection <0.383.0> (172.18.0.4:43622 -> 172.18.0.3:5672): user 'dvauser' authenticated and granted access to vhost '/'
> dva-server | WARNING:root:Could not import indexer / clustering assuming running in front-end mode / Heroku
> dva-server | Using TensorFlow backend.
> dva-server | WARNING:root:Could not import indexer / clustering assuming running in front-end mode / Heroku
> dva-server | Using TensorFlow backend.
> dva-server | WARNING:root:Could not import indexer / clustering assuming running in front-end mode / Heroku
> dva-server | WARNING:root:Could not import indexer / clustering assuming running in front-end mode / Heroku
> dva-server | WARNING:root:Could not import indexer / clustering assuming running in front-end mode / Heroku
> dva-server | Using TensorFlow backend.
> dva-server | Using TensorFlow backend.
> dva-server | WARNING:root:Could not import indexer / clustering assuming running in front-end mode / Heroku
> dva-server | WARNING:root:Could not import indexer / clustering assuming running in front-end mode / Heroku
> dva-server | WARNING:root:Could not import indexer / clustering assuming running in front-end mode / Heroku
> dva-server | WARNING:root:Could not import indexer / clustering assuming running in front-end mode / Heroku
> dva-server | Using TensorFlow backend.
> dva-server | Using TensorFlow backend.
> dva-server | Using TensorFlow backend.
> dva-server | WARNING:root:Could not import indexer / clustering assuming running in front-end mode / Heroku
> dva-server | Using TensorFlow backend.
> dva-server | Using TensorFlow backend.
> dva-server | libdc1394 error: Failed to initialize libdc1394
> dva-server | WARNING:root:Could not import segmentor!
> dva-server | WARNING:root:Could not import indexer / clustering assuming running in front-end mode / Heroku
> dva-server | /usr/local/lib/python2.7/dist-packages/celery/platforms.py:793: RuntimeWarning: You're running the worker with superuser privileges: this is
> dva-server | absolutely not recommended!
> dva-server | 
> dva-server | Please specify a different user using the -u option.
> dva-server | 
> dva-server | User information: uid=0 euid=0 gid=0 egid=0
> dva-server | 
> dva-server |   uid=uid, euid=euid, gid=gid, egid=egid,
> dva-rmq   | 
> dva-rmq   | =INFO REPORT==== 7-Sep-2017::20:43:24 ===
> dva-rmq   | accepting AMQP connection <0.419.0> (172.18.0.4:43646 -> 172.18.0.3:5672)
> dva-rmq   | 
> dva-rmq   | =INFO REPORT==== 7-Sep-2017::20:43:24 ===
> dva-rmq   | connection <0.419.0> (172.18.0.4:43646 -> 172.18.0.3:5672): user 'dvauser' authenticated and granted access to vhost '/'
> dva-rmq   | 
> dva-rmq   | =INFO REPORT==== 7-Sep-2017::20:43:24 ===
> dva-rmq   | accepting AMQP connection <0.426.0> (172.18.0.4:43648 -> 172.18.0.3:5672)
> dva-rmq   | 
> dva-rmq   | =INFO REPORT==== 7-Sep-2017::20:43:24 ===
> dva-rmq   | connection <0.426.0> (172.18.0.4:43648 -> 172.18.0.3:5672): user 'dvauser' authenticated and granted access to vhost '/'
> dva-rmq   | 
> dva-rmq   | =INFO REPORT==== 7-Sep-2017::20:43:24 ===
> dva-rmq   | accepting AMQP connection <0.444.0> (172.18.0.4:43650 -> 172.18.0.3:5672)
> dva-rmq   | 
> dva-rmq   | =INFO REPORT==== 7-Sep-2017::20:43:24 ===
> dva-rmq   | connection <0.444.0> (172.18.0.4:43650 -> 172.18.0.3:5672): user 'dvauser' authenticated and granted access to vhost '/'
> dva-server | libdc1394 error: Failed to initialize libdc1394
> dva-server | WARNING:root:Could not import segmentor!
> dva-server | WARNING:root:Could not import indexer / clustering assuming running in front-end mode / Heroku
> dva-server | /usr/local/lib/python2.7/dist-packages/celery/platforms.py:793: RuntimeWarning: You're running the worker with superuser privileges: this is
> dva-server | absolutely not recommended!
> dva-server | 
> dva-server | Please specify a different user using the -u option.
> dva-server | 
> dva-server | User information: uid=0 euid=0 gid=0 egid=0
> dva-server | 
> dva-server |   uid=uid, euid=euid, gid=gid, egid=egid,
> dva-rmq   | 
> dva-rmq   | =INFO REPORT==== 7-Sep-2017::20:43:27 ===
> dva-rmq   | accepting AMQP connection <0.474.0> (172.18.0.4:43654 -> 172.18.0.3:5672)
> dva-rmq   | 
> dva-rmq   | =INFO REPORT==== 7-Sep-2017::20:43:27 ===
> dva-rmq   | connection <0.474.0> (172.18.0.4:43654 -> 172.18.0.3:5672): user 'dvauser' authenticated and granted access to vhost '/'
> dva-rmq   | 
> dva-rmq   | =INFO REPORT==== 7-Sep-2017::20:43:27 ===
> dva-rmq   | accepting AMQP connection <0.481.0> (172.18.0.4:43656 -> 172.18.0.3:5672)
> dva-rmq   | 
> dva-rmq   | =INFO REPORT==== 7-Sep-2017::20:43:27 ===
> dva-rmq   | connection <0.481.0> (172.18.0.4:43656 -> 172.18.0.3:5672): user 'dvauser' authenticated and granted access to vhost '/'
> dva-rmq   | 
> dva-rmq   | =INFO REPORT==== 7-Sep-2017::20:43:27 ===
> dva-rmq   | accepting AMQP connection <0.495.0> (172.18.0.4:43658 -> 172.18.0.3:5672)
> dva-rmq   | 
> dva-rmq   | =INFO REPORT==== 7-Sep-2017::20:43:27 ===
> dva-rmq   | connection <0.495.0> (172.18.0.4:43658 -> 172.18.0.3:5672): user 'dvauser' authenticated and granted access to vhost '/'
> dva-server | libdc1394 error: Failed to initialize libdc1394
> dva-server | WARNING:root:Could not import segmentor!
> dva-server | WARNING:root:Could not import indexer / clustering assuming running in front-end mode / Heroku
> dva-server | Stale pidfile exists - Removing it.
> dva-rmq   | 
> dva-rmq   | =INFO REPORT==== 7-Sep-2017::20:43:28 ===
> dva-rmq   | accepting AMQP connection <0.505.0> (172.18.0.4:43664 -> 172.18.0.3:5672)
> dva-rmq   | 
> dva-rmq   | =INFO REPORT==== 7-Sep-2017::20:43:28 ===
> dva-rmq   | connection <0.505.0> (172.18.0.4:43664 -> 172.18.0.3:5672): user 'dvauser' authenticated and granted access to vhost '/'
> dva-server | libdc1394 error: Failed to initialize libdc1394
> dva-server | WARNING:root:Could not import segmentor!
> dva-server | WARNING:root:Could not import indexer / clustering assuming running in front-end mode / Heroku
> dva-server | /usr/local/lib/python2.7/dist-packages/celery/platforms.py:793: RuntimeWarning: You're running the worker with superuser privileges: this is
> dva-server | absolutely not recommended!
> dva-server | 
> dva-server | Please specify a different user using the -u option.
> dva-server | 
> dva-server | User information: uid=0 euid=0 gid=0 egid=0
> dva-server | 
> dva-server |   uid=uid, euid=euid, gid=gid, egid=egid,
> dva-server | libdc1394 error: Failed to initialize libdc1394
> dva-server | WARNING:root:Could not import segmentor!
> dva-server | WARNING:root:Could not import indexer / clustering assuming running in front-end mode / Heroku
> dva-server | libdc1394 error: Failed to initialize libdc1394
> dva-server | WARNING:root:Could not import segmentor!
> dva-server | WARNING:root:Could not import indexer / clustering assuming running in front-end mode / Heroku
> dva-server | /usr/local/lib/python2.7/dist-packages/celery/platforms.py:793: RuntimeWarning: You're running the worker with superuser privileges: this is
> dva-server | absolutely not recommended!
> dva-server | 
> dva-server | Please specify a different user using the -u option.
> dva-server | 
> dva-server | User information: uid=0 euid=0 gid=0 egid=0
> dva-server | 
> dva-server |   uid=uid, euid=euid, gid=gid, egid=egid,
> dva-server | libdc1394 error: Failed to initialize libdc1394
> dva-server | WARNING:root:Could not import segmentor!
> dva-server | WARNING:root:Could not import indexer / clustering assuming running in front-end mode / Heroku
> dva-server | /usr/local/lib/python2.7/dist-packages/celery/platforms.py:793: RuntimeWarning: You're running the worker with superuser privileges: this is
> dva-server | absolutely not recommended!
> dva-server | 
> dva-server | Please specify a different user using the -u option.
> dva-server | 
> dva-server | User information: uid=0 euid=0 gid=0 egid=0
> dva-server | 
> dva-server |   uid=uid, euid=euid, gid=gid, egid=egid,
> dva-server | /usr/local/lib/python2.7/dist-packages/celery/platforms.py:793: RuntimeWarning: You're running the worker with superuser privileges: this is
> dva-server | absolutely not recommended!
> dva-server | 
> dva-server | Please specify a different user using the -u option.
> dva-server | 
> dva-server | User information: uid=0 euid=0 gid=0 egid=0
> dva-server | 
> dva-server |   uid=uid, euid=euid, gid=gid, egid=egid,
> dva-rmq   | 
> dva-rmq   | =INFO REPORT==== 7-Sep-2017::20:43:29 ===
> dva-rmq   | accepting AMQP connection <0.539.0> (172.18.0.4:43674 -> 172.18.0.3:5672)
> dva-rmq   | 
> dva-rmq   | =INFO REPORT==== 7-Sep-2017::20:43:29 ===
> dva-rmq   | connection <0.539.0> (172.18.0.4:43674 -> 172.18.0.3:5672): user 'dvauser' authenticated and granted access to vhost '/'
> dva-rmq   | 
> dva-rmq   | =INFO REPORT==== 7-Sep-2017::20:43:29 ===
> dva-rmq   | accepting AMQP connection <0.546.0> (172.18.0.4:43676 -> 172.18.0.3:5672)
> dva-rmq   | 
> dva-rmq   | =INFO REPORT==== 7-Sep-2017::20:43:29 ===
> dva-rmq   | connection <0.546.0> (172.18.0.4:43676 -> 172.18.0.3:5672): user 'dvauser' authenticated and granted access to vhost '/'
> dva-rmq   | 
> dva-rmq   | =INFO REPORT==== 7-Sep-2017::20:43:29 ===
> dva-rmq   | accepting AMQP connection <0.560.0> (172.18.0.4:43678 -> 172.18.0.3:5672)
> dva-rmq   | 
> dva-rmq   | =INFO REPORT==== 7-Sep-2017::20:43:29 ===
> dva-rmq   | connection <0.560.0> (172.18.0.4:43678 -> 172.18.0.3:5672): user 'dvauser' authenticated and granted access to vhost '/'
> dva-rmq   | 
> dva-rmq   | =INFO REPORT==== 7-Sep-2017::20:43:29 ===
> dva-rmq   | accepting AMQP connection <0.567.0> (172.18.0.4:43680 -> 172.18.0.3:5672)
> dva-rmq   | 
> dva-rmq   | =INFO REPORT==== 7-Sep-2017::20:43:29 ===
> dva-rmq   | connection <0.567.0> (172.18.0.4:43680 -> 172.18.0.3:5672): user 'dvauser' authenticated and granted access to vhost '/'
> dva-rmq   | 
> dva-rmq   | =INFO REPORT==== 7-Sep-2017::20:43:29 ===
> dva-rmq   | accepting AMQP connection <0.574.0> (172.18.0.4:43682 -> 172.18.0.3:5672)
> dva-rmq   | 
> dva-rmq   | =INFO REPORT==== 7-Sep-2017::20:43:29 ===
> dva-rmq   | accepting AMQP connection <0.577.0> (172.18.0.4:43684 -> 172.18.0.3:5672)
> dva-rmq   | 
> dva-rmq   | =INFO REPORT==== 7-Sep-2017::20:43:29 ===
> dva-rmq   | connection <0.577.0> (172.18.0.4:43684 -> 172.18.0.3:5672): user 'dvauser' authenticated and granted access to vhost '/'
> dva-rmq   | 
> dva-rmq   | =INFO REPORT==== 7-Sep-2017::20:43:29 ===
> dva-rmq   | connection <0.574.0> (172.18.0.4:43682 -> 172.18.0.3:5672): user 'dvauser' authenticated and granted access to vhost '/'
> dva-rmq   | 
> dva-rmq   | =INFO REPORT==== 7-Sep-2017::20:43:29 ===
> dva-rmq   | accepting AMQP connection <0.598.0> (172.18.0.4:43686 -> 172.18.0.3:5672)
> dva-rmq   | 
> dva-rmq   | =INFO REPORT==== 7-Sep-2017::20:43:29 ===
> dva-rmq   | connection <0.598.0> (172.18.0.4:43686 -> 172.18.0.3:5672): user 'dvauser' authenticated and granted access to vhost '/'
> dva-server | libdc1394 error: Failed to initialize libdc1394
> dva-rmq   | 
> dva-rmq   | =INFO REPORT==== 7-Sep-2017::20:43:30 ===
> dva-rmq   | accepting AMQP connection <0.607.0> (172.18.0.4:43688 -> 172.18.0.3:5672)
> dva-server | WARNING:root:Could not import segmentor!
> dva-rmq   | 
> dva-rmq   | =INFO REPORT==== 7-Sep-2017::20:43:30 ===
> dva-rmq   | connection <0.607.0> (172.18.0.4:43688 -> 172.18.0.3:5672): user 'dvauser' authenticated and granted access to vhost '/'
> dva-server | WARNING:root:Could not import indexer / clustering assuming running in front-end mode / Heroku
> dva-rmq   | 
> dva-rmq   | =INFO REPORT==== 7-Sep-2017::20:43:30 ===
> dva-rmq   | accepting AMQP connection <0.626.0> (172.18.0.4:43690 -> 172.18.0.3:5672)
> dva-rmq   | 
> dva-rmq   | =INFO REPORT==== 7-Sep-2017::20:43:30 ===
> dva-rmq   | connection <0.626.0> (172.18.0.4:43690 -> 172.18.0.3:5672): user 'dvauser' authenticated and granted access to vhost '/'
> dva-server | /usr/local/lib/python2.7/dist-packages/celery/platforms.py:793: RuntimeWarning: You're running the worker with superuser privileges: this is
> dva-server | absolutely not recommended!
> dva-server | 
> dva-server | Please specify a different user using the -u option.
> dva-server | 
> dva-server | User information: uid=0 euid=0 gid=0 egid=0
> dva-server | 
> dva-server |   uid=uid, euid=euid, gid=gid, egid=egid,
> dva-rmq   | 
> dva-rmq   | =INFO REPORT==== 7-Sep-2017::20:43:30 ===
> dva-rmq   | accepting AMQP connection <0.636.0> (172.18.0.4:43694 -> 172.18.0.3:5672)
> dva-rmq   | 
> dva-rmq   | =INFO REPORT==== 7-Sep-2017::20:43:30 ===
> dva-rmq   | connection <0.636.0> (172.18.0.4:43694 -> 172.18.0.3:5672): user 'dvauser' authenticated and granted access to vhost '/'
> dva-rmq   | 
> dva-rmq   | =INFO REPORT==== 7-Sep-2017::20:43:30 ===
> dva-rmq   | accepting AMQP connection <0.643.0> (172.18.0.4:43696 -> 172.18.0.3:5672)
> dva-rmq   | 
> dva-rmq   | =INFO REPORT==== 7-Sep-2017::20:43:30 ===
> dva-rmq   | connection <0.643.0> (172.18.0.4:43696 -> 172.18.0.3:5672): user 'dvauser' authenticated and granted access to vhost '/'
> dva-rmq   | 
> dva-rmq   | =INFO REPORT==== 7-Sep-2017::20:43:30 ===
> dva-rmq   | accepting AMQP connection <0.657.0> (172.18.0.4:43698 -> 172.18.0.3:5672)
> dva-rmq   | 
> dva-rmq   | =INFO REPORT==== 7-Sep-2017::20:43:30 ===
> dva-rmq   | accepting AMQP connection <0.660.0> (172.18.0.4:43700 -> 172.18.0.3:5672)
> dva-rmq   | 
> dva-rmq   | =INFO REPORT==== 7-Sep-2017::20:43:30 ===
> dva-rmq   | connection <0.657.0> (172.18.0.4:43698 -> 172.18.0.3:5672): user 'dvauser' authenticated and granted access to vhost '/'
> dva-rmq   | 
> dva-rmq   | =INFO REPORT==== 7-Sep-2017::20:43:30 ===
> dva-rmq   | connection <0.660.0> (172.18.0.4:43700 -> 172.18.0.3:5672): user 'dvauser' authenticated and granted access to vhost '/'
> dva-rmq   | 
> dva-rmq   | =INFO REPORT==== 7-Sep-2017::20:43:30 ===
> dva-rmq   | accepting AMQP connection <0.674.0> (172.18.0.4:43702 -> 172.18.0.3:5672)
> dva-rmq   | 
> dva-rmq   | =INFO REPORT==== 7-Sep-2017::20:43:30 ===
> dva-rmq   | connection <0.674.0> (172.18.0.4:43702 -> 172.18.0.3:5672): user 'dvauser' authenticated and granted access to vhost '/'
> dva-server | libdc1394 error: Failed to initialize libdc1394
> dva-server | WARNING:root:Could not import segmentor!
> dva-server | WARNING:root:Could not import indexer / clustering assuming running in front-end mode / Heroku
> dva-rmq   | 
> dva-rmq   | =INFO REPORT==== 7-Sep-2017::20:43:30 ===
> dva-rmq   | accepting AMQP connection <0.688.0> (172.18.0.4:43704 -> 172.18.0.3:5672)
> dva-rmq   | 
> dva-rmq   | =INFO REPORT==== 7-Sep-2017::20:43:30 ===
> dva-rmq   | connection <0.688.0> (172.18.0.4:43704 -> 172.18.0.3:5672): user 'dvauser' authenticated and granted access to vhost '/'
> dva-server | /usr/local/lib/python2.7/dist-packages/celery/platforms.py:793: RuntimeWarning: You're running the worker with superuser privileges: this is
> dva-server | absolutely not recommended!
> dva-server | 
> dva-server | Please specify a different user using the -u option.
> dva-server | 
> dva-server | User information: uid=0 euid=0 gid=0 egid=0
> dva-server | 
> dva-server |   uid=uid, euid=euid, gid=gid, egid=egid,
> dva-server | libdc1394 error: Failed to initialize libdc1394
> dva-server | WARNING:root:Could not import segmentor!
> dva-server | WARNING:root:Could not import indexer / clustering assuming running in front-end mode / Heroku
> dva-server | /usr/local/lib/python2.7/dist-packages/celery/platforms.py:793: RuntimeWarning: You're running the worker with superuser privileges: this is
> dva-server | absolutely not recommended!
> dva-server | 
> dva-server | Please specify a different user using the -u option.
> dva-server | 
> dva-server | User information: uid=0 euid=0 gid=0 egid=0
> dva-server | 
> dva-server |   uid=uid, euid=euid, gid=gid, egid=egid,
> dva-rmq   | 
> dva-rmq   | =INFO REPORT==== 7-Sep-2017::20:43:31 ===
> dva-rmq   | accepting AMQP connection <0.723.0> (172.18.0.4:43710 -> 172.18.0.3:5672)
> dva-rmq   | 
> dva-rmq   | =INFO REPORT==== 7-Sep-2017::20:43:31 ===
> dva-rmq   | connection <0.723.0> (172.18.0.4:43710 -> 172.18.0.3:5672): user 'dvauser' authenticated and granted access to vhost '/'
> dva-rmq   | 
> dva-rmq   | =INFO REPORT==== 7-Sep-2017::20:43:31 ===
> dva-rmq   | accepting AMQP connection <0.740.0> (172.18.0.4:43712 -> 172.18.0.3:5672)
> dva-rmq   | 
> dva-rmq   | =INFO REPORT==== 7-Sep-2017::20:43:31 ===
> dva-rmq   | connection <0.740.0> (172.18.0.4:43712 -> 172.18.0.3:5672): user 'dvauser' authenticated and granted access to vhost '/'
> dva-rmq   | 
> dva-rmq   | =INFO REPORT==== 7-Sep-2017::20:43:31 ===
> dva-rmq   | accepting AMQP connection <0.781.0> (172.18.0.4:43714 -> 172.18.0.3:5672)
> dva-rmq   | 
> dva-rmq   | =INFO REPORT==== 7-Sep-2017::20:43:31 ===
> dva-rmq   | connection <0.781.0> (172.18.0.4:43714 -> 172.18.0.3:5672): user 'dvauser' authenticated and granted access to vhost '/'
> dva-rmq   | 
> dva-rmq   | =INFO REPORT==== 7-Sep-2017::20:43:31 ===
> dva-rmq   | accepting AMQP connection <0.800.0> (172.18.0.4:43716 -> 172.18.0.3:5672)
> dva-rmq   | 
> dva-rmq   | =INFO REPORT==== 7-Sep-2017::20:43:31 ===
> dva-rmq   | connection <0.800.0> (172.18.0.4:43716 -> 172.18.0.3:5672): user 'dvauser' authenticated and granted access to vhost '/'
> dva-rmq   | 
> dva-rmq   | =INFO REPORT==== 7-Sep-2017::20:43:31 ===
> dva-rmq   | accepting AMQP connection <0.808.0> (172.18.0.4:43718 -> 172.18.0.3:5672)
> dva-rmq   | 
> dva-rmq   | =INFO REPORT==== 7-Sep-2017::20:43:31 ===
> dva-rmq   | connection <0.808.0> (172.18.0.4:43718 -> 172.18.0.3:5672): user 'dvauser' authenticated and granted access to vhost '/'
> dva-rmq   | 
> dva-rmq   | =INFO REPORT==== 7-Sep-2017::20:43:31 ===
> dva-rmq   | accepting AMQP connection <0.822.0> (172.18.0.4:43720 -> 172.18.0.3:5672)
> dva-rmq   | 
> dva-rmq   | =INFO REPORT==== 7-Sep-2017::20:43:31 ===
> dva-rmq   | connection <0.822.0> (172.18.0.4:43720 -> 172.18.0.3:5672): user 'dvauser' authenticated and granted access to vhost '/'
> dva-rmq   | 
> dva-rmq   | =INFO REPORT==== 7-Sep-2017::20:45:39 ===
> dva-rmq   | accepting AMQP connection <0.929.0> (172.18.0.1:37260 -> 172.18.0.3:5672)
> dva-rmq   | 
> dva-rmq   | =ERROR REPORT==== 7-Sep-2017::20:45:39 ===
> dva-rmq   | closing AMQP connection <0.929.0> (172.18.0.1:37260 -> 172.18.0.3:5672):
> dva-rmq   | {bad_header,<<"GET / HT">>}
> dva-rmq   | 
> dva-rmq   | =INFO REPORT==== 7-Sep-2017::20:45:40 ===
> dva-rmq   | accepting AMQP connection <0.932.0> (172.18.0.1:37262 -> 172.18.0.3:5672)
> dva-rmq   | 
> dva-rmq   | =ERROR REPORT==== 7-Sep-2017::20:45:40 ===
> dva-rmq   | closing AMQP connection <0.932.0> (172.18.0.1:37262 -> 172.18.0.3:5672):
> dva-rmq   | {bad_header,<<"GET /fav">>}
> dva-rmq   | 
> dva-rmq   | =INFO REPORT==== 7-Sep-2017::20:45:42 ===
> dva-rmq   | accepting AMQP connection <0.938.0> (172.18.0.1:37266 -> 172.18.0.3:5672)
> dva-rmq   | 
> dva-rmq   | =ERROR REPORT==== 7-Sep-2017::20:45:42 ===
> dva-rmq   | closing AMQP connection <0.938.0> (172.18.0.1:37266 -> 172.18.0.3:5672):
> dva-rmq   | {bad_header,<<"GET / HT">>}
> dva-rmq   | 
> dva-rmq   | =INFO REPORT==== 7-Sep-2017::20:45:42 ===
> dva-rmq   | accepting AMQP connection <0.941.0> (172.18.0.1:37268 -> 172.18.0.3:5672)
> dva-rmq   | 
> dva-rmq   | =ERROR REPORT==== 7-Sep-2017::20:45:42 ===
> dva-rmq   | closing AMQP connection <0.941.0> (172.18.0.1:37268 -> 172.18.0.3:5672):
> dva-rmq   | {bad_header,<<"GET /fav">>}
> dva-rmq   | 
> dva-rmq   | =INFO REPORT==== 7-Sep-2017::20:45:43 ===
> dva-rmq   | accepting AMQP connection <0.944.0> (172.18.0.1:37270 -> 172.18.0.3:5672)
> dva-rmq   | 
> dva-rmq   | =ERROR REPORT==== 7-Sep-2017::20:45:43 ===
> dva-rmq   | closing AMQP connection <0.944.0> (172.18.0.1:37270 -> 172.18.0.3:5672):
> dva-rmq   | {bad_header,<<"GET / HT">>}
> dva-rmq   | 
> dva-rmq   | =INFO REPORT==== 7-Sep-2017::20:45:43 ===
> dva-rmq   | accepting AMQP connection <0.947.0> (172.18.0.1:37272 -> 172.18.0.3:5672)
> dva-rmq   | 
> dva-rmq   | =ERROR REPORT==== 7-Sep-2017::20:45:43 ===
> dva-rmq   | closing AMQP connection <0.947.0> (172.18.0.1:37272 -> 172.18.0.3:5672):
> dva-rmq   | {bad_header,<<"GET /fav">>}

**Comment by AKSHAYUBHAT** [comment]
Can you post output of `docker ps -a` and  did you see anything on localhost:8000 (you might need to replace localhost by VM hostname) ?

**Comment by AKSHAYUBHAT** [comment]
Hi, I tested this again, ensuring that I was using latest image of rabbitmq pulled from Docker hub. 
Can you try `docker-compose down -v && docker-compose up`. 

```
dva-rmq | =ERROR REPORT==== 7-Sep-2017::20:45:43 ===
dva-rmq | closing AMQP connection <0.947.0> (172.18.0.1:37272 -> 172.18.0.3:5672):
dva-rmq | {bad_header,<<"GET /fav">>}

```

This looks like RabbitMQ did not spin up correctly.

**Comment by AKSHAYUBHAT** [comment]
Cant reproduce.
