### ISSUE TITLE
Outdated readme.md in /DeepVideoAnalytics/notebooks/OCR/

### ISSUE THREAD

**Issue by Weihnachtswurst** [AKSHAYUBHAT/DeepVideoAnalytics#74]
The readme.md seems to be outdated.

The link given isn't valid anymore:
> To run following two notebooks, start docker container (nvidia-docker/GPU preferred) using following script. https://github.com/AKSHAYUBHAT/DeepVideoAnalytics/blob/master/docker/ctpn/run_ocr_container.sh

It is also not possible to run [recognize_text.ipynb](https://github.com/AKSHAYUBHAT/DeepVideoAnalytics/blob/master/notebooks/OCR/recognize_text.ipynb) although the server was started by `nvidia-docker-compose up` inside /DeepVideoAnalytics/docker/. 

I guess the python notebook needs to be started from within docker to import torch?
If you try to execute  [recognize_text.ipynb](https://github.com/AKSHAYUBHAT/DeepVideoAnalytics/blob/master/notebooks/OCR/recognize_text.ipynb) by console you will get the following error:

       ---------------------------------------------------------------------------
       ModuleNotFoundError                       Traceback (most recent call last)
       <ipython-input-3-85a5c41f6660> in <module>()
       ----> 1 import dvalib.crnn.utils as utils
             2 import dvalib.crnn.dataset as dataset
             3 import torch
             4 from torch.autograd import Variable
             5 from PIL import Image
       
       /home/dnndev/Downloads/DeepVideoAnalytics/dvalib/crnn/utils.py in <module>()
             2 # encoding: utf-8
             3 
             ----> 4 import torch
            5 import torch.nn as nn
            6 import collections

       ModuleNotFoundError: No module named 'torch'

The Deep Video Analysis server runs fine within docker and is accessible from localhost:8000

-------------------------
This issue is __not related__ to #73 since this occurred on another machine.

**Comment by AKSHAYUBHAT** [comment]
Yeah I am working on this, I am adding a CPU version of the Caffe container which will let me add/test OCR notebook and rewrite it. 

In the meantime above error can be fixed by just adding following line to the notebook

`!pip install --no-cache-dir http://download.pytorch.org/whl/cu80/torch-0.1.12.post2-cp27-none-linux_x86_64.whl`

This line executes a shell command (hence the ! prefix) and installs pytorch which is missing in the   new Caffe container.

**Comment by AKSHAYUBHAT** [comment]
I have updated the readme. Now you can run both detection and recognition in CPU only mode.
You can find the updated instructions here: 

https://github.com/AKSHAYUBHAT/DeepVideoAnalytics/tree/master/notebooks/OCR

The new instructions require a single "docker run" or "nvidia-docker run" command to download/run detection & recognition notebooks. I have updated the recognition notebooks and it installs PyTorch / Torchvision which is not present in the Caffe container.
