### ISSUE TITLE
Could not import Indexer {Could not launch}

### ISSUE THREAD

**Issue by bishopchips** [AKSHAYUBHAT/DeepVideoAnalytics#77]
# Hi, after running this command ("# **cd DeepVideoAnalytics/docker && docker-compose up**"), this is what I get. What should I do?

Run 'docker COMMAND --help' for more information on a command.
Starting dva-pg ... 
Starting dva-pg
Starting dva-rmq ... 
Starting dva-pg ... done
Starting dva-server ... 
Starting dva-server ... done
Attaching to dva-rmq, dva-pg, dva-server
dva-pg    | LOG:  database system was shut down at 2017-09-16 05:10:30 UTC
dva-pg    | LOG:  MultiXact member wraparound protections are now enabled
dva-pg    | LOG:  database system is ready to accept connections
dva-pg    | LOG:  autovacuum launcher started
dva-rmq   | 
dva-rmq   | =INFO REPORT==== 16-Sep-2017::05:11:29 ===
dva-rmq   | Starting RabbitMQ 3.6.12 on Erlang 19.2.1
dva-rmq   | Copyright (C) 2007-2017 Pivotal Software, Inc.
dva-rmq   | Licensed under the MPL.  See http://www.rabbitmq.com/
dva-rmq   | 
dva-rmq   |               RabbitMQ 3.6.12. Copyright (C) 2007-2017 Pivotal Software, Inc.
dva-rmq   |   ##  ##      Licensed under the MPL.  See http://www.rabbitmq.com/
dva-rmq   |   ##  ##
dva-rmq   |   ##########  Logs: tty
dva-rmq   |   ######  ##        tty
dva-rmq   |   ##########
dva-rmq   |               Starting broker...
dva-rmq   | 
dva-rmq   | =INFO REPORT==== 16-Sep-2017::05:11:29 ===
dva-rmq   | node           : rabbit@744c881ffbee
dva-rmq   | home dir       : /var/lib/rabbitmq
dva-rmq   | config file(s) : /etc/rabbitmq/rabbitmq.config
dva-rmq   | cookie hash    : hP4KSdywPloR9wBbyzNguQ==
dva-rmq   | log            : tty
dva-rmq   | sasl log       : tty
dva-rmq   | database dir   : /var/lib/rabbitmq/mnesia/rabbit@744c881ffbee
dva-server | WARNING: Assuming --restrict-filenames since file system encoding cannot encode all characters. Set the LC_ALL environment variable to fix this.
dva-server | youtube-dl is up-to-date (2017.09.15)
dva-rmq   | 
dva-rmq   | =INFO REPORT==== 16-Sep-2017::05:11:30 ===
dva-rmq   | Memory high watermark set to 3154 MiB (3307873894 bytes) of 7886 MiB (8269684736 bytes) total
dva-rmq   | 
dva-rmq   | =INFO REPORT==== 16-Sep-2017::05:11:30 ===
dva-rmq   | Enabling free disk space monitoring
dva-rmq   | 
dva-rmq   | =INFO REPORT==== 16-Sep-2017::05:11:30 ===
dva-rmq   | Disk free limit set to 50MB
dva-rmq   | 
dva-rmq   | =INFO REPORT==== 16-Sep-2017::05:11:30 ===
dva-rmq   | Limiting to approx 1048476 file handles (943626 sockets)
dva-rmq   | 
dva-rmq   | =INFO REPORT==== 16-Sep-2017::05:11:30 ===
dva-rmq   | FHC read buffering:  OFF
dva-rmq   | FHC write buffering: ON
dva-rmq   | 
dva-rmq   | =INFO REPORT==== 16-Sep-2017::05:11:30 ===
dva-rmq   | Waiting for Mnesia tables for 30000 ms, 9 retries left
dva-rmq   | 
dva-rmq   | =INFO REPORT==== 16-Sep-2017::05:11:31 ===
dva-rmq   | Waiting for Mnesia tables for 30000 ms, 9 retries left
dva-rmq   | 
dva-rmq   | =INFO REPORT==== 16-Sep-2017::05:11:31 ===
dva-rmq   | Priority queues enabled, real BQ is rabbit_variable_queue
dva-rmq   | 
dva-rmq   | =INFO REPORT==== 16-Sep-2017::05:11:31 ===
dva-rmq   | Starting rabbit_node_monitor
dva-rmq   | 
dva-rmq   | =INFO REPORT==== 16-Sep-2017::05:11:31 ===
dva-rmq   | msg_store_transient: using rabbit_msg_store_ets_index to provide index
dva-rmq   | 
dva-rmq   | =INFO REPORT==== 16-Sep-2017::05:11:31 ===
dva-rmq   | msg_store_persistent: using rabbit_msg_store_ets_index to provide index
dva-rmq   | 
dva-rmq   | =INFO REPORT==== 16-Sep-2017::05:11:31 ===
dva-rmq   | started TCP Listener on [::]:5672
dva-rmq   |  completed with 0 plugins.
dva-rmq   | 
dva-rmq   | =INFO REPORT==== 16-Sep-2017::05:11:31 ===
dva-rmq   | Server startup complete; 0 plugins started.
dva-server | Already up-to-date.
dva-server | WARNING:root:Could not import indexer / clustering assuming running in front-end mode / Heroku
dva-server | No changes detected
dva-server | WARNING:root:Could not import indexer / clustering assuming running in front-end mode / Heroku
dva-server | Operations to perform:
dva-server |   Apply all migrations: admin, auth, authtoken, contenttypes, django_celery_beat, django_celery_results, dvaapp, sessions
dva-server | Running migrations:
dva-server |   No migrations to apply.
dva-server | [localhost] local: python manage.py makemigrations
dva-server | [localhost] local: python manage.py migrate
dva-server | 
dva-server | Done.

**Comment by AKSHAYUBHAT** [comment]
Can you post output of `docker ps -a` and `docker image ls` ?

**Comment by bishopchips** [comment]
docker ps -a
CONTAINER ID        IMAGE                         COMMAND                  CREATED             STATUS              PORTS                                            NAMES
0526a194de53        akshayubhat/dva-auto:latest   "bash -c 'youtube-..."   10 hours ago        Up 9 hours          80/tcp, 0.0.0.0:8000->8000/tcp                   dva-server
744c881ffbee        rabbitmq                      "docker-entrypoint..."   10 hours ago        Up 9 hours          4369/tcp, 5671-5672/tcp, 25672/tcp               dva-rmq
41e77666b838        postgres                      "docker-entrypoint..."   10 hours ago        Up 9 hours          5432/tcp                                         dva-pg

docker image ls
REPOSITORY                                      TAG                 IMAGE ID            CREATED             SIZE
alpine                                          latest              76da55c8019d        3 days ago          3.97MB
postgres                                        latest              f5b23ab70487        3 days ago          265MB
akshayubhat/dva-auto                            latest              47baf29704b3        3 days ago          2.78GB
rabbitmq                                        latest              b961a046021b        3 days ago          124MB
h

**Comment by AKSHAYUBHAT** [comment]
Can you go to localhost:8000 or IP of the Docker Machine. It seems it's running.

**Comment by bishopchips** [comment]
Thank You so much. Its Running with a different IP Address. I was only trying with
 localhost:8000.
