### ISSUE TITLE
How to train new model crnn.pth?

### ISSUE THREAD

**Issue by lisayan** [AKSHAYUBHAT/DeepVideoAnalytics#78]
I got the end-to-end system to work with GPU, thanks so much for answering all of my questions quickly!

I'm working on how to train a model to recognize symbols in addition to alphabet, and I want to train a new one. I was wondering, what were the steps that you used to train the model? I was looking at the tips in https://github.com/bgshih/crnn, but I'm not sure if that outputs the same kind of model that you have?

Thanks for your help!

**Comment by AKSHAYUBHAT** [comment]
It's exactly the same model. You just need to change the list/string of symbols and trained model.
