### ISSUE TITLE
Environment

### ISSUE THREAD

**Issue by wrongbattery** [AKSHAYUBHAT/DeepVideoAnalytics#79]
Is there away for me to run you repo without using Docker?

**Comment by AKSHAYUBHAT** [comment]
Yes its possible, you will have to manually install requirements in Dockerfile and requirements.txt .
And then ensure correct set of environment variables e.g, DATABASE & RabbitMQ creds etc.

**Comment by wrongbattery** [comment]
I run your repo with Docker + window 10 but fail? is it because of OS?

**Comment by AKSHAYUBHAT** [comment]
Can you post the error message?

**Comment by wrongbattery** [comment]
A huge of warning messages and then error messages 
[error1.txt](https://github.com/AKSHAYUBHAT/DeepVideoAnalytics/files/1415301/error1.txt)
[error2.txt](https://github.com/AKSHAYUBHAT/DeepVideoAnalytics/files/1415303/error2.txt)

**Comment by AKSHAYUBHAT** [comment]
How much memory do you have? You need at least 8Gb for the code to run.

```
dva-rmq   | ERROR: "Free disk space monitor encountered an error (e.g. failed to parse output from OS tools): ~p, retries left: ~s~n" - [{{'EXIT',
dva-rmq   |                                                                                                                                {unparseable,
dva-rmq   |                                                                                                                                 "/bin/sh: 1: /bin/df: Cannot allocate memory\n"}},
dva-rmq   |                                                                                                                               1044119552},

```

It seems you are running out of memory.

**Comment by wrongbattery** [comment]
8 GB, no GPU, when running i see that your repo only use 80MB of my RAM before it's fail.
I use toolbox to install Docker since my Window doesn't have Hyper-V

**Comment by AKSHAYUBHAT** [comment]
How much memory is allocated to Docker Machine VM?

**Comment by wrongbattery** [comment]
5GB, 2 CPU, it's doesnt  fail but get stuck here
![2017-10-26 5](https://user-images.githubusercontent.com/16754474/32049136-1b6ca6da-ba76-11e7-8828-4a78b1e2f327.png)

**Comment by wrongbattery** [comment]
Is it because i dont have GPU?

**Comment by wrongbattery** [comment]
[error.txt](https://github.com/AKSHAYUBHAT/DeepVideoAnalytics/files/1418091/error.txt)

**Comment by AKSHAYUBHAT** [comment]
can you go to port 8000 of your docker machine IP address
it looks like its working.

**Comment by wrongbattery** [comment]
I set up in Linux it works ok but not for VM+Window

**Comment by AKSHAYUBHAT** [comment]
On windows you might need to find the IP address of the Docker Machine VM and ensure that the correct VM port is open etc.
