### ISSUE TITLE
some small mistakes

### ISSUE THREAD

**Issue by nanqiangyipo** [AKSHAYUBHAT/DeepVideoAnalytics#80]
1. I setup the system using the `docker-compose-gpu.yml` script in single directory.I can't browse the home page. However. Because the dva service binds a wrong port .Nginx listens port 80, while dva service binds 8000 port to 80 port

2. The retry_task method redirects to a wrong address '/processes/', it might be '/processes'.

**Comment by AKSHAYUBHAT** [comment]
Regarding 1, I am using nginx (port 8000) <->u wsgi <-> dva server processes, the uwsgi <-> nginx happens through a file socket. 

https://github.com/AKSHAYUBHAT/DeepVideoAnalytics/blob/master/configs/uwsgi.ini#L5

If you are using docker-compose-gpu.yml for development and would prefer to not use NGINX at all, you can remove LAUNCH_SERVER_NGINX 

https://github.com/AKSHAYUBHAT/DeepVideoAnalytics/blob/master/deploy/single/docker-compose-gpu.yml#L32

Regarding retry_task I need to update implementation of retry_task. Now that DVA has a scheduler that regularly monitors the system, it might be possible to do auto retries and expiries.

**Comment by nanqiangyipo** [comment]
Thank you very much . I'm trying to catch up you  .
