### ISSUE TITLE
Cannot access UI

### ISSUE THREAD

**Issue by srbistline** [AKSHAYUBHAT/DeepVideoAnalytics#82]
After following the installation instructions, and running the "docker-compose up" I cannot access the UI.

I tried "http://localhost:8000"

I have run the following "docker exec -i -t adcccb239f97 /bin/bash" and ran a PS looking for "nginx" but the process is not running.

Any assistance would be very much appreciated.

**Comment by AKSHAYUBHAT** [comment]
- Can your check/post output of `docker logs dva-server`?
- Which compose file are you using? Is it `deploy/demo/docker-compose.yml` or the GPU version? 
- Are you running on Windows? In which case you should use IP address of Docker machine instead of localhost. 

Finally you can manually inspect logs in /logs folder inside the container after entering running container with docker exec.

**Comment by srbistline** [comment]
I have attached the output of the "docker logs dva-server" command.

Steve
[log.txt](https://github.com/AKSHAYUBHAT/DeepVideoAnalytics/files/1424558/log.txt)

**Comment by AKSHAYUBHAT** [comment]
Can you run `docker ps -a` and check if postgres container (dva-pg) is running? 
From logs it appears it DB container is down. 

```
Internal Server Error: /
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 249, in _legacy_get_response
    response = self._get_response(request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/contrib/auth/decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/root/DVA/dvaui/views.py", line 420, in index
    for i in DeepModel.objects.filter(model_type=DeepModel.INDEXER):
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 250, in __iter__
    self._fetch_all()
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 1118, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 53, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/sql/compiler.py", line 882, in execute_sql
    cursor = self.connection.cursor()
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/base/base.py", line 254, in cursor
    return self._cursor()
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/base/base.py", line 229, in _cursor
    self.ensure_connection()
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/base/base.py", line 213, in ensure_connection
    self.connect()
  File "/usr/local/lib/python2.7/dist-packages/django/db/utils.py", line 94, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/base/base.py", line 213, in ensure_connection
    self.connect()
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/base/base.py", line 189, in connect
    self.connection = self.get_new_connection(conn_params)
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/postgresql/base.py", line 176, in get_new_connection
    connection = Database.connect(**conn_params)
  File "/usr/local/lib/python2.7/dist-packages/psycopg2/__init__.py", line 130, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
OperationalError: server closed the connection unexpectedly
        This probably means the server terminated abnormally
        before or while processing the request.
```

**Comment by srbistline** [comment]
Here is what I get from "docker ps -a"

====================================

C:\Users\Owner\Documents\Development\DeepVideoAnalytics\deploy\demo>docker ps -a
CONTAINER ID        IMAGE                                            COMMAND                  CREATED             STATUS                     PORTS               NAMES
adcccb239f97        akshayubhat/dva-auto:latest                      "bash -c 'youtube-..."   3 hours ago         Exited (137) 2 hours ago                       dva-server
d51a3b666aa6        p7hb/p7hb-docker-mllib-twitter-sentiment:1.6.2   "/bin/sh -c 'bash ..."   3 days ago          Exited (0) 3 days ago                          spark
17d334382f1c        akshayubhat/dva-auto:caffe-cpu                   "bash -c 'sleep 60..."   6 days ago          Exited (255) 3 hours ago   8888/tcp            dva-caffe
4f83c2d2c681        rabbitmq                                         "docker-entrypoint..."   6 days ago          Exited (137) 2 hours ago                       dva-rmq
ba89204b1e5a        postgres                                         "docker-entrypoint..."   6 days ago          Exited (137) 2 hours ago                       dva-pg
cb544db08a72        nginx                                            "nginx -g 'daemon ..."   6 days ago          Exited (137) 6 days ago                        webserver
5032ed9badb7        ubuntu                                           "bash"                   6 days ago          Exited (0) 6 days ago                          dazzling_heyrovsky
e6c0aeafa657        hello-world                                      "/hello"                 6 days ago          Exited (0) 6 days ago                          angry_mahavira

C:\Users\Owner\Documents\Development\DeepVideoAnalytics\deploy\demo>

**Comment by srbistline** [comment]
Ok... now have these running, but still no UI


C:\Users\Owner\Documents\Development\DeepVideoAnalytics\deploy\demo>docker ps
CONTAINER ID        IMAGE                         COMMAND                  CREATED             STATUS              PORTS                                NAMES
adcccb239f97        akshayubhat/dva-auto:latest   "bash -c 'youtube-..."   3 hours ago         Up 2 minutes        80/tcp, 0.0.0.0:8000->8000/tcp       dva-server
4f83c2d2c681        rabbitmq                      "docker-entrypoint..."   6 days ago          Up 2 minutes        4369/tcp, 5671-5672/tcp, 25672/tcp   dva-rmq
ba89204b1e5a        postgres                      "docker-entrypoint..."   6 days ago          Up 2 minutes        5432/tcp                             dva-pg

C:\Users\Owner\Documents\Development\DeepVideoAnalytics\deploy\demo>

**Comment by srbistline** [comment]
Well, for some reason it just decided to work. 

I have started and stopped multiple times and the UI never came up. 

Guess it knew you were on the case and decided to cooperate ;-)

Thanks for the assistance.

**Comment by AKSHAYUBHAT** [comment]
When you run `docker-compose down -v` make sure you use `-v` to remove existing volumes associated with the containers. Also when DVA is started for the first time, it will download weights for models (recognition, detection, analysis etc.) as a result it might take several minutes for the UI to be launched. You can monitor/tail the `docker log`.

**Comment by tuyoisaza** [comment]
Hi! you give this clue: "in Windows: In which case you should use IP address of Docker machine instead of localhost."  I been trying to get this Ip adress of the docker machine with no luck, so i cant acess the running container! 
an you assist?

Thanks for the great work!
