### ISSUE TITLE
Questions about dataset

### ISSUE THREAD

**Issue by hyche** [AKSHAYUBHAT/DeepVideoAnalytics#84]
Hi,
I read this documents but it does not show anything except the titles https://github.com/AKSHAYUBHAT/DeepVideoAnalytics/tree/master/notebooks

I have checked 2 of your sample dataset: lfw and MSCOCO
They all have audio, detection, frames, indexes and video, and there are some json and binary files (npy) in  the indexes. Also, lfw dataset has lfw_tunneled directory in frames, is that original lfw database ?
Can you tell me what are the purposes of these ? and how can I format my own dataset to use it in your platform ?

Thanks

**Comment by AKSHAYUBHAT** [comment]
Hi, I will push documentation for schema here soon. 
https://github.com/VisualDataNetwork/visualdatanetwork.github.io

> is that original lfw database ?

Not its subset of LFW with at most 2 images per identity.
