### ISSUE TITLE
Because external causes, I can not download models from dropbox. If I manually download all models, Which fold should i put these models into in the docker environment? 

### ISSUE THREAD

**Issue by doudoubean** [AKSHAYUBHAT/DeepVideoAnalytics#85]

**Comment by AKSHAYUBHAT** [comment]
There are several solutions from simplest to most difficult:

1. Modify urls in [models.json](https://github.com/AKSHAYUBHAT/DeepVideoAnalytics/blob/master/configs/models.json)

2. Change download_models in [fablfile.py](https://github.com/AKSHAYUBHAT/DeepVideoAnalytics/blob/master/fabfile.py#L506) , e.g. as you can see that on my local MacOSX i simply copy from another directory. You can mount a local directory containing those files as a volume and simply copy from there.

**Comment by doudoubean** [comment]
thanks, let me try!

**Comment by doudoubean** [comment]
hi，I change download_models in fabfile.py. moreover ，i hava already mounted a local directory containing those files as a volume. They are shown as follows.
![image](https://user-images.githubusercontent.com/7455568/34237565-53d594ee-e638-11e7-9ac4-200fefcb80d6.png)
![image](https://user-images.githubusercontent.com/7455568/34237657-d4df3b94-e638-11e7-923f-8322ec96549d.png)

*************************************************************************************************************
version: '3'
 services:
   db:
     image: postgres:9.6.6
     container_name: dva-pg
     volumes:
      - dvapgdata:/var/lib/postgresql/data
      - modeldata:/home/yangzhanku/model/dva_model
     environment:
      - POSTGRES_USER=pgdbuser
      - POSTGRES_PASSWORD=pgdbpass
   rabbit:
     image: rabbitmq
     container_name: dva-rmq
     environment:
       - RABBITMQ_DEFAULT_USER=dvauser
       - RABBITMQ_DEFAULT_PASS=localpass
     volumes:
       - dvarabbit:/var/lib/rabbitmq
       - modeldata:/home/yangzhanku/model/dva_model
   dva:
     image: akshayubhat/dva-auto:gpu
     container_name: dva-server
     environment:
       - DOCKER_MODE=true
       - RABBIT_HOST=rabbit
       - RABBIT_USER=dvauser
       - RABBIT_PASS=localpass
       - GPU_AVAILABLE=1
       - DB_HOST=db
       - DB_NAME=postgres
       - DB_USER=pgdbuser
       - DB_PASS=pgdbpass
       - LAUNCH_SERVER_NGINX=1
       - SUPERUSER=akshay
       - SUPERPASS=super
       - SUPEREMAIL=akshay@deepvideoanalytics.com
       - LAUNCH_BY_NAME_indexer_inception=1
       - LAUNCH_BY_NAME_indexer_facenet=1
       - LAUNCH_BY_NAME_retriever_inception=1
       - LAUNCH_BY_NAME_retriever_facenet=1
       - LAUNCH_BY_NAME_detector_coco=1
       - LAUNCH_BY_NAME_analyzer_crnn=1
       - LAUNCH_BY_NAME_detector_face=1
       - LAUNCH_BY_NAME_detector_textbox=1
       - LAUNCH_Q_qclusterer=1
       - LAUNCH_Q_qextract=1
       - LAUNCH_Q_qtrainer=1
       - TEST=1
       - AUTH_DISABLED=1
     command: bash -c "youtube-dl -U && git pull && sleep 10 && fab migrate && fab start_container:server"
     ports:
       - "8000:80"
       - "9999:8888"
     depends_on:
       - db
       - rabbit
     volumes:
       - dvadata:/root/DVA/dva/media
       - modeldata:/home/yangzhanku/model/dva_model
 volumes:
  dvapgdata:
  dvadata:
  dvarabbit:
  modeldata:
*********************************************************************************************************
However，when i run deepvideoanalytics project，the program still download all models from dropbox website。

**Comment by AKSHAYUBHAT** [comment]
Hey I have fixed this. Now to customize you can simply mount a new docker volume at /root/DVA/configs/custom_defaults/ the volume must contain a defaults.py. 
If the url starts with / it will simply copy the file otherwise it will download. 

- https://github.com/AKSHAYUBHAT/DeepVideoAnalytics/tree/master/configs/custom_defaults
- https://github.com/AKSHAYUBHAT/DeepVideoAnalytics/blob/master/configs/custom_defaults/defaults.py
