### ISSUE TITLE
docker-compose up  but  some problem for me 

### ISSUE THREAD

**Issue by debin168** [AKSHAYUBHAT/DeepVideoAnalytics#86]
root@ubuntu:~/DeepVideoAnalytics/deploy/demo# docker-compose build & docker-compose up
[1] 6657
Pulling rabbit (rabbitmq:latest)...
db uses an image, skipping
rabbit uses an image, skipping
dva uses an image, skipping
latest: Pulling from library/rabbitmq
bc95e04b23c0: Already exists
41a230aa3726: Already exists
9190ffbd2271: Already exists
69e829d8f0d2: Waiting      

 always stay herer ,not go on , what's problem for me .thank you for you help

**Comment by AKSHAYUBHAT** [comment]
This looks like an error with Docker rather than with DVA.
Try just pulling rabbitmq from docker hub, by running command below.

`docker pull rabbitmq`

**Comment by debin168** [comment]
thank u for you help  ,it casue by GFW,  i  chang the vps area, so this proble is not happen
