### ISSUE TITLE
hi, why it's  unauthorized when i run docker-compose up  

### ISSUE THREAD

**Issue by debin168** [AKSHAYUBHAT/DeepVideoAnalytics#87]
2f2a774ee350: Waiting
54007ae909b0: Waiting
789dfa1b0839: Waiting
ERROR: unauthorized: authentication required

**Comment by AKSHAYUBHAT** [comment]
These seems like a docker error, you might need to login on to the docker hub. 
https://docs.docker.com/engine/reference/commandline/login/#options
