### ISSUE TITLE
Container status like this, how should i  access ui ,  http://vps ip address:8000   like it ,can't access

### ISSUE THREAD

**Issue by debin168** [AKSHAYUBHAT/DeepVideoAnalytics#88]
CONTAINER ID        IMAGE                         COMMAND                  CREATED             STATUS              PORTS                                NAMES
76a69fd821fd        akshayubhat/dva-auto:latest   "bash -c 'youtube-..."   13 minutes ago      Up 8 seconds        80/tcp, 0.0.0.0:8000->8000/tcp       dva-server
32c8156de396        postgres                      "docker-entrypoint..."   13 minutes ago      Up 13 minutes       5432/tcp                             dva-pg
2c9e15055188        rabbitmq                      "docker-entrypoint..."   13 minutes ago      Up 13 minutes       4369/tcp, 5671-5672/tcp, 25672/tcp   dva-rmq

**Comment by AKSHAYUBHAT** [comment]
For the VPS you need to ensure that the port is opened or tunnelled via ssh. 
e.g. I use this file to launch on Linode (a VPS provider) 

https://github.com/AKSHAYUBHAT/DeepVideoAnalytics/blob/master/deploy/single/docker-compose-linode.yml#L51
