### ISSUE TITLE
on the vps ,i set ufw disable and use docker-compose -f docker-compose-linode.yml up  ，the result is like follow ,but i  access http://x.x.x.x:8000  is still  can't access ui ,what should i do other's work?

### ISSUE THREAD

**Issue by debin168** [AKSHAYUBHAT/DeepVideoAnalytics#89]
dva-server   |
dva-server   | Done.
dva-rmq      |
dva-rmq      | =INFO REPORT==== 21-Nov-2017::05:27:12 ===
dva-rmq      | accepting AMQP connection <0.369.0> (172.18.0.5:54376 -> 172.18.0.2:5672)
dva-rmq      |
dva-rmq      | =INFO REPORT==== 21-Nov-2017::05:27:12 ===
dva-rmq      | connection <0.369.0> (172.18.0.5:54376 -> 172.18.0.2:5672): user 'dvauser' authenticated and granted access to vhost '/'
dva-caffe    | From https://github.com/akshayubhat/DeepVideoAnalytics
dva-caffe    |    0ca8a7b..0657c64  master     -> origin/master
dva-caffe    | Updating 0ca8a7b..0657c64
dva-caffe    | Fast-forward
dva-caffe    |  .travis.yml                   |   5 +-
dva-caffe    |  deploy/cloud/readme.md        |   2 +-
dva-caffe    |  dva/settings.py               |  15 ++--
dva-caffe    |  dvaapp/operations/indexing.py |   8 +-
dva-caffe    |  dvaapp/processing.py          |   2 +-
dva-caffe    |  dvaapp/tasks.py               |  12 ++-
dva-caffe    |  dvalib/indexer.py             | 125 ++++++++++++++--------------
dva-caffe    |  dvaui/view_shared.py          |   4 +-
dva-caffe    |  tests/debug/tf_dataset.ipynb  | 184 ------------------------------------------
dva-caffe    |  9 files changed, 95 insertions(+), 262 deletions(-)
dva-caffe    |  delete mode 100644 tests/debug/tf_dataset.ipynb
dva-caffe    | libdc1394 error: Failed to initialize libdc1394
dva-caffe    | libdc1394 error: Failed to initialize libdc1394
dva-caffe    | WARNING:root:Could not import indexer / clustering assuming running in front-end mode / Heroku
dva-caffe    | WARNING:root:Could not import indexer / clustering assuming running in front-end mode / Heroku
dva-caffe    | WARNING:root:Could not import indexer / clustering assuming running in front-end mode / Heroku
dva-caffe    | WARNING:root:Could not import indexer / clustering assuming running in front-end mode / Heroku
dva-caffe    | /usr/local/lib/python2.7/dist-packages/celery/platforms.py:793: RuntimeWarning: You're running the worker with superuser privileges: this is
dva-caffe    | absolutely not recommended!
dva-caffe    |
dva-caffe    | Please specify a different user using the -u option.
dva-caffe    |
dva-caffe    | User information: uid=0 euid=0 gid=0 egid=0
dva-caffe    |
dva-caffe    |   uid=uid, euid=euid, gid=gid, egid=egid,
dva-caffe    | /usr/local/lib/python2.7/dist-packages/celery/platforms.py:793: RuntimeWarning: You're running the worker with superuser privileges: this is
dva-caffe    | absolutely not recommended!
dva-caffe    |
dva-caffe    | Please specify a different user using the -u option.
dva-caffe    |
dva-caffe    | User information: uid=0 euid=0 gid=0 egid=0
dva-caffe    |
dva-caffe    |   uid=uid, euid=euid, gid=gid, egid=egid,
dva-rmq      |
dva-rmq      | =INFO REPORT==== 21-Nov-2017::05:30:21 ===
dva-rmq      | accepting AMQP connection <0.409.0> (172.18.0.4:38060 -> 172.18.0.2:5672)
dva-rmq      |
dva-rmq      | =INFO REPORT==== 21-Nov-2017::05:30:21 ===
dva-rmq      | connection <0.409.0> (172.18.0.4:38060 -> 172.18.0.2:5672): user 'dvauser' authenticated and granted access to vhost '/'
dva-rmq      |
dva-rmq      | =INFO REPORT==== 21-Nov-2017::05:30:21 ===
dva-rmq      | accepting AMQP connection <0.416.0> (172.18.0.4:38062 -> 172.18.0.2:5672)
dva-rmq      |
dva-rmq      | =INFO REPORT==== 21-Nov-2017::05:30:22 ===
dva-rmq      | connection <0.416.0> (172.18.0.4:38062 -> 172.18.0.2:5672): user 'dvauser' authenticated and granted access to vhost '/'
dva-caffe    |
dva-caffe    |  -------------- celery@manager.3a453a586758 v4.0.2 (latentcall)
dva-caffe    | ---- **** -----
dva-caffe    | --- * ***  * -- Linux-4.4.0-91-generic-x86_64-with-Ubuntu-14.04-trusty 2017-11-21 05:30:20
dva-caffe    | -- * - **** ---
dva-caffe    | - ** ---------- [config]
dva-caffe    | - ** ---------- .> app:         dva:0x7ff13feeb890
dva-caffe    | - ** ---------- .> transport:   amqp://dvauser:**@rabbit:5672//
dva-caffe    | - ** ---------- .> results:
dva-caffe    | - *** --- * --- .> concurrency: 1 (prefork)
dva-caffe    | -- ******* ---- .> task events: OFF (enable -E to monitor tasks in this worker)
dva-caffe    | --- ***** -----
dva-caffe    |  -------------- [queues]
dva-caffe    |                 .> bcast.57b057f2-1f95-4feb-adce-6bd0c909aa8a exchange=qmanager(fanout) key=celery
dva-caffe    |
dva-caffe    |
dva-caffe    | [tasks]
dva-caffe    |   . dva.celery.debug_task
dva-caffe    |   . manage_host
dva-caffe    |   . monitor_system
dva-caffe    |   . perform_analysis
dva-caffe    |   . perform_compression
dva-caffe    |   . perform_dataset_extraction
dva-caffe    |   . perform_decompression
dva-caffe    |   . perform_deletion
dva-caffe    |   . perform_detection
dva-caffe    |   . perform_detector_import
dva-caffe    |   . perform_detector_training
dva-caffe    |   . perform_export
dva-caffe    |   . perform_import
dva-caffe    |   . perform_indexing
dva-caffe    |   . perform_ingestion
dva-caffe    |   . perform_model_import
dva-caffe    |   . perform_retrieval
dva-caffe    |   . perform_retriever_creation
dva-caffe    |   . perform_segmentation
dva-caffe    |   . perform_stream_capture
dva-caffe    |   . perform_sync
dva-caffe    |   . perform_transformation
dva-caffe    |   . perform_video_decode
dva-caffe    |   . perform_video_decode_lambda
dva-caffe    |   . perform_video_segmentation
dva-caffe    |
dva-rmq      |
dva-rmq      | =INFO REPORT==== 21-Nov-2017::05:30:24 ===
dva-rmq      | accepting AMQP connection <0.431.0> (172.18.0.4:38064 -> 172.18.0.2:5672)
dva-rmq      |
dva-rmq      | =INFO REPORT==== 21-Nov-2017::05:30:24 ===
dva-rmq      | connection <0.431.0> (172.18.0.4:38064 -> 172.18.0.2:5672): user 'dvauser' authenticated and granted access to vhost '/'
dva-caffe    |
dva-caffe    | Done.
dva-caffe    | [localhost] local: cd 5 && wget --quiet https://www.dropbox.com/s/jytpgw8et09ede9/facenet.pb
dva-caffe    | [localhost] local: CAFFE_MODE=1 fab startq:q_detector_2 &
dva-caffe    | [localhost] local: fab startq:qmanager
dva-caffe    |
dva-caffe    | Done.
dva-rmq      |
dva-rmq      | =WARNING REPORT==== 21-Nov-2017::05:30:27 ===
dva-rmq      | closing AMQP connection <0.431.0> (172.18.0.4:38064 -> 172.18.0.2:5672, vhost: '/', user: 'dvauser'):
dva-rmq      | client unexpectedly closed TCP connection
dva-rmq      |
dva-rmq      | =WARNING REPORT==== 21-Nov-2017::05:30:27 ===
dva-rmq      | closing AMQP connection <0.416.0> (172.18.0.4:38062 -> 172.18.0.2:5672, vhost: '/', user: 'dvauser'):
dva-rmq      | client unexpectedly closed TCP connection
dva-rmq      |
dva-rmq      | =WARNING REPORT==== 21-Nov-2017::05:30:27 ===
dva-rmq      | closing AMQP connection <0.409.0> (172.18.0.4:38060 -> 172.18.0.2:5672, vhost: '/', user: 'dvauser'):
dva-rmq      | client unexpectedly closed TCP connection
dva-caffe exited with code 0

**Comment by AKSHAYUBHAT** [comment]
can you post output of 
`docker ps -a`

After SSH'ing on your VPS host OS can you do `wget localhost:8000` ?

If you do disable the firewall, make sure to change line 
https://github.com/AKSHAYUBHAT/DeepVideoAnalytics/blob/master/deploy/single/docker-compose-linode.yml#L51

from 127.0.0.1:8000:80  to 8000:80.

**Comment by debin168** [comment]
root@VM-157-162-ubuntu:~/DeepVideoAnalytics/deploy/single# docker ps -a
CONTAINER ID        IMAGE                            COMMAND                  CREATED             STATUS              PORTS                                NAMES
06354d4f835f        akshayubhat/dva-auto:latest      "bash -c 'youtube-..."   7 minutes ago       Up 26 seconds       0.0.0.0:8000->80/tcp                 dva-server
ca31fbea30bf        akshayubhat/dva-auto:caffe-cpu   "bash -c 'sleep 60..."   7 minutes ago       Up 26 seconds       8888/tcp                             dva-caffe
1537d23bbd3b        postgres                         "docker-entrypoint..."   8 minutes ago       Up 26 seconds       5432/tcp                             dva-pg
db9a02d63b0d        rabbitmq                         "docker-entrypoint..."   8 minutes ago       Up 27 seconds       4369/tcp, 5671-5672/tcp, 25672/tcp   dva-rmq


still can't access  http://49.51.34.43:8000 ,should i  do some work with ssh?

**Comment by debin168** [comment]
two minute ago,it's like this 

06354d4f835f        akshayubhat/dva-auto:latest      "bash -c 'youtube-..."   12 minutes ago      Exited (137) 3 minutes ago                       dva-server
ca31fbea30bf        akshayubhat/dva-auto:caffe-cpu   "bash -c 'sleep 60..."   12 minutes ago      Up 4 minutes                 8888/tcp            dva-caffe
1537d23bbd3b        postgres                         "docker-entrypoint..."   12 minutes ago      Up 4 minutes                 5432/tcp            dva-pg
db9a02d63b0d        rabbitmq                         "docker-entrypoint..."   12 minutes ago      Exited (0) 4 minutes ago                         dva-rmq

**Comment by AKSHAYUBHAT** [comment]
its up only for few seconds wait for few minutes for it to download and start server, also you have posted your IP address which means anyone can access its. Thats the reason I recommend tunnelling through SSH.

**Comment by AKSHAYUBHAT** [comment]
How much RAM does the machine have?

**Comment by debin168** [comment]
for test ,i just using 2G RAM. is it to less ?

**Comment by AKSHAYUBHAT** [comment]
you need at least 6 Gb for non-OCR models (i.e. not dva-caffe), for all models including OC you need at least 8 and preferably 12 Gb.
