### ISSUE TITLE
while executing cd DeepVideoAnalytics/deploy/demo && docker-compose up getting following error

### ISSUE THREAD

**Issue by kumarneeraj2005** [AKSHAYUBHAT/DeepVideoAnalytics#90]
dva-server |   File "/usr/local/lib/python2.7/dist-packages/fabric/main.py", line 757, in main
dva-server |     *args, **kwargs
dva-server |   File "/usr/local/lib/python2.7/dist-packages/fabric/tasks.py", line 426, in execute
dva-server |     results['<local-only>'] = task.run(*args, **new_kwargs)
dva-server |   File "/usr/local/lib/python2.7/dist-packages/fabric/tasks.py", line 173, in run
dva-server |     return self.wrapped(*args, **kwargs)
dva-server |   File "/root/DVA/fabfile.py", line 79, in start_container
dva-server |     launch_workers_and_scheduler_from_environment()
dva-server |   File "/root/DVA/fabfile.py", line 393, in launch_workers_and_scheduler_from_environment
dva-server |     dm = Retriever.objects.get(name=model_name)
dva-server |   File "/usr/local/lib/python2.7/dist-packages/django/db/models/manager.py", line 85, in manager_method
dva-server |     return getattr(self.get_queryset(), name)(*args, **kwargs)
dva-server |   File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 380, in get
dva-server |     self.model._meta.object_name
dva-server | dvaapp.models.DoesNotExist: Retriever matching query does not exist.
dva-server exited with code 1

**Comment by kumarneeraj2005** [comment]
Hi Akshay - please help me here, thanks

**Comment by AKSHAYUBHAT** [comment]
trying to reproduce.

**Comment by AKSHAYUBHAT** [comment]
Hi I could run the demo, make sure that you have pulled the latest image from Docker hub, since the new image now uses Tensorflow 1.4  and you might have an outdated / old image. 

You can manually remove old container images using `docker images ls` and then `docker images  rm <image_id>`
