### ISSUE TITLE
dva-server exited with code 1

### ISSUE THREAD

**Issue by lili2018** [AKSHAYUBHAT/DeepVideoAnalytics#93]
nvidia-docker-compose -f docker-compose-gpu.yml up
Starting dva-pg ... 
Starting dva-rmq ... 
Starting dva-rmq
Starting dva-pg ... done
Starting dva-server ... 
Starting dva-ocr ... 
Starting dva-server
Starting dva-ocr ... done
Attaching to dva-rmq, dva-pg, dva-server, dva-ocr
dva-pg     | 2017-12-04 11:02:14.732 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
dva-pg     | 2017-12-04 11:02:14.732 UTC [1] LOG:  listening on IPv6 address "::", port 5432
dva-pg     | 2017-12-04 11:02:14.834 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
dva-pg     | 2017-12-04 11:02:15.107 UTC [22] LOG:  database system was shut down at 2017-12-04 11:01:20 UTC
dva-pg     | 2017-12-04 11:02:15.229 UTC [1] LOG:  database system is ready to accept connections
dva-server | WARNING: Assuming --restrict-filenames since file system encoding cannot encode all characters. Set the LC_ALL environment variable to fix this.
dva-server | ERROR: can't find the current version. Please try again later.
dva-rmq    | 
dva-rmq    | =INFO REPORT==== 4-Dec-2017::11:02:18 ===
dva-rmq    | Starting RabbitMQ 3.6.14 on Erlang 19.2.1
dva-rmq    | Copyright (C) 2007-2017 Pivotal Software, Inc.
dva-rmq    | Licensed under the MPL.  See http://www.rabbitmq.com/
dva-rmq    | 
dva-rmq    |               RabbitMQ 3.6.14. Copyright (C) 2007-2017 Pivotal Software, Inc.
dva-rmq    |   ##  ##      Licensed under the MPL.  See http://www.rabbitmq.com/
dva-rmq    |   ##  ##
dva-rmq    |   ##########  Logs: tty
dva-rmq    |   ######  ##        tty
dva-rmq    |   ##########
dva-rmq    |               Starting broker...
dva-rmq    | 
dva-rmq    | =INFO REPORT==== 4-Dec-2017::11:02:18 ===
dva-rmq    | node           : rabbit@2af3bfec9b57
dva-rmq    | home dir       : /var/lib/rabbitmq
dva-rmq    | config file(s) : /etc/rabbitmq/rabbitmq.config
dva-rmq    | cookie hash    : EAAC8J3Wz2TIl0x5WyAmTA==
dva-rmq    | log            : tty
dva-rmq    | sasl log       : tty
dva-rmq    | database dir   : /var/lib/rabbitmq/mnesia/rabbit@2af3bfec9b57
dva-rmq    | 
dva-rmq    | =INFO REPORT==== 4-Dec-2017::11:02:19 ===
dva-rmq    | Memory high watermark set to 3162 MiB (3315626803 bytes) of 7905 MiB (8289067008 bytes) total
dva-rmq    | 
dva-rmq    | =INFO REPORT==== 4-Dec-2017::11:02:19 ===
dva-rmq    | Enabling free disk space monitoring
dva-rmq    | 
dva-rmq    | =INFO REPORT==== 4-Dec-2017::11:02:19 ===
dva-rmq    | Disk free limit set to 50MB
dva-rmq    | 
dva-rmq    | =INFO REPORT==== 4-Dec-2017::11:02:19 ===
dva-rmq    | Limiting to approx 1048476 file handles (943626 sockets)
dva-rmq    | 
dva-rmq    | =INFO REPORT==== 4-Dec-2017::11:02:19 ===
dva-rmq    | FHC read buffering:  OFF
dva-rmq    | FHC write buffering: ON
dva-rmq    | 
dva-rmq    | =INFO REPORT==== 4-Dec-2017::11:02:19 ===
dva-rmq    | Waiting for Mnesia tables for 30000 ms, 9 retries left
dva-rmq    | 
dva-rmq    | =INFO REPORT==== 4-Dec-2017::11:02:19 ===
dva-rmq    | Waiting for Mnesia tables for 30000 ms, 9 retries left
dva-rmq    | 
dva-rmq    | =INFO REPORT==== 4-Dec-2017::11:02:19 ===
dva-rmq    | Priority queues enabled, real BQ is rabbit_variable_queue
dva-rmq    | 
dva-rmq    | =INFO REPORT==== 4-Dec-2017::11:02:19 ===
dva-rmq    | Starting rabbit_node_monitor
dva-rmq    | 
dva-rmq    | =INFO REPORT==== 4-Dec-2017::11:02:19 ===
dva-rmq    | msg_store_transient: using rabbit_msg_store_ets_index to provide index
dva-rmq    | 
dva-rmq    | =INFO REPORT==== 4-Dec-2017::11:02:19 ===
dva-rmq    | msg_store_persistent: using rabbit_msg_store_ets_index to provide index
dva-rmq    | 
dva-rmq    | =WARNING REPORT==== 4-Dec-2017::11:02:19 ===
dva-rmq    | msg_store_persistent: rebuilding indices from scratch
dva-rmq    | 
dva-rmq    | =INFO REPORT==== 4-Dec-2017::11:02:19 ===
dva-rmq    | started TCP Listener on [::]:5672
dva-rmq    |  completed with 0 plugins.
dva-rmq    | 
dva-rmq    | =INFO REPORT==== 4-Dec-2017::11:02:19 ===
dva-rmq    | Server startup complete; 0 plugins started.
dva-server | WARNING:root:Could not import Tensorflow assuming operating in either frontend or caffe/pytorch mode
dva-server | WARNING:root:Could not import indexer / clustering assuming running in front-end mode / Heroku
dva-server | Traceback (most recent call last):
dva-server |   File "manage.py", line 22, in <module>
dva-server |     execute_from_command_line(sys.argv)
dva-server |   File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
dva-server |     utility.execute()
dva-server |   File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 356, in execute
dva-server |     self.fetch_command(subcommand).run_from_argv(self.argv)
dva-server |   File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 283, in run_from_argv
dva-server |     self.execute(*args, **cmd_options)
dva-server |   File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 330, in execute
dva-server |     output = self.handle(*args, **options)
dva-server |   File "/usr/local/lib/python2.7/dist-packages/django/core/management/commands/makemigrations.py", line 110, in handle
dva-server |     loader.check_consistent_history(connection)
dva-server |   File "/usr/local/lib/python2.7/dist-packages/django/db/migrations/loader.py", line 282, in check_consistent_history
dva-server |     applied = recorder.applied_migrations()
dva-server |   File "/usr/local/lib/python2.7/dist-packages/django/db/migrations/recorder.py", line 65, in applied_migrations
dva-server |     self.ensure_schema()
dva-server |   File "/usr/local/lib/python2.7/dist-packages/django/db/migrations/recorder.py", line 52, in ensure_schema
dva-server |     if self.Migration._meta.db_table in self.connection.introspection.table_names(self.connection.cursor()):
dva-server |   File "/usr/local/lib/python2.7/dist-packages/django/db/backends/base/base.py", line 254, in cursor
dva-server |     return self._cursor()
dva-server |   File "/usr/local/lib/python2.7/dist-packages/django/db/backends/base/base.py", line 229, in _cursor
dva-server |     self.ensure_connection()
dva-server |   File "/usr/local/lib/python2.7/dist-packages/django/db/backends/base/base.py", line 213, in ensure_connection
dva-server |     self.connect()
dva-server |   File "/usr/local/lib/python2.7/dist-packages/django/db/utils.py", line 94, in __exit__
dva-server |     six.reraise(dj_exc_type, dj_exc_value, traceback)
dva-server |   File "/usr/local/lib/python2.7/dist-packages/django/db/backends/base/base.py", line 213, in ensure_connection
dva-server |     self.connect()
dva-server |   File "/usr/local/lib/python2.7/dist-packages/django/db/backends/base/base.py", line 189, in connect
dva-server |     self.connection = self.get_new_connection(conn_params)
dva-server |   File "/usr/local/lib/python2.7/dist-packages/django/db/backends/postgresql/base.py", line 176, in get_new_connection
dva-server |     connection = Database.connect(**conn_params)
dva-server |   File "/usr/local/lib/python2.7/dist-packages/psycopg2/__init__.py", line 130, in connect
dva-server |     conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
dva-server | django.db.utils.OperationalError: could not connect to server: Connection refused
dva-server | 	Is the server running on host "db" (172.18.0.3) and accepting
dva-server | 	TCP/IP connections on port 5432?
dva-server | 
dva-server | 
dva-server | Fatal error: local() encountered an error (return code 1) while executing 'python manage.py makemigrations'
dva-server | 
dva-server | Aborting.
dva-server | [localhost] local: python manage.py makemigrations
dva-server exited with code 1
dva-ocr    | Traceback (most recent call last):
dva-ocr    |   File "/usr/local/lib/python2.7/dist-packages/fabric/main.py", line 757, in main
dva-ocr    |     *args, **kwargs
dva-ocr    |   File "/usr/local/lib/python2.7/dist-packages/fabric/tasks.py", line 426, in execute
dva-ocr    |     results['<local-only>'] = task.run(*args, **new_kwargs)
dva-ocr    |   File "/usr/local/lib/python2.7/dist-packages/fabric/tasks.py", line 173, in run
dva-ocr    |     return self.wrapped(*args, **kwargs)
dva-ocr    |   File "/root/DVA/fabfile.py", line 73, in start_container
dva-ocr    |     init_models()
dva-ocr    |   File "/usr/local/lib/python2.7/dist-packages/fabric/tasks.py", line 170, in __call__
dva-ocr    |     return self.run(*args, **kwargs)
dva-ocr    |   File "/usr/local/lib/python2.7/dist-packages/fabric/tasks.py", line 173, in run
dva-ocr    |     return self.wrapped(*args, **kwargs)
dva-ocr    |   File "/root/DVA/fabfile.py", line 560, in init_models
dva-ocr    |     model_type=DeepModel.DETECTOR
dva-ocr    |   File "/usr/local/lib/python2.7/dist-packages/django/db/models/manager.py", line 85, in manager_method
dva-ocr    |     return getattr(self.get_queryset(), name)(*args, **kwargs)
dva-ocr    |   File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 464, in get_or_create
dva-ocr    |     return self.get(**lookup), False
dva-ocr    |   File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 374, in get
dva-ocr    |     num = len(clone)
dva-ocr    |   File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 232, in __len__
dva-ocr    |     self._fetch_all()
dva-ocr    |   File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 1118, in _fetch_all
dva-ocr    |     self._result_cache = list(self._iterable_class(self))
dva-ocr    |   File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 53, in __iter__
dva-ocr    |     results = compiler.execute_sql(chunked_fetch=self.chunked_fetch)
dva-ocr    |   File "/usr/local/lib/python2.7/dist-packages/django/db/models/sql/compiler.py", line 882, in execute_sql
dva-ocr    |     cursor = self.connection.cursor()
dva-ocr    |   File "/usr/local/lib/python2.7/dist-packages/django/db/backends/base/base.py", line 254, in cursor
dva-ocr    |     return self._cursor()
dva-ocr    |   File "/usr/local/lib/python2.7/dist-packages/django/db/backends/base/base.py", line 229, in _cursor
dva-ocr    |     self.ensure_connection()
dva-ocr    |   File "/usr/local/lib/python2.7/dist-packages/django/db/backends/base/base.py", line 213, in ensure_connection
dva-ocr    |     self.connect()
dva-ocr    |   File "/usr/local/lib/python2.7/dist-packages/django/db/utils.py", line 94, in __exit__
dva-ocr    |     six.reraise(dj_exc_type, dj_exc_value, traceback)
dva-ocr    |   File "/usr/local/lib/python2.7/dist-packages/django/db/backends/base/base.py", line 213, in ensure_connection
dva-ocr    |     self.connect()
dva-ocr    |   File "/usr/local/lib/python2.7/dist-packages/django/db/backends/base/base.py", line 189, in connect
dva-ocr    |     self.connection = self.get_new_connection(conn_params)
dva-ocr    |   File "/usr/local/lib/python2.7/dist-packages/django/db/backends/postgresql/base.py", line 176, in get_new_connection
dva-ocr    |     connection = Database.connect(**conn_params)
dva-ocr    |   File "/usr/local/lib/python2.7/dist-packages/psycopg2/__init__.py", line 130, in connect
dva-ocr    |     conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
dva-ocr    | django.db.utils.OperationalError: could not connect to server: Connection refused
dva-ocr    | 	Is the server running on host "db" (172.18.0.3) and accepting
dva-ocr    | 	TCP/IP connections on port 5432?
dva-ocr    | 
dva-ocr exited with code 1

**Comment by AKSHAYUBHAT** [comment]
Can you post output of `docker ps -a`

It appears that the postgres container is not running. 

```
dva-server | connection = Database.connect(**conn_params)
dva-server | File "/usr/local/lib/python2.7/dist-packages/psycopg2/init.py", line 130, in connect
dva-server | conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
dva-server | django.db.utils.OperationalError: could not connect to server: Connection refused
dva-server | Is the server running on host "db" (172.18.0.3) and accepting
dva-server | TCP/IP connections on port 5432?
dva-server |
dva-server |
dva-server | Fatal error: local() encountered an error (return code 1) while executing 'python manage.py makemigrations'
dva-server |
dva-server | Aborting.
dva-server | [localhost] local: python manage.py makemigrations
dva-server exited with code 1
```

**Comment by lili2018** [comment]
docker ps -a
CONTAINER ID        IMAGE                        COMMAND                  CREATED              STATUS                      PORTS                                                    NAMES
2c24ad650019        akshayubhat/dva-auto:caffe   "bash -c 'sleep 60..."   About a minute ago   Exited (1) 9 seconds ago                                                             dva-ocr
bf167098245f        akshayubhat/dva-auto:gpu     "bash -c 'youtube-..."   About a minute ago   Up About a minute           6006/tcp, 0.0.0.0:8888->8888/tcp, 0.0.0.0:8000->80/tcp   dva-server
cfdfea9b9873        rabbitmq                     "docker-entrypoint..."   2 minutes ago        Up About a minute           4369/tcp, 5671-5672/tcp, 25672/tcp                       dva-rmq
0aa6daaa5cc6        postgres                     "docker-entrypoint..."   2 minutes ago        Up About a minute           5432/tcp                                                 dva-pg
19ab0f16df29        ubuntu                       "ping 8.8.8.8"           18 hours ago         Created                                                                              priceless_elion
e6b52088dcc8        ubuntu                       "ping 8.8.8.8"           18 hours ago         Created                                                                              blissful_gates
cae4ca9b994c        2554e763fdc2                 "/bin/sh -c 'apt-g..."   18 hours ago         Exited (100) 18 hours ago                                                            youthful_engelbart
b88f6ef1260d        2554e763fdc2                 "/bin/sh -c 'apt-g..."   18 hours ago         Exited (100) 18 hours ago                                                            gracious_boyd
f5ced46268ef        2554e763fdc2                 "/bin/sh -c 'apt-g..."   18 hours ago         Exited (100) 18 hours ago                                                            hungry_bell
fd43cffe2f9a        12158275f3f9                 "/bin/sh -c 'pip i..."   5 days ago           Exited (1) 5 days ago                                                                naughty_sinoussi
b133ce0b960e        12158275f3f9                 "/bin/sh -c 'pip i..."   5 days ago           Exited (1) 5 days ago                                                                admiring_sammet
9f3341bf3510        12158275f3f9                 "/bin/sh -c 'pip i..."   5 days ago           Exited (1) 5 days ago                                                                kind_mcclintock
18cdc98bf62c        12158275f3f9                 "/bin/sh -c 'pip i..."   5 days ago           Exited (1) 5 days ago                                                                gifted_curran
e890071ff170        12158275f3f9                 "/bin/sh -c 'pip i..."   5 days ago           Exited (2) 5 days ago                                                                objective_easley
f1688c2bae1c        12158275f3f9                 "/bin/sh -c 'pip i..."   5 days ago           Exited (1) 5 days ago                                                                lucid_heisenberg
aaf646769848        12158275f3f9                 "/bin/sh -c 'pip i..."   5 days ago           Exited (1) 5 days ago                                                                affectionate_mcclintock

**Comment by AKSHAYUBHAT** [comment]
Hey I just posted new version of `deploy/single/docker-compose-gpu.yml` which no longer requires dva-auto:caffe, can you try with that, also make sure you have new versions of the container, which you can auto-pull by removing old containers using `docker rmi dva-auto:latest` and `docker rmi dva-auto:gpu`.
