### ISSUE TITLE
Change in code base

### ISSUE THREAD

**Issue by kumarneeraj2005** [AKSHAYUBHAT/DeepVideoAnalytics#94]
Hi Akshay, i made some changes in code base but its reverting back to your changes, please help me here how to stop accepting code changes from your latest build.
here is your docker compose file.

version: '3'
 services:
   db:
     image: postgres
     container_name: dva-pg
     volumes:
      - dvapgdata:/var/lib/postgresql/data
     environment:
       - POSTGRES_USER=pgdbuser
       - POSTGRES_PASSWORD=pgdbpass
   rabbit:
     image: rabbitmq
     container_name: dva-rmq
     environment:
       - RABBITMQ_DEFAULT_USER=dvauser
       - RABBITMQ_DEFAULT_PASS=localpass
     volumes:
       - dvarabbit:/var/lib/rabbitmq
   dva:
     image: akshayubhat/dva-auto:latest
     container_name: dva-server
     environment:
       - DOCKER_MODE=true
       - RABBIT_HOST=rabbit
       - RABBIT_USER=dvauser
       - RABBIT_PASS=localpass
       - DB_HOST=db
       - DB_NAME=postgres
       - DB_USER=pgdbuser
       - DB_PASS=pgdbpass
       - LAUNCH_SERVER=1
       - LAUNCH_BY_NAME_indexer_inception=1
       - LAUNCH_BY_NAME_indexer_facenet=1
       - LAUNCH_BY_NAME_retriever_inception=1
       - LAUNCH_BY_NAME_retriever_facenet=1
       - LAUNCH_BY_NAME_detector_coco=1
       - LAUNCH_BY_NAME_analyzer_crnn=1
       - LAUNCH_BY_NAME_analyzer_tagger=1
       - LAUNCH_BY_NAME_detector_face=1
       - LAUNCH_Q_qclusterer=1
       - LAUNCH_Q_qextract=1
       - LAUNCH_SCHEDULER=1
       - TEST=1
       - AUTH_DISABLED=1
     command: bash -c "youtube-dl -U && git pull && sleep 45 && fab migrate && fab start_container:server"
     ports:
       - "8000:8000"
     depends_on:

**Comment by AKSHAYUBHAT** [comment]
You should remove the `git pull` from following line.

```
command: bash -c "youtube-dl -U && git pull && sleep 45 && fab migrate && fab start_container:server"
```
