### ISSUE TITLE
Update text detection CTPN by incorporating recent changes

### ISSUE THREAD

**Issue by AKSHAYUBHAT** [AKSHAYUBHAT/DeepVideoAnalytics#95]
Incorporate changes and new model from:

https://github.com/eragonruan/text-detection-ctpn/pull/54

**Comment by jackylee1** [comment]
hi, great job.but when i execute cd DeepVideoAnalytics && python manage.py start cpu

it shows the address of the jupter book.
and then what should i do .i just didn't see the webui show as your video introduction.
