### ISSUE TITLE
How to run ipyunb file.

### ISSUE THREAD

**Issue by arsalan993** [AKSHAYUBHAT/DeepVideoAnalytics#98]
I am on ubuntu. I setup the doctor but after downloading all file this was displaying on terminal 
"root@7e44b83847de:~/DVA#" 
i dont know what to do further . i cant even run ipynb files /notebook/OCR folders.
You mentioned to open up the link. i cant find any link on terminal. 
Just tell me simple method on what to do after dockers get finish downloading all files

**Comment by AKSHAYUBHAT** [comment]
Did you use `docker run` command or `docker-compose up`? 
If you have have used latter, open localhost:8000 in browser to view the UI. 
Regarding IPython notebooks I am still working on them. 
I will post a better tutorial with a video demo in couple of days.

**Comment by arsalan993** [comment]
as being told on this page 
https://github.com/AKSHAYUBHAT/DeepVideoAnalytics/tree/master/notebooks/OCR
i ran the following command since i dont have GPU installed
docker run -p 8888:8888 -it akshayubhat/dva-auto:latest
It first pulled all files and ended up at "root@7e44b83847de:~/DVA#" 
there ware jupyter notebook url present .. 
i my self installed jupyter notebook inside docker but still unable to access it via browser on my ubuntu host.

**Comment by AKSHAYUBHAT** [comment]
Oh cd into notebooks/OCR and then run `juputer notebook --allow-root` it will display a localhost url containing the key. Just copy paste it in the browser to open notebook.

**Comment by arsalan993** [comment]
yes the link was generated but when i post that onto my brower "firefox" nothing comes up

**Comment by AKSHAYUBHAT** [comment]
This happened because you have multiple jupyter notebook servers running the first one at 8888 and second one at 8889. However you have onlu port 8888 mapped.  Close the newest juputer server and then run `jupyter notebook list` to get url for the first one which is at 8888.

**Comment by arsalan993** [comment]
so i restart everything 
and ran `jupyter notebook list`
and i got this out
root@2459f3bcf6e2:~/DVA/notebooks/OCR# jupyter notebook list
Currently running servers:
root@2459f3bcf6e2:~/DVA/notebooks/OCR# 
so initially no server was running
and besides i have to pip install jupyter notebook again .. its not already present

**Comment by arsalan993** [comment]
and now when i run 
`jupyter notebook --allow-root`
i get this
`http://localhost:8888/?token=f69bc9711f058efb84ff17b528176bb8672dfa80eb4309e1`
but when i copy paste this on browser still no connection

**Comment by arsalan993** [comment]
I guess the main issue is
`no web browser found. Could not locate runnable browser`

**Comment by AKSHAYUBHAT** [comment]
This is a common jupyter error google the fix.
